#!/bin/sh

# i-MSCP a internet Multi Server Control Panel
#
# Copyright (C) 2010 by internet Multi Server Control Panel - http://i-mscp.net
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>
#
# The Original Code is "i-MSCP internet Multi Server Control Panel".
#
# The Initial Developer of the Original Code is i-MSCP Team.
# Portions created by Initial Developer are Copyright (C) 22010 by
# internet Multi Server Control Panel. All Rights Reserved.
#
# @category		i-MSCP
# @copyright	2010 by i-MSCP | http://i-mscp.net
# @author		Daniel Andreca <sci2tech@i-mscp.net>
# @version		SVN: $Id$
# @link			http://i-mscp.net i-MSCP Home Site
# @license		http://www.gnu.org/licenses/ GPL v2

SYSTEM_FOLDERS='
				INST_PREF=/tmp/imscp
				ROOT_CONF=${INST_PREF}/etc
				SYSTEM_ROOT=${INST_PREF}/var/www/imscp
				SYSTEM_CONF=${INST_PREF}/etc/imscp
				SYSTEM_LOG=${INST_PREF}/var/log/imscp
				SYSTEM_APACHE_BACK_LOG=${INST_PREF}/var/log/apache2/backup
				SYSTEM_VIRTUAL=${INST_PREF}/var/www/virtual
				SYSTEM_AWSTATS=${INST_PREF}/var/www/awstats
				SYSTEM_FCGI=${INST_PREF}/var/www/fcgi
				SYSTEM_SCOREBOARDS=${INST_PREF}/var/www/scoreboards
				SYSTEM_MAIL_VIRTUAL=${INST_PREF}/var/mail/virtual

				ROOT_APACHE_CONF=${ROOT_CONF}/apache2

				ROOT_POSTFIX_CONF=${ROOT_CONF}/postfix

				ROOT_COURIER_CONF=${ROOT_CONF}/courier
'
FOLDERS='${SYSTEM_LOG}/imscp-arpl-msgr'
COPY_FILE=''
CREATE_FILE=''
CHOWN_FILE=''
CHMOD_FILE=''
