#!/bin/sh

# i-MSCP a internet Multi Server Control Panel
#
# Copyright (C) 2010 by internet Multi Server Control Panel - http://i-mscp.net
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>
#
# The Original Code is "i-MSCP internet Multi Server Control Panel".
#
# The Initial Developer of the Original Code is i-MSCP Team.
# Portions created by Initial Developer are Copyright (C) 22010 by
# internet Multi Server Control Panel. All Rights Reserved.
#
# @category		i-MSCP
# @copyright	2010 by i-MSCP | http://i-mscp.net
# @author		Daniel Andreca <sci2tech@i-mscp.net>
# @version		SVN: $Id: Database.php 3702 2010-11-16 14:20:55Z sci2tech $
# @link			http://i-mscp.net i-MSCP Home Site
# @license		http://www.gnu.org/licenses/ GPL v2

writelog() {
	_logline="${1}";
	printf "${1}";
	_logline=$(printf "$_logline" | sed -r 's~'$(echo "\033")'\[[0-9;]{1,4}m~~g'; printf x);
	_logline="${_logline%x}"
	if [ "${SYSTEM_LOG}" ]; then
		if [ "${FlushTXT}" ]; then
			LOG=$(echo ${SYSTEM_LOG}| sed 's~'${INST_PREF}'~~g');
			${mkdir} -p "${LOG}"
			#if [ -f "${LOG}/imscp-build.log" ]; then ${rm} "${LOG}/imscp-build.log"; fi
			${touch} "${LOG}/imscp-build.log"
			${chmod} 0660 "${LOG}/imscp-build.log"
			printf "${FlushTXT}${_logline}" >> "${LOG}/imscp-build.log"
			FlushTXT='';
		fi
		printf "${_logline}" >> "${LOG}/imscp-build.log"
	else
		FlushTXT="${FlushTXT}${_logline}"
	fi
}
