<?xml version="1.0" encoding="UTF-8" ?>
<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
    <head>
	    <?php $this->headLink()->appendStylesheet('/themes/default/css/imscp.css')?>
		<?php echo $this->headTitle(), PHP_EOL; ?>
		<?php echo $this->headMeta(), PHP_EOL; ?>
		<?php echo $this->headLink(), PHP_EOL; ?>
		<?php echo $this->headScript(), PHP_EOL ?>
    </head>
	<body>
		<div class="header">
			<div class="main_menu">
				<?php echo $this->navigation()->menu()->setMaxDepth(0)->setUlClass('icon'); ?>
			</div>
			<div class="logo"><img src="/themes/default/images/imscp_logo.png" alt="i-MSCP" /></div>
		</div>
		<div class="location">
		    <div class="location-area icons-left">
		        <?php echo $this->navigation()->breadcrumbs()->setPartial('_sections.phtml')->setMinDepth(0)->setMaxDepth(0);?>
		    </div>
		    <ul class="location-menu">
		        <li><a class="logout" href="../index.php?logout">Logout</a></li>
		    </ul>
		    <ul class="path">
				<?php echo $this->navigation()->breadcrumbs()->setMaxDepth(1)->setPartial('_breadcrumbs.phtml');?>
		    </ul>
		</div>
		<div class="left_menu">
			<?php echo $this->navigation()->menu()->setOnlyActiveBranch(true)->setRenderParents(false)->setUlClass('')->setMinDepth(1)->setMaxDepth(0);
			?>
		</div>
		<div class="body">
			<?php echo $this->layout()->content; ?>
		</div>
		<div class="footer">
			<?php
				echo $this->productShortName . ' ' . $this->productVersion . '<br />Codename: ' . $this->productCodeName .
					'<br />Build: ' . $this->productBuild;
			?>
		</div>
    </body>
</html>
