<?xml version="1.0" encoding="UTF-8"?>
<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
    <head>
	    <?php $this->headLink()->appendStylesheet('/themes/default/red/color.css')?>
	    <?php $this->headLink()->appendStylesheet('/themes/default/css/imscp.css')?>
		<?php echo $this->headTitle(), PHP_EOL;?>
		<?php echo $this->headMeta(), PHP_EOL;?>
		<?php echo $this->headLink(), PHP_EOL;?>
		<?php echo $this->headScript(), PHP_EOL;?>
	    <?php echo $this->jQuery(), PHP_EOL;?>
    </head>
	<body>
		<div class="header">
			<div class="main_menu">
				<?php echo $this->navigation()->menu()->setMaxDepth(0)->setUlClass('icon');?>
			</div>
			<div class="logo"><img src="/themes/default/images/imscp_logo.png" alt="<?php echo $this->productShortName;?>" /></div>
		</div>
		<div class="location">
		    <div class="location-area icons-left">
		        <?php echo $this->navigation()->breadcrumbs()->setPartial('_section.phtml')->setMinDepth(0)->setMaxDepth(0);?>
		    </div>
		    <ul class="path">
				<?php echo $this->navigation()->breadcrumbs()->setMaxDepth(3)->setPartial('_breadcrumbs.phtml');?>
		    </ul>
		    <ul class="location-menu">
			    <li><?php echo $this->translate('Logged in as');?> <a class="logged-as" style="color:#fff" href="<?php echo $this->url(array(),'core_authentication_logout');?>">Admin</a></li>
		        <li><a class="logout" href="<?php echo $this->url(array(),'core_authentication_logout');?>"><?php echo $this->translate('Logout');?></a></li>
		    </ul>
		</div>
		<div class="left_menu">
			<?php echo $this->navigation()->menu()->setOnlyActiveBranch(true)->setRenderParents(false)->setUlClass('')->setMinDepth(1)->setMaxDepth(0);?>
		</div>
		<div class="body">
			<?php if ($this->message):?>
			<div class="<?php echo $this->message['type']; ?> message"><?php echo $this->message['message']; ?></div>
			<?php endif; ?>
			<?php echo $this->layout()->content;?>
		</div>
		<div class="footer">
			<?php echo $this->productShortName . ' ' . $this->productVersion . '<br />Codename: ' . $this->productCodeName . '<br />Build: ' . $this->productBuild;?>
			<p style="margin-top:10px">
				<a href="http://validator.w3.org/check?uri=referer"><img style="border:none;" src="http://www.w3.org/Icons/valid-xhtml10-blue" alt="Valid XHTML 1.0 Transitional" height="31" width="88" /></a>
			</p>
		</div>
    </body>
</html>
