<?xml version="1.0" encoding="UTF-8" ?>
<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
	<head>
	    <?php $this->headLink()->appendStylesheet('/themes/default/css/simple.css');?>
		<?php echo $this->headTitle(), PHP_EOL;?>
		<?php echo $this->headMeta(), PHP_EOL;?>
		<?php echo $this->headLink(), PHP_EOL;?>
		<?php echo $this->headScript(), PHP_EOL?>
	</head>
	<body onload="document.login_frm.uname.focus()" class="body">
		<div class="header">
			<div id="logo">
				<div id="logoInner">
					<img src="/themes/default/images/imscp_logo32.png" alt="internet Multi Server Control Panel" />
					<span>internet Multi Server Control Panel</span>
				</div>
			</div>
			<div id="copyright">
				<div id="copyrightInner">
					<a href="http://www.i-mscp.net" target="blank" tabindex="8">
						&copy; Copyright 2010 i-MSCP Team<br/>All Rights Reserved
					</a>
				</div>
			</div>
		</div>
		<?php echo $this->layout()->content; ?>
	</body>
</html>
