<?xml version="1.0" encoding="UTF-8" ?>
<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
	<head>
		<?php
			$this->headTitle('i-MSCP - internet Multi Server Control Panel / Login');
			$this->headMeta()->appendName('robots', 'nofollow, noindex')
				->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
				->appendHttpEquiv('X-UA-Compatible', 'IE=8')
				->appendHttpEquiv('Content-Style-Type', 'text/css')
				->appendHttpEquiv('Content-Script-Type', 'text/javascript');
			$this->headLink()->appendStylesheet('/themes/default/css/simple.css')
                 ->headLink(array('rel' => 'favicon', 'href' => '/favicon.ico'),'PREPEND');
			$this->headScript()->appendFile('/themes/default/js/DD_belatedPNG_0.0.8a-min.js', 'text/javascript', array('conditional' => 'IE 6'))
				->appendScript("DD_belatedPNG.fix('*');" . PHP_EOL, 'text/javascript', array('conditional' => 'IE 6'));
			echo $this->headTitle(), PHP_EOL, $this->headMeta(), PHP_EOL, $this->headLink(), PHP_EOL, $this->headScript(), PHP_EOL;
		?>

	</head>
	<body onload="document.login_frm.uname.focus()" class="body">
		<div class="header">
			<div id="logo">
				<div id="logoInner">
					<img src="/themes/default/images/imscp_logo32.png" alt="internet Multi Server Control Panel" />
					<span>internet Multi Server Control Panel</span>
				</div>
			</div>
			<div id="copyright">
				<div id="copyrightInner">
					<a href="http://www.i-mscp.net" target="blank" tabindex="8">
						&copy; Copyright 2010 i-MSCP Team<br/>All Rights Reserved
					</a>
				</div>
			</div>
		</div>
		<?php echo $this->layout()->content; ?>
	</body>
</html>
