#!/bin/bash

# ispCP ω (OMEGA) a Virtual Hosting Control System
# Copyright (c) 2007 by ispCP
# http://www.isp-control.net
#
#
# License:
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of the MPL Mozilla Public License
#    as published by the Free Software Foundation; either version 1.1
#    of the License, or (at your option) any later version.

#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    MPL Mozilla Public License for more details.
#
#    You may have received a copy of the MPL Mozilla Public License
#    along with this program.
#
#    An on-line copy of the MPL Mozilla Public License can be found
#    http://www.mozilla.org/MPL/MPL-1.1.html
#
#
# The ispCP Home Page is at:
#
#    http://www.isp-control.net

RMMOD='/sbin/rmmod'

IPTABLES="/sbin/iptables"

${RMMOD} ipchains 1>/tmp/ispcp_network.log 2>/tmp/ispcp_network.err.log

# all traffic

${IPTABLES} -I INPUT

${IPTABLES} -I OUTPUT

# web traffic

${IPTABLES} -I INPUT -p tcp --dport 80
${IPTABLES} -I OUTPUT -p tcp --sport 80

# pop3 traffic

${IPTABLES} -I INPUT -p tcp --dport 110
${IPTABLES} -I OUTPUT -p tcp --sport 110

# imap traffic

${IPTABLES} -I INPUT -p tcp --dport 143
${IPTABLES} -I OUTPUT -p tcp --sport 143

# mail traffic

${IPTABLES} -I INPUT  -p tcp --dport 25
${IPTABLES} -I OUTPUT -p tcp --sport 25
