#!/bin/sh
# $Id: vhcs2.init,v 1.0 2006/01/09 17:54:30 Ugo Viti <ugo.viti@initzero.it> $
#
# PID file, vhcs2_network added by Carsten Schoene <cs@linux-administrator.com>
#
# description:	VHCS2 (Virtual Hosting Control System) Daemon
#
# chkconfig:	- 90 30
# processname:	vhcs2_daemon
# config:	/etc/vhcs2/vhcs2.conf
# pidfile:	/var/run/vhcs2_daemon.pid

lockfile=/var/lock/subsys/vhcs2
PID=/var/run/vhcs2_daemon.pid
prog=vhcs2_daemon

# Source function library.
. /etc/rc.d/init.d/functions

prog=vhcs2_daemon
progpath=/var/www/vhcs2/daemon

start() {
        echo -n $"Starting $prog: "
        daemon $progpath/$prog -p $PID
        RETVAL=$?
        [ $RETVAL -eq 0 ] && touch $lockfile >/dev/null 2>&1
        echo
}

stop() {
        echo -n $"Shutting down $prog: "
        killproc $prog
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f $lockfile
}

status() {
		if [ -s $pidfile ]; then
			pid=`cat $pidfile`
			kill -0 $pid >/dev/null 2>&1
			if [ "$?" = "0" ]; then
				echo "$prog (pid $pid) is running"
				RETVAL=0
			else
				echo "$prog is stopped"
				RETVAL=1
			fi
		else
			echo "$prog is stopped"
			RETVAL=1
		fi
}

case "$1" in
  start)
        start
		/etc/init.d/vhcs2_network
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        start
        ;;
  status)
        status $prog
        RETVAL=$?
        ;;
  *)
        echo "Usage: $prog {start|stop|restart|status}"
        exit 1
esac

exit $RETVAL

