<?xml version="1.0" encoding="UTF-8" ?>
<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=8" />
		<title>i-MSCP - internet Multi Server Control Panel - Error</title>
		<meta name="robots" content="nofollow, noindex" />
		<meta http-equiv="Content-Style-Type" content="text/css" />
	    <?php echo $this->headLink()->appendStylesheet('/themes/default/red/color.css'), PHP_EOL;?>
		<link href="/themes/default/css/simple.css" rel="stylesheet" type="text/css" />
		<link href="/themes/default/css/exception.css" rel="stylesheet" type="text/css" />
	</head>
	<body>
		<div class="header">
			<div id="logo">
				<div id="logoInner">
					<img src="/themes/default/images/imscp_logo32.png" alt="<?php echo $this->productShortName;?>" />
					<span><?php echo $this->productLongName;?></span>
				</div>
			</div>
			<div id="copyright">
				<div id="copyrightInner">
					<a href="http://www.imscp.net" tabindex="8"><?php echo $this->productCopyright;?></a>
				</div>
			</div>
		</div>
		<div class="box">
			<div class="boxHeader"></div>
			<div class="content">
				<h1><?php echo $this->translate('An error occurred');?></h1>
				<?php if (isset($this->exception)):?>
				<p><strong><?php echo $this->translate('Message');?>:</strong> <?php echo $this->exception->getMessage();?></p>
				<?php else: ?>
				<p><?php echo $this->message;?></p>
				<?php endif ?>
				<a href="#" onclick="history.go(-1);return false;"><?php echo $this->translate('Back');?></a>
			</div>
		</div>

<?php if (isset($this->exception)):?>
<div style="margin-top:310px;padding:10px;">
  <h4><?php echo $this->translate('Stack trace');?>:</h4>
  <pre ><?php echo $this->exception->getTraceAsString();?></pre>
<!--
  <h4>Request Parameters:</h4>
  <pre><?php //echo var_export($this->request->, true); ?></pre>
-->
  <?php endif ?>
</div>
	</body>
</html>
