#!/bin/sh
#
# chkconfig: - 91 35
# description: Starts and stops the ISPCP daemon
#
# pidfile: /var/run/imscp.pid
# config:  /etc/imscp/imscp.conf
#
# ispCP ω (OMEGA) a Virtual Hosting Control Panel
# Copyright (C) 2006-2010 by isp Control Panel - http://ispcp.net
#
# Version: $Id$
#
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is "ispCP ω (OMEGA) a Virtual Hosting Control Panel".
#
# The Initial Developer of the Original Code is ispCP Team.
# Portions created by Initial Developer are Copyright (C) 2006-2010 by
# isp Control Panel. All Rights Reserved.
#
# The ispCP ω Home Page is:
#
#    http://isp-control.net
#

# Source function library.
if [ -f /etc/init.d/functions ] ; then
  . /etc/init.d/functions
elif [ -f /etc/rc.d/init.d/functions ] ; then
  . /etc/rc.d/init.d/functions
else
  exit 0
fi

# Avoid using root's TMPDIR
unset TMPDIR

# Source networking configuration.
. /etc/sysconfig/network

if [ -f /var/www/imscp/daemon ]; then
   . /var/www/imscp/daemon
fi

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0

# Check that imscp.conf exists.
[ -f /etc/imscp/imscp.conf ] || exit 0

RETVAL=0


start() {
        KIND="I-MSCP"
	echo -n $"Starting $KIND services: "
	daemon /var/www/imscp/daemon/imscp_daemon
	RETVAL=$?
	echo
      	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/imscp || RETVAL=1
	echo ""
	return $RETVAL
}

stop() {
        KIND="I-MSCP"
	echo -n $"Shutting down $KIND services: "
	killproc imscp_daemon
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/imscp
	echo ""
	return $RETVAL
}

restart() {
	stop
	start
}

reload() {
	echo -n $"Reloading imscp.conf: "
	killproc imscp_daemon -HUP
	RETVAL=$?
	echo
	return $RETVAL
}

rhstatus() {
	status imscp_daemon
	RETVAL=$?
	if [ $? -ne 0 -o $RETVAL -ne 0 ] ; then
		return 1
	fi
}


# Allow status as non-root.
if [ "$1" = status ]; then
       rhstatus
       exit $?
fi

# Check that we can write to it... so non-root users stop here
[ -w /etc/imscp/imscp.conf ] || exit 0



case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart)
  	restart
	;;
  reload)
  	reload
	;;
  status)
  	rhstatus
	;;
  condrestart)
  	[ -f /var/lock/subsys/imscp ] && restart || :
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|reload|status|condrestart}"
	exit 1
esac

exit $?
