<?php $this->headTitle($this->translate('Lost Password'));?>
<?php $this->jQuery()->addOnload('$("#captcha").focus()');?>

		<!-- BDP: page_message -->
		<!--<div class="{MESSAGE_CLS} message">{MESSAGE}</div>-->
		<!-- EDP: page_message -->
		<div id="outer">
			<div id="middle">
				<div id="inner">
					<form class="box_form" action="<?php echo $this->url();?>" method="post">
						<fieldset style="top:160px;">
							<span><?php echo $this->captchaCode;?></span>
							<label><?php echo $this->translate('Code');?>:<input type="text" name="captcha[input]" id="captcha" value="" maxlength="255" tabindex="1" /></label>
							<label><?php echo $this->translate('Username');?>:<input type="text" name="uname" id="uname" value="" maxlength="255" tabindex="2" /></label>
							<div class="buttons" style="height:25px;float:right;">
								<div class="button_left"></div>
								<div class="button_center">
									<input type="submit" name="back" value="<?php echo $this->translate('Back');?>" tabindex="2" onclick="location.href='/';return false"/>
								</div>
								<div class="button_right"></div>

								<div class="button_left"></div>
								<div class="button_center">
									<input style="padding-left:3px;" type="submit" name="Submit" value="<?php echo $this->translate('Send request');?>" tabindex="3" />
								</div>
								<div class="button_right"></div>
							</div>
							<input type="hidden" name="captcha[id]" value="<?php echo $this->captchaId;?>" />
						</fieldset>
					</form>
				</div>
				<!--<div class="info" style="width:450px;position: relative;top:-50%;margin-left:auto;margin-right:auto;">
					<?php echo $this->translate('To avoid abuse, we ask you to write the combination of letters on the picture above into the field "Security code"');?>
				</div>-->
			</div>
		</div>
