#!/bin/sh
XGETTEXT_OPTIONS="--keyword=_ -keyword=N_ --default-domain=html_mail --no-location"

# Allows controlling language option
# (gettext v.0.10.40 = -C, gettext 0.11+ = -L php).
if [ $SM_LANG_PHP ] ; then
 XGETTEXT_OPTIONS="${XGETTEXT_OPTIONS} -L php";
else
 XGETTEXT_OPTIONS="${XGETTEXT_OPTIONS} -C";
fi

xgettext ${XGETTEXT_OPTIONS} *.php --output=html_mail.pot
