.include <../../../../Makefile.inc>

install:
	$(SYSTEM_MAKE_DIRS) $(SYSTEM_CONF)/bind
	cp ./named.conf ./working
	cp ./named.conf $(SYSTEM_CONF)/bind
	cp -R ./backup $(SYSTEM_CONF)/bind
	cp -R ./parts $(SYSTEM_CONF)/bind
	cp -R ./working $(SYSTEM_CONF)/bind
	cp ./named.rc $(ROOT_CONF)/named.rc
	chmod 700 $(ROOT_CONF)/named.rc
	chown root:wheel $(ROOT_CONF)/named.rc

uninstall:
	rm -rf $(SYSTEM_CONF)/bind

