#!/usr/bin/perl

# ispCP ω (OMEGA) a Virtual Hosting Control Panel
# Copyright (c) 2006-2009 by isp Control Panel
# http://isp-control.net
#
#
# License:
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of the MPL Mozilla Public License
#    as published by the Free Software Foundation; either version 1.1
#    of the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    MPL Mozilla Public License for more details.
#
#    You may have received a copy of the MPL Mozilla Public License
#    along with this program.
#
#    An on-line copy of the MPL Mozilla Public License can be found
#    http://www.mozilla.org/MPL/MPL-1.1.html
#
#
# The ispCP ω Home Page is at:
#
#    http://isp-control.net
#



my @needed = (strict, warnings, IO::Socket, DBI, DBD::mysql, Mail::Address, MIME::Entity,
MIME::Parser, Crypt::CBC, Crypt::Blowfish, MIME::Base64,
Term::ReadPassword, Net::LibIDN);

my ($mod, $mod_err, $mod_missing) = ('', '_off_', '');

for $mod (@needed) {
    print STDERR "Checking for '$mod'...\t";

    if (eval "require $mod") {
        $mod -> import();
        printf " Ok.\n";
    } else {
        print STDERR "CRITICAL ERROR: Module '$mod' WAS NOT FOUND !\n" ;

        $mod_err = '_on_';

        if ($mod_missing eq '') {
            $mod_missing .= $mod;
        } else {
            $mod_missing .= ", $mod";
        }
    }
}

if ($mod_err eq '_on_') {
    print STDERR "\nModules [$mod_missing] WERE NOT FOUND in your system...\n";
    print STDERR "\nPlease INSTALL them before using ispCP Omega !\n";
    exit 1;
} else {
    $| = 1;
}

return 0;

# hack for dh_perl

require IO::Socket;
require DBI;
require DBD::mysql;
require Mail::Address;
require MIME::Entity;
require MIME::Parser;
require Crypt::CBC;
require Crypt::Blowfish;
require MIME::Base64;
require Term::ReadPassword;
require Net::LibIDN;
