<?xml version="1.0" encoding="UTF-8" ?>
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
    <head>
		<?php
			$this->headTitle('i-MSCP - internet Multi Server Control Panel');
			$this->headMeta()->appendName('robots', 'nofollow, noindex')
				->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
				->appendHttpEquiv('X-UA-Compatible', 'IE=8')
				->appendHttpEquiv('Content-Style-Type', 'text/css')
				->appendHttpEquiv('Content-Script-Type', 'text/javascript');
			$this->headLink()->appendStylesheet('/themes/default/css/imscp.css')
                 ->headLink(array('rel' => 'favicon', 'href' => '/favicon.ico'),'PREPEND');
			$this->headScript()->appendFile('/themes/default/js/DD_belatedPNG_0.0.8a-min.js', 'text/javascript', array('conditional' => 'IE 6'))
				->appendScript("DD_belatedPNG.fix('*');" . PHP_EOL, 'text/javascript', array('conditional' => 'IE 6'));
			echo $this->headTitle(), PHP_EOL, $this->headMeta(), PHP_EOL, $this->headLink(), PHP_EOL, $this->headScript(), PHP_EOL;
		?>
    </head>
	<body>
		<div class="header">
			<div class="main_menu">
				<?php echo $this->navigation()->menu($this->mainMenu); ?>
			</div>
			<div class="logo"><img src="/themes/default/images/imscp_logo.png" alt="i-MSCP logo" /></div>
		</div>
		<div class="location">
			<div class="location-area icons-left">
	            <!--<h1 class="settings"></h1>-->

	            <?php echo $this->navigation()->breadcrumbs($this->mainMenu)->setMinDepth(0)->setLinkLast(true)->setSeparator('');?>
                    <!--{TR_MENU_SETTINGS}-->
	        </div>
			<ul class="location-menu">
				<li><a class="logout" href="../index.php?logout">Logout</a></li>
			</ul>
	        <ul class="path">
	            <?php //echo $this->navigation()->breadcrumbs($this->mainMenu)->setMinDepth(0)->setLinkLast(true)->setSeparator(" >> "); ?>
	        </ul>
		</div>
		<div class="left_menu">
			<!-- todo left menu -->
		</div>
		<?php echo $this->layout()->content; ?>
		<div class="footer">i-MSCP 1.0.0<br />build: 111210<br />Codename: Phoenix</div>
    </body>
</html>
