<?xml version="1.0" encoding="{THEME_CHARSET}" ?>
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=8" />
        <title>{TR_ADMIN_SETTINGS_PAGE_TITLE}</title>
        <meta name="robots" content="nofollow, noindex" />
        <link href="themes/default/css/imscp.css" rel="stylesheet" type="text/css" />
        <!--[if IE 6]>
        <script type="text/javascript" src="themes/default/js/DD_belatedPNG_0.0.8a-min.js"></script>
        <script type="text/javascript">
            DD_belatedPNG.fix('*');
        </script>
        <![endif]-->
	</script>
    </head>
	<body>
		<div class="header">
			<div class="main_menu">
				<?php echo $this->navigation()->menu(); ?>
			</div>
			<div class="logo"><img src="themes/default/images/imscp_logo.png" alt="i-MSCP logo" /></div>
		</div>
		<div class="location">
			<div class="location-area icons-left"><h1 class="settings">{TR_MENU_SETTINGS}</h1></div>
			<ul class="location-menu">
				<li><a class="logout" href="../index.php?logout">{TR_MENU_LOGOUT}</a></li>
			</ul>
			<?php echo $this->navigation()->breadcrumbs()->setMinDepth(0)->setLinkLast(true)->setSeparator(" >> "); ?>
		</div>
		<div class="left_menu">
			<!-- todo left menu -->
		</div>
		<?php echo $this->layout()->content; ?>
		<div class="footer">i-MSCP {VERSION}<br />build: {BUILDDATE}<br />Codename: {CODENAME}</div>
    </body>
</html>
