<?xml version="1.0" encoding="{THEME_CHARSET}" ?>
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=8" />
        <title>{TR_ADMIN_SETTINGS_PAGE_TITLE}</title>
        <meta name="robots" content="nofollow, noindex" />
        <link href="themes/default/css/imscp.css" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="themes/default/js/jquery.js"></script>
		<script type="text/javascript" src="themes/default/js/jquery.imscpTooltips.js"></script>
        <!--[if IE 6]>
        <script type="text/javascript" src="themes/default/js/DD_belatedPNG_0.0.8a-min.js"></script>
        <script type="text/javascript">
            DD_belatedPNG.fix('*');
        </script>
        <![endif]-->
        <script type="text/javascript">
		/*<![CDATA[*/
			$(document).ready(function() {
				jQuery('#tld_help').iMSCPtooltips({msg:"{TR_TLD_STRICT_VALIDATION_HELP}"});
				jQuery('#sld_help').iMSCPtooltips({msg:"{TR_SLD_STRICT_VALIDATION_HELP}"});
			});
		/*]]>*/
	</script>
    </head>
	<body>
		<div class="header">
			<!-- todo partial for main menu -->
			{MAIN_MENU}
			<div class="logo"><img src="themes/default/images/imscp_logo.png" alt="i-MSCP logo" /></div>
		</div>
		<div class="location">
			<div class="location-area icons-left"><h1 class="settings">{TR_MENU_SETTINGS}</h1></div>
			<ul class="location-menu">
				<li><a class="logout" href="../index.php?logout">{TR_MENU_LOGOUT}</a></li>
			</ul>
			<ul class="path">
				<li><a href="settings.php">{TR_SETTINGS}</a></li>
			</ul>
		</div>
		<div class="left_menu">
			<!-- todo partial for left menu -->
			{MENU}
		</div>
		<?php echo $this->layout()->content; ?>
		<div class="footer">i-MSCP {VERSION}<br />build: {BUILDDATE}<br />Codename: {CODENAME}</div>
    </body>
</html>
