<?xml version="1.0" encoding="UTF-8" ?>
<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
	<head>
		<title>i-MSCP - internet Multi Server Control Panel / Login</title>
		<meta name="robots" content="nofollow, noindex" />
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<meta http-equiv="Content-Style-Type" content="text/css" />
		<meta http-equiv="Content-Script-Type" content="text/javascript" />
		<link href="/themes/default/css/simple.css" rel="stylesheet" type="text/css" />
		<!--[if IE 6]>
			<script type="text/javascript" src="/themes/default/js/DD_belatedPNG_0.0.8a-min.js"></script>
			<script type="text/javascript">
				DD_belatedPNG.fix('*');
			</script>
		<![endif]-->
	</head>
	<body onload="document.login_frm.uname.focus()" class="body">
		<div class="header">
			<div id="logo">
				<div id="logoInner">
					<img src="/themes/default/images/imscp_logo32.png" alt="internet Multi Server Control Panel" />
					<span>internet Multi Server Control Panel</span>
				</div>
			</div>
			<div id="copyright">
				<div id="copyrightInner">
					<a href="{productLink}" target="blank" tabindex="8">
						&copy; Copyright 2010 i-MSCP Team<br/>All Rights Reserved
					</a>
				</div>
			</div>
		</div>
		<?php echo $this->layout()->content; ?>
	</body>
</html>
