<?xml version="1.0" encoding="UTF-8" ?>
<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=8" />
		<title><?php echo $this->pageTitle ?></title>
		<meta name="robots" content="nofollow, noindex" />
		<meta http-equiv="Content-Style-Type" content="text/css" />
		<link href="/themes/default/css/simple.css" rel="stylesheet" type="text/css" />
		<link href="/themes/default/css/exception.css" rel="stylesheet" type="text/css" />
	</head>
	<body>
		<div class="header">
			<div id="logo">
				<div id="logoInner">
					<img src="/themes/default/images/imscp_logo32.png" alt="<?php echo $this->productLongName ?>" />
					<span><?php echo $this->productLongName ?></span>
				</div>
			</div>
			<div id="copyright">
				<div id="copyrightInner">
					<a href="<?php echo $this->productLink ?>" target="blank" tabindex="8"><?php echo $this->productCopyright ?></a>
				</div>
			</div>
		</div>
		<?php echo $this->layout()->content; ?>
	</body>
</html>