#!/usr/bin/perl

# i-MSCP - internet Multi Server Control Panel
# Copyright (C) 2010-2015 by internet Multi Server Control Panel
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Script that mount i-MSCP filesystems on server reboot

use FindBin;
use lib "$FindBin::Bin/..", "$FindBin::Bin/../PerlLib", "$FindBin::Bin/../PerlVendor";
use iMSCP::Bootstrapper;
use iMSCP::Debug;
use iMSCP::Getopt;
use iMSCP::Mail;
use iMSCP::Mount 'mount';
use File::Basename;
use Tie::File;

newDebug('imscp-mountall-mngr.log');

iMSCP::Getopt->parseNoDefault(sprintf("Usage: perl %s [OPTION]...", basename($0)) . qq {

Mountall filesystems as configured by i-MSCP

OPTIONS:
 -v,    --verbose       Enable verbose mode.},
 'verbose|v' => sub { setVerbose(@_); }
);

iMSCP::Bootstrapper->getInstance()->boot({
	norequirements => 1, nokeys => 1, nodatabase => 1, nolock => 1, config_readonly => 1, mode => 'reboot'
});

eval {
	my $mountsConffilePath = "$main::imscpConfig{'CONF_DIR'}/mounts/mounts.conf";
	if(-f $mountsConffilePath) {
		tie my @mounts, 'Tie::File', $mountsConffilePath or die (sprintf'Could not tie %s: %s', $mountsConffilePath, $!);

		for my $mount(@mounts) {
			next if $mount =~ /^\s*#/;
			my %mountOptions;
			@mountOptions{ qw/ fs_spec fs_file fs_vfstype fs_mntops / } = split /\s+/, $mount;
			mount(\%mountOptions);
		}
	}
};

if($@) {
	my $error = $@;
	iMSCP::Mail->new()->errmsg($error);
	die($error);
};
