#!/usr/bin/perl

# i-MSCP - internet Multi Server Control Panel
# Copyright (C) 2010 by internet Multi Server Control Panel
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# @category		i-MSCP
# @copyright	2010 - 2012 by i-MSCP | http://i-mscp.net
# @author		Daniel Andreca <sci2tech@gmail.com>
# @version		SVN: $Id$
# @link			http://i-mscp.net i-MSCP Home Site
# @license		http://www.gnu.org/licenses/gpl-2.0.html GPL v2

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/..";
use lib "$FindBin::Bin/../PerlLib";

use iMSCP::Debug;
use iMSCP::Boot;
use iMSCP::Execute;
use iMSCP::Mail;
use iMSCP::Servers;
use iMSCP::Addons;
use Data::Dumper;

newDebug('imscp-del-tmp.log');

sub logs_start_up {

	umask(027);
	iMSCP::Boot->new()->init({nolock => 'yes'});

	0;
}

sub del_tmp{

	my $rs = 0;

	my @servers	= iMSCP::Servers->new()->get();
	unless(scalar @servers){
		error("Can not get servers list");
		return 1;
	}

	for(@servers){
		s/\.pm//;
		next if $_ eq 'noserver';
		my $file	= "Servers/$_.pm";
		my $class	= "Servers::$_";
		require $file;
		my $instance	= $class->factory();
		if($instance->can('del_tmp')){
			$rs |= $instance->del_tmp();
		}
	}

	my @addons	= iMSCP::Addons->new()->get();
	unless(scalar @addons){
		error("Can not get addons list");
		return 1;
	}

	for(@addons){
		s/\.pm//;
		next if $_ eq 'noserver';
		my $file	= "Addons/$_.pm";
		my $class	= "Addons::$_";
		require $file;
		my $instance	= $class->factory();
		if($instance->can('del_tmp')){
			$rs |= $instance->del_tmp();
		}
	}

	$rs;
}

my $rs = 0;

exit 1 if logs_start_up();

$rs |= del_tmp();

exit $rs;

