--
-- ISPCP ω (OMEGA) a Virtual Hosting Control Panel
-- Copyright (c) 2001-2006 by moleSoftware GmbH
-- Copyright (c) 2006-2007 by ispCP | http://isp-control.net
--
-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle `lang_English`
--

CREATE TABLE `lang_English` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `msgid` text,
  `msgstr` text,
  UNIQUE KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1115 ;

--
-- Daten für Tabelle `lang_English`
--

INSERT INTO `lang_English` (`id`, `msgid`, `msgstr`) VALUES
(1, 'ispcp_table', 'English'),
(2, 'ispcp_language', 'English'),
(3, 'ispcp_languageSetlocaleValue', 'en_GB'),
(4, 'encoding', 'UTF-8'),
(5, 'do not exist', ''),
(6, ' Has IP address that can not be managed from the destination reseller !<br>This user can not be moved!', ''),
(7, ' Has unlimited rights for a <b>', ''),
(8, 'is exceeding limits for a <b>', ''),
(9, ' you are logged now as', ''),
(10, '(Ex. domain-of-your-choice.com)', '(e.g. domain-of-your-choice.com)'),
(11, '(e.g. EUR)', ''),
(12, '(usually named backup_YYY_MM_DD.tar)', ''),
(13, '[New]', ''),
(14, '[Re]', ''),
(15, '* denotes mandatory field.', ''),
(16, '</b> Address !<br>Edit reseller aborted!', ''),
(17, '</b> amount, present on the system!', ''),
(18, '</b> in a destination reseller,<br>', ''),
(19, '</b> In a destination reseller,<br>', ''),
(20, '</b> records on the system!', ''),
(21, '</b> records, present on the system!', ''),
(22, '</b> Service !<br>', ''),
(23, '</b> Service can not be disabled !<br>There is <b>', ''),
(24, '</b> Service can not be limited !<br>specified number is smaller then <b>', '</b> Service can not be limited !<br>specified number is smaller than <b>'),
(25, '</b> Service can not be limited !<br>Specified number is smaller then <b>', '</b> Service can not be limited !<br>Specified number is smaller than <b>'),
(26, '</b> Service can not be limited !<br>You are exceeding reseller limits for the <b>', ''),
(27, '</b> Service can not be unlimited !<br>There is reseller limits for the <b>', ''),
(28, '</b> service!', ''),
(29, '<b>Routine maintenance!</b><br><br>ISPCP is not available for system changes<br><br>Pleas contact your hosting service provider for more information<br><br>We apologize for any inconvenience and thank you for understanding', '<b>Routine maintenance!</b><br><br>ISPCP is not available for system changes<br><br>Please contact your hosting service provider for more information<br><br>We apologize for any inconvenience and thank you for understanding'),
(30, '<b>Thank You for purchasing</b><br>You will receive an email with more details and information', ''),
(31, '<br>service in destination reseller!<br>', ''),
(32, '0', '0'),
(33, '1', '1'),
(34, '2', '2'),
(35, '3', '3'),
(36, '4', '4'),
(37, 'Access your files through the web interface', ''),
(38, 'Access your mail through the web interface', ''),
(39, 'Account name', ''),
(40, 'Action', ''),
(41, 'Activationlink valid (minutes)', ''),
(42, 'Active', ''),
(43, 'Add', ''),
(44, 'Add admin', ''),
(45, 'Add alias', ''),
(46, 'Add Cronjob', ''),
(47, 'Add domain alias', ''),
(48, 'Add existing user', ''),
(49, 'Add FTP user', ''),
(50, 'Add group', ''),
(51, 'Add hosting plan', ''),
(52, 'Add mail user', ''),
(53, 'Add mail users', ''),
(54, 'Add new button', ''),
(55, 'Add new IP', ''),
(56, 'Add new protected area', ''),
(57, 'Add new user hosting plan', ''),
(58, 'Add On A Domain', ''),
(59, 'Add other domains to this account', ''),
(60, 'Add plan', ''),
(61, 'Add reseller', ''),
(62, 'Add SQL database', ''),
(63, 'Add SQL user', ''),
(64, 'Add subdomain', ''),
(65, 'Add to the system', ''),
(66, 'Add user', ''),
(67, 'Add/Details', ''),
(68, 'Addition in progress', ''),
(69, 'Additional data', ''),
(70, 'Admin log', ''),
(71, 'Admin Log', ''),
(72, 'Admin users', ''),
(73, 'Administrator', ''),
(74, 'Administrators', ''),
(75, 'Adminitrators list is empty!', ''),
(76, 'Alais name', ''),
(77, 'Alias', ''),
(78, 'Alias forward', ''),
(79, 'Alias list is empty!', ''),
(80, 'Alias list is empty! You can not add FTP accounts there!', ''),
(81, 'Alias list is empty! You can not add mail accounts!', ''),
(82, 'Alias mail', ''),
(83, 'Alias mails', ''),
(84, 'Alias name', ''),
(85, 'Alias scheduled for addition!', ''),
(86, 'Alias scheduled for deletion!', ''),
(87, 'Alias scheduled for modification!', ''),
(88, 'Alias(es)<br><i>(-1 disabled, 0 unlimited)', ''),
(89, 'Aliases', ''),
(90, 'All', ''),
(91, 'All closed support tickets deleted successfully!', ''),
(92, 'All in', ''),
(93, 'All open support tickets deleted successfully!', ''),
(94, 'All out', ''),
(95, 'All resellers', ''),
(96, 'All traffic', ''),
(97, 'All users & resellers', ''),
(98, 'All users', ''),
(99, 'Already in:', ''),
(100, 'Apache logfiles', ''),
(101, 'Apache logs', ''),
(102, 'Apply changes', ''),
(103, 'Are you sure you want to change the status of domain account?', ''),
(104, 'Are you sure you want to delete', ''),
(105, 'Are you sure you want to delete this account?', ''),
(106, 'Are you sure you want to delete this order?', ''),
(107, 'Area name', ''),
(108, 'Assign', ''),
(109, 'Auto email template data updated!', ''),
(110, 'Auto respond', ''),
(111, 'Automatic Updates', ''),
(112, 'Available for purchasing', ''),
(113, 'Available IPs', ''),
(114, 'Available ISPCP updates', ''),
(115, 'Awstats', ''),
(116, 'AwStats', ''),
(117, 'Back', ''),
(118, 'Backup / Restore', ''),
(119, 'Backup', ''),
(120, 'Backup and restore', ''),
(121, 'Backup and Restore', ''),
(122, 'Backup and restore settings', ''),
(123, 'Backup archive scheduled for restoring!', ''),
(124, 'Behind the name', ''),
(125, 'Billing Settings', ''),
(126, 'Blocktime (minutes)', ''),
(127, 'Blue', ''),
(128, 'Bruteforce detection', ''),
(129, 'Button link', ''),
(130, 'Button name', ''),
(131, 'Button target', ''),
(132, 'Can not connect as MySQL administrator!', ''),
(133, 'Can Not Connect As MySQL Administrator!', ''),
(134, 'Can not open directory !<br>Please contact your administrator !', ''),
(135, 'Can not open file! Please contact your administrator !', ''),
(136, 'Can not read ispcp language file!', ''),
(137, 'Cancel', ''),
(138, 'Cancel order', ''),
(139, 'Cannot connect as MySQL administrator!', ''),
(140, 'Catch all', ''),
(141, 'Catch all account', ''),
(142, 'Catch all account scheduled for creation!', ''),
(143, 'Catch all account scheduled for deletion!', ''),
(144, 'Catch all mail account can not be created!', ''),
(145, 'CGI / Perl', ''),
(146, 'CGI support', ''),
(147, 'CGI Support: disabled', ''),
(148, 'CGI Support: enabled', ''),
(149, 'Change', ''),
(150, 'Change password', ''),
(151, 'Change pers. data', ''),
(152, 'Change personal data', ''),
(153, 'Change SQL user password', ''),
(154, 'Change user interface', ''),
(155, 'Check Out', ''),
(156, 'Choose', ''),
(157, 'Choose default language', ''),
(158, 'Choose default layout', ''),
(159, 'Choose dir', ''),
(160, 'Choose hosting plan', ''),
(161, 'Circular', ''),
(162, 'City', ''),
(163, 'Clear log', ''),
(164, 'Click Restore button and the system will<br>restore last daily backup', ''),
(165, 'Close ticket', ''),
(166, 'Closed tickets', ''),
(167, 'Command to run:', ''),
(168, 'Company', ''),
(169, 'Continue', ''),
(170, 'Core data', ''),
(171, 'Costs', ''),
(172, 'Country', ''),
(173, 'CPU bogomips', ''),
(174, 'CPU cache', ''),
(175, 'CPU MHz', ''),
(176, 'CPU model', ''),
(177, 'CPU system Info', ''),
(178, 'Create catch all', ''),
(179, 'Create catch all mail account', ''),
(180, 'Created by', ''),
(181, 'Creation date', ''),
(182, 'Cronjob', ''),
(183, 'Cronjob Manager', ''),
(184, 'Cronjobs', ''),
(185, 'Currency', ''),
(186, 'Current password', ''),
(187, 'Custom Apache Logs', ''),
(188, 'Custom error page was updated!', ''),
(189, 'Custom error pages', ''),
(190, 'Custom Error Pages', ''),
(191, 'Custom menu data updated successful!', ''),
(192, 'Custom menu deleted successful!', ''),
(193, 'Custom menus', ''),
(194, 'Customer data', ''),
(195, 'Customer ID', ''),
(196, 'Customer order was removed successful!', ''),
(197, 'Customize error pages for your domain', ''),
(198, 'D', 'Details'),
(199, 'Daily backup', ''),
(200, 'Database list is empty!', ''),
(201, 'Database name', ''),
(202, 'Database user list is empty!', ''),
(203, 'Database users', ''),
(204, 'Date', ''),
(205, 'Day', ''),
(206, 'Day:', ''),
(207, 'days', ''),
(208, 'Day(s):', ''),
(209, 'default', ''),
(210, 'Default', ''),
(211, 'Default language', ''),
(212, 'Default language changed!', ''),
(213, 'delete', ''),
(214, 'Delete', ''),
(215, 'Delete all', ''),
(216, 'Delete CatchAll', ''),
(217, 'Delete from log:', ''),
(218, 'Delete order', ''),
(219, 'Deletion in progress', ''),
(220, 'Description', ''),
(221, 'Details', ''),
(222, 'Direction download today backup', ''),
(223, 'Directories', ''),
(224, 'Directory listing', ''),
(225, 'Directory mount point', ''),
(226, 'Directory tree', ''),
(227, 'Directory tree<br>mount point', ''),
(228, 'Disable', ''),
(229, 'disabled', ''),
(230, 'Disabled', ''),
(231, 'Disk [MB]<br><i>(0 unlimited)', ''),
(232, 'Disk', ''),
(233, 'Disk in MB', ''),
(234, 'Disk limit [Mb]<br><i>(0 unlimited)</i>', ''),
(235, 'Disk limit [MB]<br><i>(0 unlimited)</i>', ''),
(236, 'Disk usage', ''),
(237, 'Disk<br>usage', ''),
(238, 'Domain', ''),
(239, 'Domain account', ''),
(240, 'Domain alias', ''),
(241, 'Domain alias added for termination!', ''),
(242, 'Domain alias added!', ''),
(243, 'Domain alias errors', ''),
(244, 'Domain alias limit expired!', ''),
(245, 'Domain alias modified!', ''),
(246, 'Domain alias not added for termination!', ''),
(247, 'Domain alias not added!', ''),
(248, 'Domain alias not modified!', ''),
(249, 'Domain alias you are trying to remove has email accounts !<br>First remove them!', ''),
(250, 'Domain alias you are trying to remove has FTP accounts!<br>First remove them!', ''),
(251, 'Domain aliases', ''),
(252, 'Domain aliasses', ''),
(253, 'Domain details', ''),
(254, 'Domain errors', ''),
(255, 'Domain Features', ''),
(256, 'Domain IP', ''),
(257, 'Domain mail', ''),
(258, 'Domain mails', ''),
(259, 'Domain name', ''),
(260, 'Domain properties', ''),
(261, 'Domain properties updated successfully!', ''),
(262, 'Domain statistics', ''),
(263, 'Domain with that name already exists on the system!', ''),
(264, 'Domain with this name already exist', ''),
(265, 'Domain you are trying to remove has domain alias!<br> first remove them !', ''),
(266, 'Domain you are trying to remove has email accounts !<br> first remove them !', ''),
(267, 'Domain you are trying to remove has FTP accounts !<br> first remove them !', ''),
(268, 'Domain you are trying to remove has subdomains accounts !<br> first remove them !', ''),
(269, 'Domains', ''),
(270, 'Domains per page', ''),
(271, 'Done', ''),
(272, 'DOWN', ''),
(273, 'Download the only one file in this directory', ''),
(274, 'E-mail', ''),
(275, 'Edit', ''),
(276, 'Edit admin', ''),
(277, 'Edit button', ''),
(278, 'Edit Cronjob', ''),
(279, 'Edit Domain', ''),
(280, 'Edit domain alias', ''),
(281, 'Edit email account', ''),
(282, 'Edit error page', ''),
(283, 'Edit FTP user', ''),
(284, 'Edit hosting plan', ''),
(285, 'Edit mail auto responder', ''),
(286, 'Edit properties', ''),
(287, 'Edit reseller', ''),
(288, 'Edit reseller aborted!', ''),
(289, 'Edit user', ''),
(290, 'Email', ''),
(291, 'Email account not founded!', ''),
(292, 'Email Accounts', ''),
(293, 'Email and FTP accounts', ''),
(294, 'Email forward', ''),
(295, 'Email marketing', ''),
(296, 'Email setup', ''),
(297, 'Email Updated', ''),
(298, 'Email Updated!', ''),
(299, 'Empty data or wrong field!', ''),
(300, 'Empty list', ''),
(301, 'Empty List', ''),
(302, 'Enable', ''),
(303, 'Enable mail auto responder', ''),
(304, 'enabled', ''),
(305, 'Enabled', ''),
(306, 'Enduser level', ''),
(307, 'Enter Address', ''),
(308, 'Entered passwords differ from the another!', ''),
(309, 'Entered passwords differ!', ''),
(310, 'Entered passwords does not match!', ''),
(311, 'Error', ''),
(312, 'Error 401 (unauthorized)', ''),
(313, 'Error 403 (forbidden)', ''),
(314, 'Error 404 (not found)', ''),
(315, 'Error 500 (internal server error)', ''),
(316, 'Error pages', ''),
(317, 'Error we have domain that use this IP!', ''),
(318, 'Error we have reseller that use this IP!', ''),
(319, 'ERROR: Password not send', ''),
(320, 'ERROR: Security code was not correct!', ''),
(321, 'ERROR: Unknown user', ''),
(322, 'everything', ''),
(323, 'Execute', ''),
(324, 'Execute query', ''),
(325, 'Execute SQL query', ''),
(326, 'Existing SQL users', ''),
(327, 'Export', ''),
(328, 'Extras', ''),
(329, 'Fax', ''),
(330, 'Feature', ''),
(331, 'Filemanager', ''),
(332, 'Filesystem system Info', ''),
(333, 'First name', ''),
(334, 'Footer', ''),
(335, 'Forward', ''),
(336, 'Forward list is empty!', ''),
(337, 'Forward mail', ''),
(338, 'Forward to', ''),
(339, 'Forward to URL', ''),
(340, 'Free', ''),
(341, 'free of charge', ''),
(342, 'From', ''),
(343, 'From reseller', ''),
(344, 'Fronpage extensions', ''),
(345, 'FTP', ''),
(346, 'FTP account', ''),
(347, 'FTP account added!', ''),
(348, 'FTP account already exists!', ''),
(349, 'FTP account data updated!', ''),
(350, 'FTP account deleted successfully!', ''),
(351, 'FTP account limit<br><i>(0 unlimited)</i>', ''),
(352, 'FTP account(s)<br><i>(0 unlimited)', ''),
(353, 'FTP accounts', ''),
(354, 'FTP Accounts', ''),
(355, 'FTP accounts limit expired!', ''),
(356, 'FTP list is empty!', ''),
(357, 'FTP traffic', ''),
(358, 'FTP users', ''),
(359, 'FTP<br>traffic', ''),
(360, 'FTPs total', ''),
(361, 'General information', ''),
(362, 'General settings', ''),
(363, 'Get it at', ''),
(364, 'Go back', ''),
(365, 'Green', ''),
(366, 'Group - Usermanagement', ''),
(367, 'Group', ''),
(368, 'Group already exist !', ''),
(369, 'Group auth', ''),
(370, 'Group members', ''),
(371, 'Group name', ''),
(372, 'Groups', ''),
(373, 'Has unlimited rights for a <b>', ''),
(374, 'Havent you got more than one name?', 'Haven''t you got more than one name?'),
(375, 'HDD', ''),
(376, 'Header', ''),
(377, 'hide aliases', ''),
(378, 'High', ''),
(379, 'Host', ''),
(380, 'Hosting details', ''),
(381, 'Hosting plan', ''),
(382, 'Hosting plan added!', ''),
(383, 'Hosting plan deleted!', ''),
(384, 'Hosting plan properties', ''),
(385, 'Hosting plan updated!', ''),
(386, 'Hosting plan with entered name already exists!', ''),
(387, 'Hosting plans', ''),
(388, 'Hosting plans available for update', ''),
(389, 'Hosting plans not found!', ''),
(390, 'Hour', ''),
(391, 'hours', ''),
(392, 'Hour(s):', ''),
(393, 'ID', ''),
(394, 'If you want to limit the reseller, fist you must limit its users !<br>', ''),
(395, '(To avoid abuse, we ask you to write the combination of letters on the above picture into the field "Security code")', ''),
(396, 'Implementation URL', ''),
(397, 'In front the name', ''),
(398, 'In this mode only administrators can login', ''),
(399, 'Incorrect alias range or syntax!', 'Incorrect <i>domain alias</i> range or syntax!'),
(400, 'Incorrect city syntax!', 'Incorrect <i>city</i> syntax!'),
(401, 'Incorrect company range or syntax!', 'Incorrect <i>company</i> range or syntax!'),
(402, 'Incorrect country syntax!', 'Incorrect <i>country</i> syntax!'),
(403, 'Incorrect customer ID syntax!', 'Incorrect <i>customer ID</i> syntax!'),
(404, 'Incorrect data input!', ''),
(405, 'Incorrect disk range or syntax!', 'Incorrect <i>disk range</i> or syntax!'),
(406, 'Incorrect domain name syntax', 'Incorrect <i>domain name</i> syntax'),
(407, 'Incorrect email range or syntax!', 'Incorrect <i>e-mail</i> range or syntax!'),
(408, 'Incorrect fax range or syntax!', 'Incorrect <i>fax</i> range or syntax!'),
(409, 'Incorrect first name range or syntax!', 'Incorrect <i>first name</i> range or syntax!'),
(410, 'Incorrect forward syntax', 'Incorrect <i>forward</i> syntax!'),
(411, 'Incorrect FTP account range or syntax!', 'Incorrect <i>FTP account</i> range or syntax!'),
(412, 'Incorrect mail account range or syntax!', 'Incorrect <i>e-mail account</i> range or syntax!'),
(413, 'Incorrect max alias count or syntax!', 'Incorrect <i>max alias</i> count or syntax!'),
(414, 'Incorrect max disk amount or syntax!', 'Incorrect <i>max disk</i> amount or syntax!'),
(415, 'Incorrect max domain count or syntax!', 'Incorrect <i>max domain</i> count or syntax!'),
(416, 'Incorrect max FTP count or syntax!', 'Incorrect <i>max FTP</i> count or syntax!'),
(417, 'Incorrect max mail count or syntax!', 'Incorrect <i>max e-mail</i> count or syntax!'),
(418, 'Incorrect max SQL databases count or syntax!', 'Incorrect <i>max mySQL databases</i> count or syntax!'),
(419, 'Incorrect max SQL users count or syntax!', 'Incorrect <i>max mySQL users</i> count or syntax!'),
(420, 'Incorrect max subdomain count or syntax!', 'Incorrect <i>max subdomain</i> count or syntax!'),
(421, 'Incorrect max traffic amount or syntax!', 'Incorrect <i>max traffic</i> amount or syntax!'),
(422, 'Incorrect mount point syntax', 'Incorrect <i>mount point</i> syntax!'),
(423, 'Incorrect password range or syntax!', ''),
(424, 'Incorrect phone range or syntax!', ''),
(425, 'Incorrect post code range or syntax!', ''),
(426, 'Incorrect price range or syntax!', ''),
(427, 'Incorrect second name range or syntax!', ''),
(428, 'Incorrect setup fee range or syntax!', ''),
(429, 'Incorrect SQL database range or syntax!', ''),
(430, 'Incorrect SQL user range or syntax!', ''),
(431, 'Incorrect street 1 syntax!', ''),
(432, 'Incorrect street 2 syntax!', ''),
(433, 'Incorrect subdomain range or syntax!', ''),
(434, 'Incorrect template description range or syntax!', ''),
(435, 'Incorrect template name range or syntax!', ''),
(436, 'Incorrect traffic range or syntax!', ''),
(437, 'Incorrect username range or syntax!', ''),
(438, 'Install', ''),
(439, 'Install new language', ''),
(440, 'Installed languages', ''),
(441, 'Installed layouts', ''),
(442, 'Invalid Mail Localpart Format used!', ''),
(443, 'IP', ''),
(444, 'IP was deleted!', ''),
(445, 'JSP', ''),
(446, 'Kernel', ''),
(447, 'Kill session', ''),
(448, 'Label', ''),
(449, 'Language', ''),
(450, 'Language file', ''),
(451, 'Language was removed!', ''),
(452, 'Last access', ''),
(453, 'Last name', ''),
(454, 'Last reply', ''),
(455, 'Layout', ''),
(456, 'Layout name', ''),
(457, 'Layout settings', ''),
(458, 'Level', ''),
(459, 'Limit', ''),
(460, 'Load', ''),
(461, 'Log is empty!', ''),
(462, 'Login', ''),
(463, 'Login with your FTP account', ''),
(464, 'Logo file', ''),
(465, 'Logo upload', ''),
(466, 'Logout', ''),
(467, 'Lost password', ''),
(468, 'Lostpassword', ''),
(469, 'Lostpw email', ''),
(470, 'Lostpw email setup', ''),
(471, 'Lostpw link', ''),
(472, 'Activation E-Mail', ''),
(473, 'Password E-Mail', ''),
(474, 'Low', ''),
(475, 'minutes', ''),
(476, 'Mail', 'e-mail'),
(477, 'Mail account', ''),
(478, 'Mail account already exists!', ''),
(479, 'Mail account errors', ''),
(480, 'Mail account limit<br><i>(0 unlimited)</i>', ''),
(481, 'Mail account scheduled for addition!', ''),
(482, 'Mail account scheduled for modification!', ''),
(483, 'Mail account scheduler for modification!', ''),
(484, 'Mail account(s)<br><i>(0 unlimited)', ''),
(485, 'Mail accounts', ''),
(486, 'Mail accounts limit expired!', ''),
(487, 'Mail accounts list', ''),
(488, 'Mail accounts list is empty!', ''),
(489, 'Mail forward list empty!', ''),
(490, 'Mail forward list error!', ''),
(491, 'Mail in', ''),
(492, 'Mail out', ''),
(493, 'Mail users', ''),
(494, 'Mail were updated successfully!', ''),
(495, 'Mailformat of an adress in your forward list is incorrect!', ''),
(496, 'Mails total', ''),
(497, 'Main domain', ''),
(498, 'Manage alias', ''),
(499, 'Manage custom menus', ''),
(500, 'Manage domain alias', ''),
(501, 'Manage domains', ''),
(502, 'Manage hosting plans', ''),
(503, 'Manage IPs', ''),
(504, 'Manage orders', ''),
(505, 'Manage Orders', ''),
(506, 'Manage protected areas, users and groups', ''),
(507, 'Manage SQL', ''),
(508, 'Manage user', ''),
(509, 'Manage user sessions', ''),
(510, 'Manage users', ''),
(511, 'Manage users and groups', ''),
(512, 'Mark', ''),
(513, 'Max aliases count', ''),
(514, 'Max aliases count<br><i>(0 unlimited)</i>', ''),
(515, 'Max aliases<br><i>(-1 disabled, 0 unlimited)', ''),
(516, 'Max disk amount [MB]', ''),
(517, 'Max disk amount [MB]<br><i>(0 unlimited)</i>', ''),
(518, 'Max domain count', ''),
(519, 'Max Domain count', ''),
(520, 'Max domain count<br><i>(0 unlimited)</i>', ''),
(521, 'Max FTP users count', ''),
(522, 'Max FTP users count<br><i>(0 unlimited)</i>', ''),
(523, 'Max mail users count', ''),
(524, 'Max mail users count<br><i>(0 unlimited)</i>', ''),
(525, 'Max SQL databases count', ''),
(526, 'Max SQL databases count<br><i>(-1 disabled, 0 unlimited)</i>', ''),
(527, 'Max SQL users count', ''),
(528, 'Max SQL users count<br><i>(-1 disabled, 0 unlimited)</i>', ''),
(529, 'Max subdomain count', ''),
(530, 'Max subdomain count<br><i>(0 unlimited)', ''),
(531, 'Max subdomains<br><i>(-1 disabled, 0 unlimited)', ''),
(532, 'Max traffic [MB]', ''),
(533, 'Max traffic amount [MB]', ''),
(534, 'Max traffic amount [MB]<br><i>(0 unlimited)</i>', ''),
(535, 'Medium', ''),
(536, 'Memory system info', ''),
(537, 'Menu button', ''),
(538, 'Message', ''),
(539, 'Message subject', ''),
(540, 'Message template', ''),
(541, 'Message template info', ''),
(542, 'Message was send!', ''),
(543, 'Message was sent.', ''),
(544, 'Messages', ''),
(545, 'Messages translated', ''),
(546, 'Minute(s):', ''),
(547, 'Missing or incorrect data input!', ''),
(548, 'Missing or wrong data!', ''),
(549, 'Modification in progress', ''),
(550, 'Modify', ''),
(551, 'Month', ''),
(552, 'Month:', ''),
(553, 'Months(s):', ''),
(554, 'Mount', ''),
(555, 'Mount point', ''),
(556, 'Move', ''),
(557, 'Moving aborted!', ''),
(558, 'Multilanguage', ''),
(559, 'MySQL support', ''),
(560, 'N/A', ''),
(561, 'Name', ''),
(562, 'new', ''),
(563, 'New', ''),
(564, 'New IP was added!', ''),
(565, 'New language installed!', ''),
(566, 'New order', ''),
(567, 'New ticket', ''),
(568, 'New ISPCP update is now available', ''),
(569, 'Next step', ''),
(570, 'no', ''),
(571, 'No', ''),
(572, 'No available hosting packages', ''),
(573, 'No domain alias system errors', ''),
(574, 'No domain system errors', ''),
(575, 'No email account system errors', ''),
(576, 'No new messages', ''),
(577, 'No new ISPCP updates available', ''),
(578, 'No subdomain system errors', ''),
(579, 'No.', ''),
(580, 'None', ''),
(581, 'Normal mail', ''),
(582, 'Normal users', ''),
(583, 'Not found reseller(s) in your system!', ''),
(584, 'Not found user records matching the search criteria!', ''),
(585, 'Not in:', ''),
(586, 'Number', ''),
(587, 'Number of login attempts', ''),
(588, 'of', ''),
(589, 'ok', ''),
(590, 'Ok', ''),
(591, 'OK', ''),
(592, 'older than 1 month', ''),
(593, 'older than 12 months', ''),
(594, 'older than 2 weeks', ''),
(595, 'older than 3 months', ''),
(596, 'older than 6 months', ''),
(597, 'Open ticket', ''),
(598, 'Open tickets', ''),
(599, 'Options', ''),
(600, 'Order', ''),
(601, 'Order data updated successfully!', ''),
(602, 'Order date', ''),
(603, 'Order details', ''),
(604, 'Order email setup', ''),
(605, 'Order settings', ''),
(606, 'Other in', ''),
(607, 'Other out', ''),
(608, 'Other settings', ''),
(609, 'Overview', ''),
(610, 'Owner', ''),
(611, 'Package Features', ''),
(612, 'Package Price', ''),
(613, 'Parent Directory', ''),
(614, 'Partition', ''),
(615, 'Password (repeat)', ''),
(616, 'Password', ''),
(617, 'Password data', ''),
(618, 'Password data includes not permitted signs!', ''),
(619, 'Password data is missing!', ''),
(620, 'Password generate', ''),
(621, 'Password not match!', ''),
(622, 'Password repeat', ''),
(623, 'Password send', ''),
(624, 'Password(repeat)', ''),
(625, 'Passwords does not match!', ''),
(626, 'Path', ''),
(627, 'Payment period', ''),
(628, 'Percent', ''),
(629, 'Performance', ''),
(630, 'Permission deny!', ''),
(631, 'Personal data', ''),
(632, 'Personal Data', ''),
(633, 'Personal data updated successfully!', ''),
(634, 'Personalize template', ''),
(635, 'Phone', ''),
(636, 'PHP', ''),
(637, 'PHP support', ''),
(638, 'PHP Support: disabled', ''),
(639, 'PHP Support: enabled', ''),
(640, 'PhpMyAdmin', ''),
(641, 'Please choose user or group', ''),
(642, 'Please delete first CatchAll account for this email!', ''),
(643, 'Please enter area name', ''),
(644, 'Please enter area path', ''),
(645, 'Please enter FTP account username!', ''),
(646, 'Please enter mail account username!', ''),
(647, 'Please enter SQL query!', ''),
(648, 'Please fill out all needed fields!', ''),
(649, 'Please fill up all data fields!', ''),
(650, 'Please fill up both data fields for password!', ''),
(651, 'Please fill up both data fields!', ''),
(652, 'Please select some user(s)!', ''),
(653, 'Please specify a message content!', ''),
(654, 'Please specify a message subject!', ''),
(655, 'Please specify a sender email!', ''),
(656, 'Please specify a sender name!', ''),
(657, 'Please specify a subject!', ''),
(658, 'Please specify alias!', ''),
(659, 'Please specify domain!', ''),
(660, 'Please specify email address!', ''),
(661, 'Please specify message subject!', ''),
(662, 'Please specify message!', ''),
(663, 'Please specify other FTP account dir!', ''),
(664, 'Please specify sender name!', ''),
(665, 'Please specify some email address!', ''),
(666, 'Please specify some message!', ''),
(667, 'Please specify some sender name!', ''),
(668, 'Please specify subdomain name!', ''),
(669, 'Please type database name!', ''),
(670, 'Please type user name!', ''),
(671, 'Please type user password!', ''),
(672, 'Please type your mail autorespond message!', ''),
(673, 'Please type your message!', ''),
(674, 'Please wait for update', ''),
(675, 'POP/IMAP', ''),
(676, 'Pop/IMAP in', ''),
(677, 'Pop/IMAP out', ''),
(678, 'POP3/IMAP traffic', ''),
(679, 'POP3/IMAP<br>traffic', ''),
(680, 'Preview', ''),
(681, 'Price', ''),
(682, 'Priority', ''),
(683, 'Protect it', ''),
(684, 'Protect this area', ''),
(685, 'Protected area created successfully!', ''),
(686, 'Protected area deleted successfully!', ''),
(687, 'Protected area status should be OK if you wannt to delete it!', 'Protected area status should be OK if you want to delete it!'),
(688, 'Protected area status should be OK if you wannt to edit it!', 'Protected area status should be OK if you want to edit it!'),
(689, 'Protected area updated successfully!', ''),
(690, 'Protected area was deleted successful!', ''),
(691, 'Protected areas', ''),
(692, 'Protected Areas', ''),
(693, 'Protocol', ''),
(694, 'Purchase', ''),
(695, 'Purchasing', ''),
(696, 'Query result', ''),
(697, 'Query status', ''),
(698, 'RAM', ''),
(699, 'Real domain', ''),
(700, 'Red', ''),
(701, 'Remove', ''),
(702, 'Request password', ''),
(703, 'Reseller', ''),
(704, 'Reseller added', ''),
(705, 'Reseller and enduser level', ''),
(706, 'Reseller assignment', ''),
(707, 'Reseller IP list is empty!', ''),
(708, 'Reseller IPs', ''),
(709, 'Reseller level', ''),
(710, 'Reseller list is empty!', ''),
(711, 'Reseller name', ''),
(712, 'Reseller or user list is empty!', ''),
(713, 'Reseller statistics', ''),
(714, 'Reseller statistics table', ''),
(715, 'Reseller users', ''),
(716, 'Reseller users table', ''),
(717, 'Resellers', ''),
(718, 'Resellers list is empty!', ''),
(719, 'Reset', ''),
(720, 'Restore', ''),
(721, 'Restore backup', ''),
(722, 'Retry', ''),
(723, 'Return to previous menu', ''),
(724, 'Routine maintenance!</b><br><br>ISPCP is not available for system changes<br><br>Pleas contact your hosting service provider for more information<br><br>We apologize for any inconvenience and thank you for understanding', ''),
(725, 'seconds', ''),
(726, 'S', 'Status'),
(727, 'Save', ''),
(728, 'Save changes', ''),
(729, 'Search', ''),
(730, 'Security code', ''),
(731, 'Send message', ''),
(732, 'Send message reply', ''),
(733, 'Send message to', ''),
(734, 'Send new login data', ''),
(735, 'Send reply', ''),
(736, 'Senders email', ''),
(737, 'Senders name', ''),
(738, 'Server day statistics', ''),
(739, 'Server error - please choose error page', ''),
(740, 'Server statistics', ''),
(741, 'Server status', ''),
(742, 'Server traffic', ''),
(743, 'Server traffic settings', ''),
(744, 'Server traffic settings updated successfully!', ''),
(745, 'Service', ''),
(746, 'Service in destination reseller!<br>', ''),
(747, 'Servicemode', ''),
(748, 'Set server traffic settings', ''),
(749, 'Settings', ''),
(750, 'Settings saved !', ''),
(751, 'Setup fee', ''),
(752, 'Setup Fee', ''),
(753, 'Show', ''),
(754, 'Show in', ''),
(755, 'Size', ''),
(756, 'SMTP', ''),
(757, 'SMTP traffic', ''),
(758, 'SMTP<br>traffic', ''),
(759, 'Source and destination reseller are the same!', ''),
(760, 'Specified database name already exists!', ''),
(761, 'Specified SQL username name already exists!', ''),
(762, 'SQL accounts limit expired!', ''),
(763, 'SQL database', ''),
(764, 'SQL Database', ''),
(765, 'SQL database created successfully!', ''),
(766, 'SQL database was removed successfully!', ''),
(767, 'SQL database(s)<br><i>(-1 disabled, 0 unlimited)', ''),
(768, 'SQL databases', ''),
(769, 'SQL databases limit<br><i>(-1 disabled, 0 unlimited)</i>', ''),
(770, 'SQL databases Limit<br><i>(-1 disabled, 0 unlimited)</i>', ''),
(771, 'SQL query', ''),
(772, 'SQL query has error', ''),
(773, 'SQL query is ok', ''),
(774, 'SQL support', ''),
(775, 'SQL user', ''),
(776, 'SQL User', ''),
(777, 'SQL user name', ''),
(778, 'SQL user password was successfully changed!', ''),
(779, 'SQL user successfully added!', ''),
(780, 'SQL user was removed successfully!', ''),
(781, 'SQL user(s)<br><i>(-1 disabled, 0 unlimited)', ''),
(782, 'SQL users', ''),
(783, 'SQL users limit<br><i>(-1 disabled, 0 unlimited)</i>', ''),
(784, 'SQL-user limit expired!', ''),
(785, 'SQL<br>database', ''),
(786, 'SQL<br>user', ''),
(787, 'SSI', ''),
(788, 'Statistics', ''),
(789, 'Stats', ''),
(790, 'Status', ''),
(791, 'Street 1', ''),
(792, 'Street 2', ''),
(793, 'Subdomain', ''),
(794, 'Subdomain already exists!', ''),
(795, 'Subdomain data', ''),
(796, 'Subdomain errors', ''),
(797, 'Subdomain forward', ''),
(798, 'Subdomain limit expired!', ''),
(799, 'Subdomain list is empty!', ''),
(800, 'Subdomain list is empty! You can not add FTP accounts there!', ''),
(801, 'Subdomain list is empty! You can not add mail accounts!', ''),
(802, 'Subdomain mail', ''),
(803, 'Subdomain mails', ''),
(804, 'Subdomain mount point already exists!', ''),
(805, 'Subdomain name', ''),
(806, 'Subdomain scheduled for addition!', ''),
(807, 'Subdomain scheduled for deletion!', ''),
(808, 'Subdomain you are trying to remove has email accounts !<br>First remove them!', ''),
(809, 'Subdomain you are trying to remove has FTP accounts !<br>First remove them !', ''),
(810, 'Subdomain(s)<br><i>(-1 disabled, 0 unlimited)', ''),
(811, 'Subdomains', ''),
(812, 'Subject', ''),
(813, 'Submit changes', ''),
(814, 'Sum', ''),
(815, 'support question(s)', ''),
(816, 'Support question(s)', ''),
(817, 'support questions', ''),
(818, 'Support system', ''),
(819, 'Support ticket deleted successfully!', ''),
(820, 'Support tickets', ''),
(821, 'Supportsystem', ''),
(822, 'suspended', ''),
(823, 'Suspended', ''),
(824, 'Swap', ''),
(825, 'Switch to backup directory', ''),
(826, 'System error - custom error page was NOT updated!', ''),
(827, 'System error with Doman ID', ''),
(828, 'System info', ''),
(829, 'System is currently in servicemode! At time only administrators can login.', ''),
(830, 'System messages', ''),
(831, 'System tools', ''),
(832, 'Template name', ''),
(833, 'The current password is wrong!', ''),
(834, 'The password was requested', ''),
(835, 'Theme color', ''),
(836, 'Then the value you are trying to enter now !<br>', ''),
(837, 'Then the value you are trying to enter now!<br>', ''),
(838, 'There are alias with same mount point', ''),
(839, 'There are no available hosting plans for update', ''),
(840, 'There are no available updates', ''),
(841, 'This IP already exist!', ''),
(842, 'This reseller has already dispatched more <b>', ''),
(843, 'This reseller has domains assigned To <b>', ''),
(844, 'This reseller has more <b>', ''),
(845, 'This reseller has no domains yet.', ''),
(846, 'This reseller has no domains.', ''),
(847, 'This reseller has user(s) with unlimited rights for <b>', ''),
(848, 'This user has domain record !<br>First remove the domain from the system!', ''),
(849, 'This user have domain !<br>To delete user  - first delete domain!', ''),
(850, 'This user name already exist!', ''),
(851, 'Ticket not found!', ''),
(852, 'Ticket was closed!', ''),
(853, 'Ticket(s) are closed!', ''),
(854, 'Ticket(s) are deleted!', ''),
(855, 'Time between logins', ''),
(856, 'Time between logins (seconds)', ''),
(857, 'To Admin', ''),
(858, 'To domain alias', ''),
(859, 'To main domain', ''),
(860, 'To reseller', ''),
(861, 'To subdomain', ''),
(862, 'Too long database name!', ''),
(863, 'Too long user password!', ''),
(864, 'Too user long password!', ''),
(865, 'Total', ''),
(866, 'Traffic [MB]<br><i>(0 unlimited)', ''),
(867, 'Traffic', ''),
(868, 'Traffic accounting for the selected month is missing!', ''),
(869, 'Traffic in MB', ''),
(870, 'Traffic limit [Mb]<br><i>(0 unlimited)</i>', ''),
(871, 'Traffic limit [MB]<br><i>(0 unlimited)</i>', ''),
(872, 'Traffic usage', ''),
(873, 'Traffic<br>usage', ''),
(874, 'Type', ''),
(875, 'Undefined reference to data!', ''),
(876, 'Undefined user accounting error!', ''),
(877, 'uninstall', ''),
(878, 'Uninstall', ''),
(879, 'Unknown', ''),
(880, 'unknown status', ''),
(881, 'Unknown type', ''),
(882, 'unlimited', ''),
(883, 'Unprotect it', ''),
(884, 'UP', ''),
(885, 'Up time', ''),
(886, 'Update', ''),
(887, 'Update data', ''),
(888, 'Update details', ''),
(889, 'Update hosting package', ''),
(890, 'Update language installed!', ''),
(891, 'Update order', ''),
(892, 'Update password', ''),
(893, 'Update plan', ''),
(894, 'Update user', ''),
(895, 'Upload', ''),
(896, 'Upload file error!', ''),
(897, 'Upload logo', ''),
(898, 'Use numeric ID', ''),
(899, 'Use other dir', ''),
(900, 'Used', ''),
(901, 'User (first and last) name', ''),
(902, 'User', ''),
(903, 'User account', ''),
(904, 'User accounts', ''),
(905, 'User added', ''),
(906, 'User added!', ''),
(907, 'User already exist !', ''),
(908, 'User already logged or session sharing problem! Aborting...', ''),
(909, 'User assign', ''),
(910, 'User assignment', ''),
(911, 'User auth', ''),
(912, 'User data not updated!', ''),
(913, 'User data updated!', ''),
(914, 'User deleted', ''),
(915, 'User does not exist or you do not have permission to access this interface!', ''),
(916, 'User does not exist!', ''),
(917, 'User language updated successfully!', ''),
(918, 'User list is empty!', ''),
(919, 'User login (system) name', ''),
(920, 'User name', ''),
(921, 'User name too long!', ''),
(922, 'User not terminated!', ''),
(923, 'User password', ''),
(924, 'User password updated successfully!', ''),
(925, 'User real (first and last) Name', ''),
(926, 'User session was killed!', ''),
(927, 'User sessions', ''),
(928, 'User terminated!', ''),
(929, 'User type', ''),
(930, 'User updated', ''),
(931, 'User was assigned to group', ''),
(932, 'User was deleted from group', ''),
(933, 'User was disabled', ''),
(934, 'User was moved', ''),
(935, 'Username', ''),
(936, 'Users', ''),
(937, 'Users list', ''),
(938, 'Users list is empty!', ''),
(939, 'Very high', ''),
(940, 'ISPCP - Admin - Email Marketing', ''),
(941, 'ISPCP - Admin - Manage custom menus', ''),
(942, 'ISPCP - Admin/Admin Log', ''),
(943, 'ISPCP - Admin/Change Password', ''),
(944, 'ISPCP - Admin/Change Personal Data', ''),
(945, 'ISPCP - Admin/Internationalization', ''),
(946, 'ISPCP - Admin/IP manage', ''),
(947, 'ISPCP - Admin/Lostpw email setup', ''),
(948, 'ISPCP - Admin/Main Index', ''),
(949, 'ISPCP - Admin/Manage Sessions', ''),
(950, 'ISPCP - Admin/Manage Users', ''),
(951, 'ISPCP - Admin/Manage users/Add reseller', ''),
(952, 'ISPCP - Admin/Manage users/Add User', ''),
(953, 'ISPCP - Admin/Manage users/Edit Reseller', ''),
(954, 'ISPCP - Admin/Manage users/Edit User', ''),
(955, 'ISPCP - Admin/Manage users/Email setup', ''),
(956, 'ISPCP - Admin/Manage users/Reseller assignment', ''),
(957, 'ISPCP - Admin/Manage users/User assignment', ''),
(958, 'ISPCP - Admin/Reseller User Statistics', ''),
(959, 'ISPCP - Admin/Server day stats', ''),
(960, 'ISPCP - Admin/Server statistics', ''),
(961, 'ISPCP - Admin/Server Traffic Settings', ''),
(962, 'ISPCP - Administrator/Add hosting plan', ''),
(963, 'ISPCP - Administrator/Edit hosting plan', ''),
(964, 'ISPCP - Administrator/Hosting Plan Management', ''),
(965, 'ISPCP - Circular', ''),
(966, 'ISPCP - Client : Support System: View Tickets', ''),
(967, 'ISPCP - Client/Add FTP User', ''),
(968, 'ISPCP - Client/Add Mail User', ''),
(969, 'ISPCP - Client/Add SQL Database', ''),
(970, 'ISPCP - Client/Add SQL User', ''),
(971, 'ISPCP - Client/Add Subdomain', ''),
(972, 'ISPCP - Client/Change Language', ''),
(973, 'ISPCP - Client/Change Password', ''),
(974, 'ISPCP - Client/Change Personal Data', ''),
(975, 'ISPCP - Client/Change SQL User Password', ''),
(976, 'ISPCP - Client/Create CatchAll Mail Account', ''),
(977, 'ISPCP - Client/Cronjob Manager', ''),
(978, 'ISPCP - Client/Daily Backup', ''),
(979, 'ISPCP - Client/Domain Statistics', ''),
(980, 'ISPCP - Client/Edit FTP Account', ''),
(981, 'ISPCP - Client/Enable Mail Auto Responder', ''),
(982, 'ISPCP - Client/Enable Mail Autoresponder', ''),
(983, 'ISPCP - Client/Execute SQL Query', ''),
(984, 'ISPCP - Client/Main Index', ''),
(985, 'ISPCP - Client/Manage Domains', ''),
(986, 'ISPCP - Client/Manage Error Custom Pages', ''),
(987, 'ISPCP - Client/Manage SQL', ''),
(988, 'ISPCP - Client/Manage Users', ''),
(989, 'ISPCP - Client/Questions & Comments', ''),
(990, 'ISPCP - Client/Webtools', ''),
(991, 'ISPCP - Domain Statistics Data', ''),
(992, 'ISPCP - Domain/Details', ''),
(993, 'ISPCP - Domain/Edit', ''),
(994, 'ISPCP - Manage Domain Alias/Edit Alias', ''),
(995, 'ISPCP - Manage Domain/Alias', ''),
(996, 'ISPCP - Manage Mail and FTP / Edit mail account', ''),
(997, 'ISPCP - Reseller : Support System: View Tickets', ''),
(998, 'ISPCP - Reseller statistics', ''),
(999, 'ISPCP - Reseller/Add hosting plan', ''),
(1000, 'ISPCP - Reseller/Change Password', ''),
(1001, 'ISPCP - Reseller/Change Personal Data', ''),
(1002, 'ISPCP - Reseller/Edit hosting plan', ''),
(1003, 'ISPCP - Reseller/Lostpw email setup', ''),
(1004, 'ISPCP - Reseller/Main Index', ''),
(1005, 'ISPCP - Reseller/Order details', ''),
(1006, 'ISPCP - Reseller/Order email setup', ''),
(1007, 'ISPCP - Reseller/Order management', ''),
(1008, 'ISPCP - Reseller/Order settings', ''),
(1009, 'ISPCP - Support system - New ticket', ''),
(1010, 'ISPCP - Update hosting plan', ''),
(1011, 'ISPCP - User/Add user', ''),
(1012, 'ISPCP - User/Add user(step2)', ''),
(1013, 'ISPCP - Users', ''),
(1014, 'ISPCP - Users/Add user', ''),
(1015, 'ISPCP - Users/Edit', ''),
(1016, 'ISPCP - Virtual Hosting Control System', ''),
(1017, 'ISPCP Admin / System Tools / Server Status', ''),
(1018, 'ISPCP Client : Add Alias', ''),
(1019, 'ISPCP Control Panel', ''),
(1020, 'ISPCP debugger', ''),
(1021, 'ISPCP Reseller : Add Alias', ''),
(1022, 'ISPCP updates', ''),
(1023, 'View', ''),
(1024, 'view aliases', ''),
(1025, 'View details', ''),
(1026, 'View hosting plan', ''),
(1027, 'View support ticket', ''),
(1028, 'Vital system info', ''),
(1029, 'wait to be added', ''),
(1030, 'wait to be deleted', ''),
(1031, 'wait to be enabled', ''),
(1032, 'wait to be modified', ''),
(1033, 'wait to be suspended', ''),
(1034, 'Warning traffic [MB]', ''),
(1035, 'Warning traffic is bigger then max traffic!', ''),
(1036, 'Web & E-Mail Support', ''),
(1037, 'WEB', ''),
(1038, 'Web in', ''),
(1039, 'Web out', ''),
(1040, 'Web traffic', ''),
(1041, 'Web<br>traffic', ''),
(1042, 'Webmail', ''),
(1043, 'Webspace', ''),
(1044, 'Webstatistics', ''),
(1045, 'Webtools', ''),
(1046, 'Weekday(s):', ''),
(1047, 'which has limits for the <b>', ''),
(1048, 'Which has limits for the <b>', ''),
(1049, 'Wildcards as % and ? are not allowed!', ''),
(1050, 'Wrong data input!', ''),
(1051, 'Wrong domain ID!', ''),
(1052, 'Wrong domain name syntax!', ''),
(1053, 'Wrong IP number!', ''),
(1054, 'Wrong order ID!', ''),
(1055, 'Wrong subdomain syntax!', ''),
(1056, 'Wrong username!', ''),
(1057, 'Year', ''),
(1058, 'Year:', ''),
(1059, 'Yellow', ''),
(1060, 'yes', ''),
(1061, 'Yes', ''),
(1062, 'You are exceeding SQL database limit!', ''),
(1063, 'You Are Exceeding Your Alias Limit!', ''),
(1064, 'You are exceeding your disk limit!', ''),
(1065, 'You are exceeding your FTP account limit!', ''),
(1066, 'You are exceeding your mail account limit!', ''),
(1067, 'You are exceeding your subdomain limit!', ''),
(1068, 'You are exceeding your traffic limit!', ''),
(1069, 'You are exceeding your UNLIMITED disk limit!', ''),
(1070, 'You are exceeding your UNLIMITED traffic limit!', ''),
(1071, 'You can not move <b>', ''),
(1072, 'You can not protect area without selected group(s)', ''),
(1073, 'You can not protect area without selected usre(s)', ''),
(1074, 'You can upload only images!', ''),
(1075, 'You can upload only text files!', ''),
(1076, 'You do not have new orders!', ''),
(1077, 'You do not have permission to access this interface!', ''),
(1078, 'You do not have protected areas', ''),
(1079, 'You have', ''),
(1080, 'You have alias limit!<br>You can Not Add User With Unlimited Alias Number!', ''),
(1081, 'You have been blocked for', ''),
(1082, 'You have been reached your domain limit.<br>You can not add more domains !', 'You have reached your domain limit.<br>You can not add more domains !'),
(1083, 'You have disabled SQL databases for this user!<br>You can not have SQL users here!', ''),
(1084, 'You have disk limit!<br>You can not add user with unlimited disk number!', ''),
(1085, 'You have FTP account limit!<br>You can not Add User With Unlimited FTP Accunt Number!', ''),
(1086, 'You have mail account limit!<br>You can not add user with unlimited mail accunt number!', ''),
(1087, 'You have no alias records.', ''),
(1088, 'You have no custom menus.', ''),
(1089, 'You have no groups !', ''),
(1090, 'You have no groups!', ''),
(1091, 'You have no hosting plans. Please add first hosting plan or contact your system administrator.', ''),
(1092, 'You have no new support questions!', ''),
(1093, 'You have no support tickets.', ''),
(1094, 'You have no user records.', ''),
(1095, 'You have no users !', ''),
(1096, 'You have no users!', ''),
(1097, 'You have no users.', ''),
(1098, 'You have SQL database limit!<br>You can not add user with unlimited SQL database number!', ''),
(1099, 'You have SQL user limit!<br>You can not add user with unlimited SQL users!', ''),
(1100, 'You have subdomain limit!<br>You can not add user with unlimited subdomain number!', ''),
(1101, 'You have traffic limit!<br>You can not add user with unlimited traffic number!', ''),
(1102, 'You have to wait', ''),
(1103, 'You must assign at least one IP number for a reseller!', ''),
(1104, 'You send email to your users successfully!', ''),
(1105, 'Your Chart', ''),
(1106, 'Your logo was successful uploaded!', ''),
(1107, 'Your message', ''),
(1108, 'Your message was sent!', ''),
(1109, 'Your order', ''),
(1110, 'Your Own Domain', ''),
(1111, 'Your request for hosting pack update was added successfully', ''),
(1112, 'Your request for hosting pack update was removed successfully', ''),
(1113, 'Zip / Postal code', ''),
(1114, 'Zip/Postal code', '');