#!/usr/bin/perl


use strict;
use warnings;
use Symbol;
use Log::Message::Simple;

no warnings 'once';

use FindBin;
$main::libdir = "$FindBin::Bin/PerlLib/";

require './imscp-common-code.pl';

sub imscp_htusers_init {
	debug((caller(0))[3].': Starting...');
	$main::output = $main::configs{LOG_DIR}.'/'.((caller(0))[1]);
	#$main::task =
	debug((caller(0))[3].': Ending...');
	0;
}

sub imscp_htusers_clean {
	debug((caller(0))[3].': Starting...');
	debug((caller(0))[3].': Ending...');
	0;
}

sub imscp_htusers_process {
	debug((caller(0))[3].': Starting...');
	debug((caller(0))[3].': Ending...');
	0;
}

sub imscp_htusers_entry{
	if (imscp_htusers_init(@_)) {
		imscp_htusers_clean();
		exit 1;
	}

	if (imscp_htusers_process()) {
		imscp_htusers_clean();
		exit 1;
	}

	if (imscp_htusers_clean()) {
		exit 1;
	}
	flushLogs();
	exit 0;
}

