#!/usr/bin/perl
#
# i-MSCP - internet Multi Server Control Panel
# Copyright (C) 2010 by internet Multi Server Control Panel
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# @category		i-MSCP
# @copyright	2010 by i-MSCP | http://i-mscp.net
# @author		Daniel Andreca <sci2tech@i-mscp.net>
# @version		SVN: $Id: imscp-build 3933 2010-12-01 19:35:32Z sci2tech $
# @link			http://i-mscp.net i-MSCP Home Site
# @license      http://www.gnu.org/licenses/gpl-2.0.html GPL v2

use strict;
use warnings;
use Symbol;
use Log::Message::Simple;

no warnings 'once';

use FindBin;

use lib "$FindBin::Bin/PerlLib";
use lib "$FindBin::Bin/PerlLib/Vendor";

require './imscp-common-code.pl';

sub imscp_rqst_init {
	debug((caller(0))[3].': Starting...');

	use iMSCP::Boot;

	my $x = iMSCP::Boot->new();
	$main::output = $main::configs{log_dir}.'/'.((caller(0))[1]);
	umask(027);

	debug((caller(0))[3].': Ending...');

	0;
}

sub imscp_rqst_clean {
	debug((caller(0))[3].': Starting...');

	debug((caller(0))[3].': Ending...');

	0;
}

sub imscp_rqst_process {
	debug((caller(0))[3].': Starting...');

	debug((caller(0))[3].': Ending...');

	0;
}

if (imscp_rqst_init()) {
	imscp_rqst_clean();

	exit 1;
}

if (imscp_rqst_process()) {
	imscp_rqst_clean();

	exit 1;
}

if (imscp_rqst_clean()) {
	exit 1;
}

my $x = iMSCP::Database::Database->getInstance()->doQuery('Database', 'Show databases;');

while(my ($key, $value) = each(%$x)){
	debug($value->{'Database'});
}

$main::configs{debug} = 'a';

flushLogs();

do 'imscp-htusers-mngr';
my $xxx = "aaaa\n";
my $code = sub {imscp_htusers_entry($xxx)};
&$code('aaa');



exit 0;
