#!/bin/sh
XGETTEXT_OPTIONS="--keyword=_ -keyword=N_ --default-domain=add_address --no-wrap --no-location --add-comments=i18n"

# Allows controlling language option
# (gettext v.0.10.40 = -C, gettext 0.11+ = -L php).
if [ $SM_OLD_GETTEXT ] ; then
 XGETTEXT_OPTIONS="${XGETTEXT_OPTIONS} -C";
else
 XGETTEXT_OPTIONS="${XGETTEXT_OPTIONS} -L php";
fi

xgettext ${XGETTEXT_OPTIONS} *.php --output=add_address.pot
xgettext ${XGETTEXT_OPTIONS} -j templates/default/*.tpl --output=add_address.pot
