		<!-- BDP: page_message -->
		<!--<div class="{MESSAGE_CLS} message">{MESSAGE}</div>-->
		<!-- EDP: page_message -->
		<div id="outer">
			<div id="middle">
				<div id="inner">
					<form name="lostpwd_frm"  action="index" method="post" >
						<fieldset style="top:160px;">
							<span><?php echo $this->captchaCode?></span>
							<label>Code:<input type="text" name="captcha[input]" value="" maxlength="255" tabindex="1" /></label>
							<label>Username:<input type="text" name="uname" id="uname" value="" maxlength="255" tabindex="2" /></label>
							<div class="buttons" style="margin-top:20px;">
								<input type="submit" name="back" value="Back" tabindex="2" onclick="location.href='/index';return false"/>&nbsp;&nbsp;&nbsp;
								<input style="padding-left:3px;" type="submit" name="Submit" value="Send request" tabindex="3" />
								<input type="hidden" name="captcha[id]" value="<?php echo $this->captchaId?>">
							</div>
						</fieldset>
					</form>
				</div>
				<div class="info" style="width:450px;position: relative;top:-50%;margin-left:auto;margin-right: auto;">
					To avoid abuse, we ask you to write the combination of letters on the picture above into the field "Security code"
				</div>
			</div>
		</div>
