		<!-- BDP: page_message -->
		<div class="{MESSAGE_CLS} message">{MESSAGE}</div>
		<!-- EDP: page_message -->
		<div id="outer">
			<div id="middle">
				<div id="inner">
					<form name="lostpwd_frm" action="lostpassword.php" method="post" >
						<fieldset style="top:140px;">
							<!--<span>{TR_IMGCAPCODE}</span>-->
							<label>Code:<input type="text" name="uname" id="uname" value="" maxlength="255" tabindex="1" /></label>
							<label>Username:<input type="text" name="capcode" value="" maxlength="255" tabindex="2" /></label>
							<div class="buttons" style="margin-top:10px;">
								<input type="submit" name="back" value="Back" tabindex="2" onclick="location.href='index.php';return false"/>&nbsp;&nbsp;&nbsp;
								<input style="padding-left:3px;" type="submit" name="Submit" value="Send request" tabindex="3" />
							</div>
						</fieldset>
					</form>
				</div>
				<div class="info" style="width:450px;position: relative;top:-50%;margin-left:auto;margin-right: auto;">{TR_IMGCAPCODE_DESCRIPTION}</div>
			</div>
		</div>
