#!/bin/sh
# i-MSCP - internet Multi Server Control Panel
# Copyright (C) 2010-2018 by Laurent Declercq <l.declercq@nuxwin.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

set -e

cd ../..

if [ ! -f "gui/public/index.php" ]; then
	echo "You must run this script from the i18n/tools directory!"
	exit 1
fi

# Only for debugging purpose
# Transifex is taking care of merging
#for i in i18n/po/*; do
#	echo "Updating ${i} file"
#	msgmerge -U ${i} i18n/iMSCP.pot
#done

# Purge any old language file
rm -fR gui/i18n/locales/*

for i in `find i18n/po -name '*.po' | sed -r 's/.*\/(.*)/\1/'`; do
	echo "Compiling machine object file: ${i}"
	LOCALE=`echo ${i} | cut -d '.' -f 1`
	DESTDIR="gui/i18n/locales/${LOCALE}/LC_MESSAGES"
	mkdir -p ${DESTDIR}
	msgfmt --strict --no-hash --use-fuzzy -o ${DESTDIR}/${LOCALE}.mo i18n/po/${i}
done
