.ifdef $(OSTYPE)==FreeBSD
.include <../../Makefile.fbsd>
.else
 .include <../../Makefile.inc>
.endif

SYSTEM_ENGINE_ROOT=$(SYSTEM_ROOT)/engine

CMD_INSTALL=/usr/bin/install -m 0700 -o root -g wheel

CMD_CHOWN=/bin/chown

install:

	$(SYSTEM_MAKE_DIRS) $(INST_PREF)/usr/local/sbin
	$(CMD_INSTALL) ./maillogconvert/maillogconvert.pl $(INST_PREF)/usr/local/sbin

uninstall:

	rm -rf $(INST_PREF)/usr/local/sbin/maillogconvert.pl
