.include <../../../Makefile.fbsd>

install:

	$(SYSTEM_MAKE_DIRS) $(ROOT_CONF)/rc.d

	cp ispcp_daemon $(ROOT_CONF)/rc.d
	cp ispcp_network $(ROOT_CONF)/rc.d

	chown root:wheel $(ROOT_CONF)/rc.d/ispcp_network $(ROOT_CONF)/rc.d/ispcp_daemon
	chmod 0755 $(ROOT_CONF)/rc.d/ispcp_network $(ROOT_CONF)/rc.d/ispcp_daemon

uninstall:

	rm -f $(ROOT_CONF)/rc.d/ispcp_daemon
	rm -f $(ROOT_CONF)/rc.d/ispcp_network
