# i-MSCP - internet Multi Server Control Panel
# Copyright 2010-2017 by Laurent Declercq <l.declercq@nuxwin.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

Vagrant.configure("2") do |config|
    # Debian 8.x/Jessie
    config.vm.define 'imscp_debian_jessie', autostart: false do |node|
        node.vm.box = 'debian/jessie64'
        node.vm.network :public_network

        node.vm.provider :virtualbox do |vb|
            vb.customize ['modifyvm', :id, '--memory', '1024']
            vb.customize ['modifyvm', :id, '--name', 'imscp_debian_jessie']
        end
        
        node.vm.provider :lxc do |lxc|
            lxc.customize 'cgroup.memory.limit_in_bytes', '1024M'
            lxc.container_name = 'imscp_debian_jessie'
        end
    end

    # Debian 9.x/Stretch (default if no box name passed-in to vagrant CLI)
    config.vm.define 'imscp_debian_stretch', autostart: true do |node|
        node.vm.box = 'debian/stretch64'
        node.vm.network :public_network

        node.vm.provider :virtualbox do |vb|
            vb.customize ['modifyvm', :id, '--memory', '1024']
            vb.customize ['modifyvm', :id, '--name', 'imscp_debian_stretch']
        end
        
        node.vm.provider :lxc do |lxc|
            lxc.customize 'cgroup.memory.limit_in_bytes', '1024M'
            lxc.container_name = 'imscp_debian_stretch'
        end
    end

    # Ubuntu Trusty Thar (14.04)
    config.vm.define 'imscp_ubuntu_trusty', autostart: false do |node|
        node.vm.box = 'ubuntu/trusty64'
        node.vm.network :public_network

        node.vm.provider :virtualbox do |vb|
            vb.customize ['modifyvm', :id, '--memory', '1024']
            vb.customize ['modifyvm', :id, '--name', 'imscp_ubuntu_trusty']
        end
    end

    # Ubuntu Xenial Xerus (16.04)
    config.vm.define 'imscp_ubuntu_xenial', autostart: false do |node|
        node.vm.box = 'ubuntu/xenial64'
        node.vm.network :public_network

        node.vm.provider :virtualbox do |vb|
            vb.customize ['modifyvm', :id, '--memory', '1024']
            vb.customize ['modifyvm', :id, '--name', 'imscp_ubuntu_xenial']
        end
    end

    # Make sure that distribution is up-to-date
    config.vm.provision "shell", path: "docs/vagrant/scripts/distro_update.sh"

    # Reboot the VM (possible kernel update)
    config.vm.provision :reload

    # Provision i-MSCP
    config.vm.provision "shell", path: "docs/vagrant/scripts/provision_imscp.sh"
end
