#!/bin/sh
# i-MSCP - internet Multi Server Control Panel
# Copyright 2010-2017 by Laurent Declercq <l.declercq@nuxwin.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

Vagrant.configure("2") do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "stretch64"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "https://app.vagrantup.com/debian/boxes/stretch64/versions/9.1.0/providers/virtualbox.box"

  # Provisioning 

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  config.vm.network :public_network

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.

  # Drop the memory requirement to 1024 for now.
  config.vm.provider :virtualbox do |vb, override|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    override.vm.box = "stretch64"
    override.vm.box_url = "https://app.vagrantup.com/debian/boxes/stretch64/versions/9.1.0/providers/virtualbox.box"
  end

  config.vm.provider :lxc do |lxc, override|
    lxc.cgroup.memory.limit_in_bytes='1024'
    override.vm.box = "stretch64"
    override.vm.box_url = "https://app.vagrantup.com/debian/boxes/stretch64/versions/9.1.0/providers//lxc.box"
  end

  # Make sure that distribution is up-to-date
  config.vm.provision "shell", path: "docs/vagrant/scripts/distro_update.sh"

  # Reboot the VM (possible kernel update)
  config.vm.provision :reload

  # Provision i-MSCP
  config.vm.provision "shell", path: "docs/vagrant/scripts/provision_imscp.sh"
end
