# ISPCP(tm) - Virtual Hosting Control System
# Copyright (c) 2001-2004 by moleSoftware GmbH
# http://www.molesoftware.com
#
#
# License:
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of the MPL Mozilla Public License
#    as published by the Free Software Foundation; either version 1.1
#    of the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    MPL Mozilla Public License for more details.
#
#    You may have received a copy of the MPL Mozilla Public License
#    along with this program.
#
#    An on-line copy of the MPL Mozilla Public License can be found
#    http://www.mozilla.org/MPL/MPL-1.1.html
#
#
# The ISPCP Home Page is at:
#
#    http://www.isp-control.net

.include <../Makefile.inc>

SYSTEM_GUI_ROOT=$(SYSTEM_ROOT)/gui

install:
	$(SYSTEM_MAKE_DIRS) $(SYSTEM_GUI_ROOT)
	cp ./index.php $(SYSTEM_GUI_ROOT)/index.php
	cp ./lostpassword.php $(SYSTEM_GUI_ROOT)/lostpassword.php
	cp ./imagecode.php $(SYSTEM_GUI_ROOT)/imagecode.php
	cp ./robots.txt $(SYSTEM_GUI_ROOT)/robots.txt
	cp -R ./admin $(SYSTEM_GUI_ROOT)
	cp -R ./reseller $(SYSTEM_GUI_ROOT)
	cp -R ./client $(SYSTEM_GUI_ROOT)
	cp -R ./include $(SYSTEM_GUI_ROOT)
	cp -R ./domain_default_page $(SYSTEM_GUI_ROOT)
	cp -R ./errordocs $(SYSTEM_GUI_ROOT)
	cp -R ./themes $(SYSTEM_GUI_ROOT)
	cp -R ./tools $(SYSTEM_GUI_ROOT)
	cp -R ./orderpanel $(SYSTEM_GUI_ROOT)
	cp -R ./phptmp $(SYSTEM_GUI_ROOT)
uninstall:
	rm -rf $(SYSTEM_GUI_ROOT)

.PHONY: install uninstall
