# ispCP ω (OMEGA) a Virtual Hosting Control Panel
# Copyright (c) 2001-2006 by moleSoftware GmbH
# http://www.molesoftware.com
# Copyright (c) 2006-2008 by isp Control Panel
# http://isp-control.net
#
#
# License:
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of the MPL Mozilla Public License
#    as published by the Free Software Foundation; either version 1.1
#    of the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    MPL Mozilla Public License for more details.
#
#    You may have received a copy of the MPL Mozilla Public License
#    along with this program.
#
#    An on-line copy of the MPL Mozilla Public License can be found
#    http://www.mozilla.org/MPL/MPL-1.1.html
#
#
# The ISPCP ω Home Page is at:
#
#    http://isp-control.net
#

#ifneq (,$(findstring noopt,$(DAEMON_OPTIONS)))
#	CFLAGS += -O0
#else
	CFLAGS += -O3
endif
#endif


OBJS = ispcp_daemon.o message.o daemon_init.o say.o signal-handlers.o\
receive_data.o send_data.o take_connection.o send_line.o recv_line.o\
helo_cmd.o helo_syntax.o lr_cmd.o lr_syntax.o bye_cmd.o bye_syntax.o

BUILD = gcc -ansi -Wall -Wstrict-prototypes -pedantic $(CFLAGS)

COMPILE = gcc -ansi -Wall -Wstrict-prototypes -pedantic -c $(CFLAGS)

ispcp_daemon: $(OBJS)
	$(BUILD) -o ispcp_daemon $(OBJS)
#ifeq (,$(findstring nostrip,$(DAEMON_OPTIONS)))
	strip -s ispcp_daemon
#endif

%.o: %.c %.h
	$(COMPILE) -o $@ $*.c

clean:
	rm -rf *~
	rm -rf *.o
	rm -rf ispcp_daemon

.PHONY: clean
