#
#  ispCP . (OMEGA) - Virtual Hosting Control System | Omega Version
#
#  @copyright  2001-2006 by moleSoftware GmbH
#  @copyright  2006-2007 by ispCP | http://isp-control.net
#  @link   http://isp-control.net
#  @author  ispCP Team
#
#  @license
#  This program is free software; you can redistribute it and/or modify it under
#  the terms of the MPL General Public License as published by the Free Software
#  Foundation; either version 1.1 of the License, or (at your option) any later
#  version.
#  You should have received a copy of the MPL Mozilla Public License along with
#  this program; if not, write to the Open Source Initiative (OSI)
#  http://opensource.org | osi@opensource.org
#

ifneq (,$(findstring noopt,$(DAEMON_OPTIONS)))
        CFLAGS += -O0
else
        CFLAGS += -O3
endif

ifneq (,$(findstring nostrip,$(DAEMON_OPTIONS)))
        STRIP = touch -a -c
else
        STRIP = strip -s
endif


OBJS = ispcp_daemon.o message.o daemon_init.o say.o signal-handlers.o\
receive_data.o send_data.o take_connection.o send_line.o recv_line.o\
helo_cmd.o helo_syntax.o lr_cmd.o lr_syntax.o bye_cmd.o bye_syntax.o

BUILD = gcc -ansi -Wall -Wstrict-prototypes -pedantic $(CFLAGS)

COMPILE = gcc -ansi -Wall -Wstrict-prototypes -pedantic -c $(CFLAGS)

ispcp_daemon: $(OBJS)
	$(BUILD) -o ispcp_daemon $(OBJS)
	$(STRIP) ispcp_daemon

%.o: %.c %.h
	$(COMPILE) -o $@ $*.c

clean:
	rm -rf *~
	rm -rf *.o
	rm -rf ispcp_daemon

.PHONY: clean
