
.include <../../../../Makefile.inc>

install:
	$(SYSTEM_MAKE_DIRS) $(SYSTEM_CONF)/database
	cp ./database.sql $(SYSTEM_CONF)/database
	cp ./languages.sql $(SYSTEM_CONF)/database

uninstall:
	rm -rf $(SYSTEM_CONF)/database
        
