<div id="box">
	<div id="boxHeader"></div>
		<div id="content">
			<h1>An exception occurred</h1>
			<?php if (isset($this->exception)): ?>
			<p><strong>Message:</strong> <?php echo $this->exception->getMessage() ?></p>
			<?php else: ?>
			<p><?php echo $this->message ?> !</p>
			<?php endif ?>
			<!--<a href="{BACK_BUTTON_DESTINATION}" target="_self">{TR_BACK}</a>-->
	</div>
</div>

<!--
  <?php //if (isset($this->exception)): ?>

  <h3>Exception information:</h3>
  <p><b>Message:</b> <?php //echo $this->exception->getMessage() ?></p>

  <h3>Stack trace:</h3>
  <pre><?php //echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?php //echo var_export($this->request->getParams(), true) ?>
  </pre>
  <?php //endif ?>
-->
