<?php $this->headTitle($this->translate('Hosting services - Customers list'));?>
<?php $this->jQuery()->addOnload('
	$(".actions-box-body").hide();

	$("#expandable").toggle(function() {
		$(".actions-box-body").show();
		$(this).text("Colapse");
	}, function() {
		$(".actions-box-body").hide();
		$(this).text("Expand");
	});
');
?>

<h2 class="users"><span><?php echo $this->translate('Customers');?><span class="icon_pageup i_bc_parent" onclick="history.go(-1);return false;"><?php echo $this->translate('Up Level');?></span></span></h2>
<p><?php echo $this->translate("This is where you manage accounts of your hosting service customers: create new accounts along with service subscriptions, manage existing customers, and remove accounts. To administer websites, mail or any other services provided to a customer, go to their Control Panel by clicking the Control Panel link in the list.");?></p>

<form id="frm_actions" action="<?php echo $this->url();?>" method="post">
	<table class="actions-box-header" width="auto">
		<tr>
			<td>
				<span><a class="icon i_add_user" href="<?php echo $this->url(array(),'hosting_services_account_customer_create');?>"><?php echo $this->translate("Add new customer");?></a></span> |
				<span><a class="icon i_delete" href="customers-list.phtml#"><?php echo $this->translate("Remove");?></a></span> |
				<span><a class="icon i_action_expand" href="customers-list.phtml#"><?php echo $this->translate("More action");?></a></span>
			</td>
			<td align="right">
				<span><input type="text" name="search" id="search" value="" /></span>
				<span id="expandable">Expand</span>
			</td>
		</tr>
		<tr class="actions-box-body">
			<td colspan="2">
	            <div>
	                <label for="customer_name"><?php echo $this->translate("Customer name");?></label>
	                <input type="text" id="customer_name" name="customer_name" value="" />
		        </div>
	            <div>
	            <label for="subscriptions"><?php echo $this->translate("Subscriptions");?></label>
				<select name="subscriptions" id="subscriptions">
					<option selected="selected" value="any"><?php echo $this->translate("Any");?></option>
				</select>
		        </div>
	            <div>
		            <label for="providers"><?php echo $this->translate("Providers");?></label>
					<select name="providers" id="providers">
						<option selected="selected" value="all customers"><?php echo $this->translate("All customers");?></option>
						<option value="0"><?php echo $this->translate("my customers");?></option>
						<option value="1"><?php echo $this->translate("%1\$s's customers", 'First Reseller');?></option>
					</select>
	            </div>
	            <div>
		            <label for="status"><?php echo $this->translate("Status");?></label>
					<select name="status" id="status">
						<option selected="selected"><?php echo $this->translate("Any");?></option>
						<option><?php echo $this->translate("Suspended");?></option>
						<option><?php echo $this->translate("Active");?></option>
					</select>
	            </div>
	            <div>
					<br />
					<a class="icon i_search" href="customers-list.phtml#" onclick="$('#frm_actions').submit();return true;" " ><?php echo $this->translate("Search");?></a> <a class="icon i_reload" href="customers-list.phtml#"><?php echo $this->translate("Reset search");?></a>
	            </div>
			</td>
		</tr>
	</table>
</form>


<?php if(!empty($this->customers)):?>
<!-- top paginator - begin -->
<div style="width:auto;height:15px;margin:15px;">
	<div style="float:left;">
		<?php echo vsprintf($this->translate()->getTranslator()->plural("%1\$d item total", "%1\$d items total", 4), 4);?>
	</div>
	<div style="float:right;">
		<?php echo $this->translate("Number of entries per page");?>: <a>10</a> <a>25</a> <a>50</a> <?php echo $this->translate("All");?>
	</div>
</div>
<!-- top paginator - ending -->
<div>
	<table>
		<tr>
			<th width="30"><input type="checkbox" style="margin-top:0;margin-bottom:0" /></th>
			<th><?php echo $this->translate("Customer name");?></th>
			<th><?php echo $this->translate("Subscription");?></th>
			<th><?php echo $this->translate("Setup date");?></th>
			<th colspan="2"><?php echo $this->translate("Provider");?></th>
		</tr>
		<?php foreach($this->customers as $customer):?>
		<tr>
			<td><input type="checkbox" value="id[<?php echo $customer->id;?>]"/></td>
			<td><a style="vertical-align:middle"class="icon i_ok" href="customers-list.phtml#"></a><a href="customers-list.phtml#"><?php echo $customer->username;?></a></td>
			<td><?php echo $customer->domain_name;?>  (<?php echo $customer->subscription;?><a href="customers-list.phtml#">(?)</a></td>
			<td><?php echo $customer->created_at;?></td>
			<td><?php echo $customer->provider;?></td>
			<td><a class="icon i_goto" href="customers-list.phtml#"><?php echo $this->translate("Control Panel");?></a></td>
		</tr>
		<?php endforeach;?>
	</table>
</div>

<div style="width:auto;height:15px;margin:15px;">
	<div style="float:left;">
		<?php echo vsprintf($this->translate()->getTranslator()->plural("%1\$d item total", "%1\$d items total", 4), 4);?>
	</div>
	<div style="float:right;">
		<?php echo $this->translate("Number of entries per page");?>: <a>10</a> <a>25</a> <a>50</a> <?php echo $this->translate("All");?>
	</div>
</div>
<?php else:?>
<div class="messages info"><?php echo $this->translate('No items found!');?></div>
<?php endif;?>