<?php $this->headTitle($this->translate('Hosting services - Adding new reseller'));?>
<?php $this->jQuery()->addOnload('
	$("#username").focus();
	$("#password").keyup(function(){$("#password_text").val($(this).val());});
	$("#password_text").keyup(function(){$("#password").val($(this).val());});
	$("#show_password,").click(function(){$("#password,#password_text").toggle();});
	$("#show_password").toggle(function(){$(this).val("' . $this->translate('Hide password') . '");},function(){$(this).val("' .$this->translate('Show password') .'");});
');?>

<h2 class="user"><span><?php echo $this->translate('Adding new reseller');?><span class="icon_pageup i_bc_parent" onclick="history.go(-1);return false;"><?php echo $this->translate('Up Level');?></span></span></h2>

<form name="addUserForm" method="post" action="<?php echo $this->url();?>">
    <fieldset>
        <legend><?php echo $this->translate('Reseller information');?>:</legend>
        <table>
            <tr>
                <td width="200"><label for="username"><?php echo $this->translate('Username');?></label></td>
                <td><input type="text" name="username" id="username" maxlength="8" value="<?php echo $this->escape($this->username);?>"/></td>
            </tr>
            <tr>
                <td width="200"><label for="password"><?php echo $this->translate('Password');?></label></td>
                <td>
	                <input type="password" name="password" id="password" maxlength="8" style="vertical-align:middle" value="<?php echo $this->escape($this->password);?>"/>
	                <input type="text" name="password_text" id="password_text" maxlength="8" style="display:none;vertical-align:middle" value="<?php echo $this->escape($this->password);?>"/>
	                <input type="button" name="show_password" id="show_password" style="vertical-align:middle" value="<?php echo $this->translate('Show password');?>"/>
                </td>
            </tr>
            <tr>
                <td width="200"><label for="password_confirm"><?php echo $this->translate('Confirm password');?></label></td>
                <td><input type="password" name="password_confirm" id="password_confirm" maxlength="8" value="<?php echo $this->escape($this->password_confirm);?>"/></td>
            </tr>
            <tr>
                <td width="200"><label for="email"><?php echo $this->translate('Email address');?></label></td>
                <td><input type="text" name="email" id="email" maxlength="255" value="<?php echo $this->escape($this->email);?>"/></td>
            </tr>
			<tr>
				<td width="200"><label for="is_active_yes"><?php echo $this->translate('Activate user ?');?></label></td>
				<td>
					<input type="radio" name="is_active" id="is_active_yes" class="buttons" value="1" style="vertical-align:middle" <?php echo ($this->is_active) ? 'checked="checked"' : '';?>/>
					<span style="vertical-align:middle"><?php echo $this->translate('Yes');?></span>
					<input type="radio" name="is_active" id="is_active_no" class="buttons" value="0" style="vertical-align:middle" <?php echo (!$this->is_active) ? 'checked="checked"' : '';?>/>
					<span style="vertical-align:middle"><?php echo $this->translate('No');?></span>
                </td>
            </tr>
        </table>
    </fieldset>
	<div class="buttons">
	    <input name="submit" type="submit" class="buttons" value="<?php echo $this->translate('Add');?>" />
		<input type="reset" class="buttons" value="<?php echo $this->translate('Reset');?>" />
	</div>
</form>