<?php $this->headTitle($this->translate('Hosting services - Resellers list'));?>

<h2 class="users"><span><?php echo $this->translate('Resellers');?><span class="icon_pageup i_bc_parent" onclick="history.go(-1);return false;"><?php echo $this->translate('Up Level');?></span></span></h2>

<p><?php echo $this->translate("This is where you manage accounts of resellers — your customers who resell hosting services and host their own websites. Here, you create new accounts along with service subscriptions, manage existing resellers, and remove accounts.");?></p>

<table width="auto">
	<tr>
		<td class="box-action">
			<span><a class="icon i_add_user" href="<?php echo $this->url(array(),'hosting_services_account_reseller_create')?>"><?php echo $this->translate("Add new reseller");?></a></span>&nbsp;&nbsp;&nbsp;|
			<span><a class="icon i_delete" href="resellers-list.phtml#"><?php echo $this->translate("Remove");?></a></span>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
			<span><a  class="icon i_action_expand" style="margin:0;background-position:right;padding-left: 0px;padding-right: 20px;" href="resellers-list.phtml#" ><?php echo $this->translate("More action");?></a></span>
		</td>
		<td class="box-action" align="right">
			<span>
				<input type="text" id="search_text" value=""/>
			</span>
			<span>
				<a id="test" onclick="$('#search').toggle();return false;" href="#">Expand</a>
			</span>
		</td>
	</tr>
	<tr style="background:#94CAF5;display:none" id="search">
		<td colspan="2">
            <form action="../../../../core/views/scripts/user">
	            <div style="float:left;">
	                <label style="display:block" for="customer_name"><?php echo $this->translate("Customer name");?></label>
	                <input type="text" name="customer_name" value="">
		        </div>
	            <div style="float:left;margin-left:5px;">
	                <label style="display:block"for="subscriptions"><?php echo $this->translate("Subscriptions");?></label>
					<select name="subscriptions">
						<option><?php echo $this->translate("Any");?></option>
					</select>
		        </div>
	            <div style="float:left;margin-left:5px;">
		            <label style="display:block" for="providers"><?php echo $this->translate("Providers");?></label>
					<select name="providers">
						<option><?php echo $this->translate("All providers");?></option>
						<option><?php echo $this->translate("My customers");?></option>
						<option>First reseller</option>
					</select>
	            </div>
	            <div style="float:left;margin-left:5px;">
		            <label style="display:block" for="providers"><?php echo $this->translate("Status");?></label>
					<select name="status">
						<option><?php echo $this->translate("Any");?></option>
						<option><?php echo $this->translate("Suspended");?></option>
						<option><?php echo $this->translate("Active");?></option>
					</select>
	            </div>
	            <div style="float:left;margin-left:5px;">
		            <br />
		          <a class="icon i_search" href="resellers-list.phtml#"><?php echo $this->translate("Search");?></a> <a class="icon i_reload" href="resellers-list.phtml#"><?php echo $this->translate("Reset search");?></a>
	            </div>
            </form>
		</td>
	</tr>
</table>

<div style="width:auto;height:15px;margin:15px;">
	<div class="item_number left" style="float:left;"><?php echo vsprintf($this->translate()->getTranslator()->plural("%1\$d item total", "%1\$d items total", 1), 1);?></div>
	<div class="paginate right" style="float:right;"><?php echo $this->translate("Number of entries per page");?>: 10 25 100 <?php echo $this->translate("All");?></div>
</div>

<div class="grid">
	<form action="../../../../core/views/scripts/user">
		<table>
			<tr style="background:#161E73">
				<th width="30"><input type="checkbox" style="margin-top:0;margin-bottom:0"/></th>
				<th><?php echo $this->translate("Reseller name");?></th>
				<th><?php echo $this->translate("Service plan");?></th>
				<th><?php echo $this->translate("Setup date");?></th>
				<th><?php echo $this->translate("Customers");?></th>
			</tr>
			<tr>
				<td><input type="checkbox" value=""/></td>
				<td><a style="vertical-align:middle"class="icon i_ok" href="resellers-list.phtml#"></a><a href="resellers-list.phtml#">Reseller-test</a></td>
				<td>Reseller Plan 1</td>
				<td>Jan 14, 2010</td>
				<td>5</td>
			</tr>
		</table>
	</form>
</div>

<div style="width:auto;height:15px;margin:15px;">
	<div class="item_number left" style="float:left;"><?php echo vsprintf($this->translate()->getTranslator()->plural("%1\$d item total", "%1\$d items total", 1), 1);?></div>
	<div class="paginate right" style="float:right;"><?php echo $this->translate("Number of entries per page");?>: <a>10</a> <a>25</a> <a>50</a> <?php echo $this->translate("All");?></div>
</div>
