
<form method="post" action="password_update.php" autocomplete="off">
    <table class="firstColFixed">
        <thead>
        <tr>
            <th colspan="3"><?= tohtml(tr('Login data')); ?></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td><label for="password"><?= tohtml(tr('Password')); ?></label></td>
            <td><input name="admin_pass" id="password" type="password" value="" class="pwd_generator" autocomplete="new-password" required>
            </td>
        </tr>
        <tr>
            <td><label for="cpassword"><?= tohtml(tr('Password confirmation')); ?></label></td>
            <td><input name="admin_pass_confirmation" id="cpassword" type="password" value="" autocomplete="new-password" required></td>
        </tr>
        </tbody>
    </table>
    <div class="buttons">
        <input type="submit" name="Submit" value="<?= tohtml(tr('Update', 'htmlAttr')); ?>">
    </div>
</form>
