#!/bin/sh
#
# ispCP required repositories install script for OpenSuse 11.1
#
# ispCP ω (OMEGA) a Virtual Hosting Control System
#
# copyright	2009 by ispCP | http://isp-control.net
# link		http://isp-control.net
# author	Laurent Declercq <l.declercq@nuxwin.com>
#
# license
#  This program is free software; you can redistribute it and/or modify it under
#  the terms of the MPL General Public License as published by the Free Software
#  Foundation; either version 1.1 of the License, or (at your option) any later
#  version.
#  You should have received a copy of the MPL Mozilla Public License along with
#  this program; if not, write to the Open Source Initiative (OSI)
#  http://opensource.org | osi@opensource.org
#


ZYPPER_BIN=/usr/bin/zypper
URI_BASE="http://download.opensuse.org/repositories"

case "$1" in

	add)
		# Proftpd && Cie...
		$ZYPPER_BIN ar $URI_BASE/home:/csbuild/openSUSE_11.1/ ispcp-proftpd

		# Awstats
		$ZYPPER_BIN ar $URI_BASE/network:/utilities/openSUSE_11.1/ ispcp-awstats

		# Apache && Cie...
		$ZYPPER_BIN ar $URI_BASE/Apache:/Modules/openSUSE_11.1/ ispcp-apache2

		# Rkhunter
		$ZYPPER_BIN ar $URI_BASE/openSUSE:/Factory:/Contrib/openSUSE_11.1/ ispcp-rkhunter

		# Perl lib
		$ZYPPER_BIN ar $URI_BASE/home:/csbuild:/Perl/openSUSE_11.1/ ispcp-perllib

		# Refresh all repositories
		$ZYPPER_BIN ref
	;;
	rm)
		REPO="proftpd awstats apache2 rkhunter perllib"

		for i in $REPO
   			do $ZYPPER_BIN rr ispcp-$i
		done

	;;

	*)
		echo "Usage: sh ./opensuse111-repositories {add|rm}"

	exit 1
esac



