#!/bin/sh
#
# ispCP required repositories install script for OpenSuse 11.2
#
# ispCP ω (OMEGA) a Virtual Hosting Control Panel
# Copyright (C) 2006-2009 by isp Control Panel - http://ispcp.net
# author	Laurent Declercq <laurent.declercq@ispcp.net>
#
# SVN: $Id$
#
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is "ispCP ω (OMEGA) a Virtual Hosting Control Panel".
#
# The Initial Developer of the Original Code is ispCP Team.
# Portions created by Initial Developer are Copyright (C) 2006-2009 by
# isp Control Panel. All Rights Reserved.
#
# The ispCP ω Home Page is:
#
#    http://isp-control.net


ZYPPER_BIN=/usr/bin/zypper
URI_BASE="http://download.opensuse.org/repositories"

case "$1" in

	add)
		# Proftpd && Cie...
		$ZYPPER_BIN ar $URI_BASE/server:/ftp/openSUSE_11.2/ ispcp-proftpd

		# Awstats
		$ZYPPER_BIN ar $URI_BASE/network:/utilities/openSUSE_11.2/ ispcp-awstats

		# Apache && Cie...
		$ZYPPER_BIN ar $URI_BASE/Apache:/Modules/Apache_openSUSE_11.2/ ispcp-apache2

		# Rkhunter
		$ZYPPER_BIN ar $URI_BASE/openSUSE:/Factory:/Contrib/openSUSE_11.2/ ispcp-rkhunter

		# Postgrey && Policy-weight
		$ZYPPER_BIN ar $URI_BASE/home:/pheinlein/openSUSE_11.2/ ispcp-mtools

		# lha
		$ZYPPER_BIN ar $URI_BASE/openSUSE:/Factory:/Contrib/openSUSE_11.2/ ispcp-lha

		# Refresh all repositories
		$ZYPPER_BIN ref
	;;
	rm)
		REPO="proftpd awstats apache2 rkhunter perllib mtools lha"

		for i in $REPO
   			do $ZYPPER_BIN rr ispcp-$i
		done

	;;

	*)
		echo "Usage: sh ./opensuse112-repositories {add|rm}"

	exit 1
esac

exit 0
