#!/bin/sh
#
# ispCP post installation script for OpenSuse 11.1, 11.2
#
# ispCP ω (OMEGA) a Virtual Hosting Control Panel
# Copyright (C) 2006-2009 by isp Control Panel - http://ispcp.net
# author        Laurent Declercq <laurent.declercq@ispcp.net>
# version		1.3
#
# SVN: $Id$
#
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is "ispCP ω (OMEGA) a Virtual Hosting Control Panel".
#
# The Initial Developer of the Original Code is ispCP Team.
# Portions created by Initial Developer are Copyright (C) 2006-2009 by
# isp Control Panel. All Rights Reserved.
#
# The ispCP ω Home Page is:
#
#    http://isp-control.net
#

# Special note for DevTeam:
#
# It is necessary for the error recovery and update procedures that the scripts 
# be idempotent. This means that if it is run successfully, and then it is
# called again, it doesn't bomb out or cause any harm, but just ensures that
# everything is the way it ought to be. If the first call failed, or aborted
# half way through for some reason, the second call should merely do the things
# that were left undone the first time, if any, and exit with a success status
# if if everything is OK.

set -e

CONF_FILE=/etc/ispcp/ispcp.conf

if [ ! -f $CONF_FILE ] ; then
 echo "E: $CONF_FILE not found!"
 echo "Fix the problem and try to execute the ispcp-update script!"
 exit 1
fi

# Read needed entries from ispcp.conf
for a in `grep -E '(^Version|APACHE_|MTA_|ROOT_|^PHP_FASTCGI|^CMD_|^DEBUG)' $CONF_FILE | sed -e 's/ //g'`; do
    export $a
done

A2ENMOD=/usr/sbin/a2enmod
A2DISMOD=/usr/sbin/a2dismod
CMD_MD5=/usr/bin/md5sum
INSSERV="/sbin/insserv -d"

# List of service required by ispCP
SERVICES="$CMD_ISPCPN $CMD_ISPCPD fam $CMD_NAMED apache2 $CMD_FTPD postgrey policyd-weight $CMD_MTA $CMD_AUTHD $CMD_IMAP $CMD_IMAP_SSL $CMD_POP $CMD_POP_SSL mysql"

# Get ispCP version (not used at this moment)
#ISPCP_VERS=`echo $Version | sed -e 's/[A-Z]//g'`

# Get Dist release version (not used at this moment)
#DIST_VERS=`grep -E '^VERSION' /etc/SuSE-release | sed -e 's/[[:space:]=A-Z]//g'`

if [ $DEBUG -eq 1 ]; then
  echo "now debugging $0 $@"
  set -x
fi

case "$1" in

	configure)

	#
	## OpenSuSE firewall configuration - Begin
	#

	echo -e "\t\tOpenSuSE Firewall Configuration"

	[ -f /etc/init.d/SuSEfirewall2_setup ] && /etc/init.d/SuSEfirewall2_setup stop
	[ -f /sbin/yast2 ] && /sbin/yast2 firewall startup manual

	#
	## OpenSuSE firewall configuration - End
	#

	#
	## Apache2 Configuration - Begin
	#

	echo -e "\t\tApache Configuration Processing"

	if [ -f /usr/sbin/suexec2 ] ; then
		$CMD_CHOWN $ROOT_USER:$APACHE_GROUP /usr/sbin/suexec2
		$CMD_CHMOD 4755 /usr/sbin/suexec2
	fi

	#
	## Apache2 Configuration - End
	#

	#
	## FastCGI Apache module Configuration - Begin
	#

	echo -e "\t\tFastCGI module configuration"

	# Enable FastCGI module (fcgid|fascgi) and disable unused
	if [ ! -z "$PHP_FASTCGI" ] ; then
		if [ "$PHP_FASTCGI" == "fcgid" ]; then
			[ -x $A2ENMOD ] && $A2ENMOD $PHP_FASTCGI
			[ -x $A2DISMOD ] && $A2DISMOD fastcgi
		else
			[ -x $A2ENMOD ] && $A2ENMOD $PHP_FASTCGI
			[ -x $A2DISMOD ] && $A2DISMOD fcgid
		fi
	fi

	# Disable default FastCGI modules configuration files
	[ -f /etc/apache2/conf.d/mod_fastcgi.conf ] && $CMD_MV /etc/apache2/conf.d/mod_fastcgi.conf /etc/apache2/conf.d/mod_fastcgi.conf.disabled
	[ -f /etc/apache2/conf.d/mod_fcgid.conf ] && $CMD_MV /etc/apache2/conf.d/mod_fcgid.conf /etc/apache2/conf.d/mod_fcgid.conf.disabled

	#
	## FastCGI Apache module Configuration - Begin
	#

	#
	## PHP configuration - Begin
	#

	echo -e "\t\tPHP configuration"

	# Disable mod php5
	[ -x $A2DISMOD ] && $A2DISMOD php5

	#
	## PHP configuration - End
	#

	#
	## Postfix Configuration - Begin
	#

	echo "\t\tPostfix Configuration Processing"

	# Fix warning: "not owned by root: /var/spool/postfix"
	# This is because the postgrey package changes the
	# owner of this directory during installation (why ?)
	$CMD_CHOWN root:postfix /var/spool/postfix

	# Sasl postfix configuration
	if [ ! -f /etc/ispcp/postfix/backup/smtpd.conf.system -a \
	    -f /etc/sasl2/smtpd.conf ]; then
		$CMD_CP -a /etc/sasl2/smtpd.conf /etc/ispcp/postfix/backup/smtpd.conf.system
		$CMD_CHMOD 0600 /etc/ispcp/postfix/backup/smtpd.conf.system
	fi

	# First we build a new conffile with available smtpd.conf template
	($CMD_CAT /etc/ispcp/postfix/smtpd.conf) |
	$CMD_SED "
				s/{MTA_SASL_LOG_LEVEL}/$MTA_SASL_LOG_LEVEL/
				s/{MTA_SASL_PWCHECK_METHOD}/$MTA_SASL_PWCHECK_METHOD/
				s/{MTA_SASL_MECH_LIST}/$(echo $MTA_SASL_MECH_LIST | sed 's/,/ /g')/
	 " >/tmp/smtpd.conf.tmp

	if [ "$MTA_SASL_AUXPROP_PLUGIN" != "no" ]; then
		$CMD_SED -i "s/{MTA_SASL_AUXPROP_PLUGIN}/$MTA_SASL_AUXPROP_PLUGIN/" /tmp/smtpd.conf.tmp
	else
		$CMD_SED -i '/auxprop_plugin: {MTA_SASL_AUXPROP_PLUGIN}/d' /tmp/smtpd.conf.tmp
	fi

	# Update sasl configuration file if needed
	if [ -f "$MTA_SASL_CONF_FILE" ] ; then
		oldmd5=`$CMD_MD5 $MTA_SASL_CONF_FILE | cut -d' ' -f1`
		newmd5=`$CMD_MD5 /tmp/smtpd.conf.tmp | cut -d' ' -f1`
		if [ "$oldmd5" != "$newmd5" ]; then
			$CMD_CP -p /tmp/smtpd.conf.tmp /etc/ispcp/postfix/backup/smtpd.conf.ispcp
		fi
	fi

	$CMD_CP -p /etc/ispcp/postfix/backup/smtpd.conf.ispcp $MTA_SASL_CONF_FILE
	$CMD_CHMOD 0600 $MTA_SASL_CONF_FILE /etc/ispcp/postfix/backup/smtpd.conf.ispcp

	#
	## Postfix Configuration - End
	#

	#
	## Postgrey Configuration - Begin
	#

	echo -e "\t\tPostgrey Configuration Processing"

	if [ -f /etc/sysconfig/postgrey ] ; then
		$CMD_SED -i 's/#POSTGREY_CONN_OPTIONS="--inet=127.0.0.1:10031"/POSTGREY_CONN_OPTIONS="--inet=127.0.0.1:60000"/' /etc/sysconfig/postgrey
		$CMD_SED -i 's/POSTGREY_CONN_OPTIONS="--unix=\/var\/spool\/postfix\/postgrey\/socket"/#POSTGREY_CONN_OPTIONS="--unix=\/var\/spool\/postfix\/postgrey\/socket"/' /etc/sysconfig/postgrey
	fi

	#
	## Postgrey Configuration - End
	#

	# 
	## Rkhunter - Begin
	# 

	echo -e "\t\tBuilding rkhunter database (Background process)" 

	/usr/bin/rkhunter --propupd &

	# 
	## Rkhunter - End
	# 

	#
	## Courier-Authentication Configuration - Begin
	#

	echo -e "\t\tCourier-Authentication Configuration Processing"

	# Prevent authdaemon warnings related to missing modules in mail log files
	if [ -f /etc/authlib/authdaemonrc ] ; then
		$CMD_SED -i 's/authmodulelist="authuserdb authuserdb authpam authpgsql authldap authmysql authcustom authpipe"/authmodulelist="authuserdb authpam authcustom"/' /etc/authlib/authdaemonrc
	fi

	#
	## Courier-Authentication Configuration - End
	#

	#
	## System Init Configuration - Begin
	#

	echo -e "\t\tSystem Init configuration"

	# Enable all system init scripts needed by ispCP
	for service in $SERVICES ; do
		if [ -x "/etc/init.d/$service" ]; then
			$INSSERV $service ||true
		fi
	done

	#
	## System Init Configuration - End
	#
	;;
	*)
	exit 0
	;;
esac

exit 0
