#!/bin/sh
# fcgi starter configuration file - auto-generated by i-MSCP
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
umask 027
export PHPRC={FCGI_DIR}/php{PHP_VERSION}/
export PHP_FCGI_MAX_REQUESTS={PHP_FCGI_MAX_REQUESTS}
export PHP_FCGI_CHILDREN={PHP_FCGI_CHILDREN}
export TMPDIR={TMPDIR}
exec {PHP_CGI_BIN} "$@"
