#!/usr/bin/make -f
#
# ispCP ? (OMEGA) a Virtual Hosting Control Panel
# Copyright (c) 2001-2006 by moleSoftware GmbH
# http://www.molesoftware.com
# Copyright (c) 2006-2008 by isp Control Panel
# http://isp-control.net
#
#
# License:
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of the MPL Mozilla Public License
#    as published by the Free Software Foundation; either version 1.1
#    of the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    MPL Mozilla Public License for more details.
#
#    You may have received a copy of the MPL Mozilla Public License
#    along with this program.
#
#    An on-line copy of the MPL Mozilla Public License can be found
#    http://www.mozilla.org/MPL/MPL-1.1.html
#
#
# The ispCP ? Home Page is at:
#
#    http://isp-control.net
#

.include <../../../../Makefile.inc>

APACHE_EXT_CONF=$(INST_PREF)/var/www/conf
APACHE_MOD_CONF=$(INST_PREF)/usr/local/etc/apache22/extra/
install:

	$(SYSTEM_MAKE_DIRS) $(SYSTEM_CONF)/apache
	$(SYSTEM_MAKE_DIRS) $(APACHE_EXT_CONF)
	$(SYSTEM_MAKE_DIRS) $(APACHE_MOD_CONF)
	$(SYSTEM_MAKE_DIRS) $(ROOT_APACHE_CONF)/ispcp

	cp ./httpd.conf ./working/ispcp.conf
	cp ./fastcgi.conf ./working/fastcgi_ispcp.conf
	cp ./00_master.conf $(SYSTEM_CONF)/apache
	cp ./httpd.conf $(SYSTEM_CONF)/apache
	cp -R ./backup $(SYSTEM_CONF)/apache
	cp -R ./parts $(SYSTEM_CONF)/apache
	cp -R ./working $(SYSTEM_CONF)/apache
	cp -R ./httpd.conf $(APACHE_EXT_CONF)/ispcp.conf
	cp -R ./fastcgi.conf $(APACHE_MOD_CONF)/fastcgi_ispcp.conf

uninstall:

	rm -rf $(SYSTEM_CONF)/apache
	rm -rf $(ROOT_APACHE_CONF)/ispcp.conf
	rm -rf $(APACHE_MOD_CONF)/fastcgi_ispcp.conf
