# vlogger configuration file - auto-generated by i-MSCP
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
dsn    {DSN}
user   {DATABASE_USER}
pass   {DATABASE_PASSWORD}
dump   30
