// bind9 configuration file - auto-generated by i-MSCP
//     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
zone "{DOMAIN_NAME}" {
  type master;
  file "{DB_DIR}/{DOMAIN_NAME}.db";
  allow-transfer { {SECONDARY_DNS} };
  notify yes;
};
