// bind9 configuration file - auto-generated by i-MSCP
//     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
zone "{DOMAIN_NAME}" {
  type slave;
  file "{DB_DIR}/slave/{DOMAIN_NAME}.db";
  masters { {PRIMARY_DNS} };
};
