.include <../../../../Makefile.inc>

install:

	$(SYSTEM_MAKE_DIRS) $(ROOT_CONF)/init.d
        
	cp vhcs2_daemon $(ROOT_CONF)/vhcs2_daemon.rc
	cp vhcs2_network $(ROOT_CONF)/vhcs2_network.rc

	chown root:wheel $(ROOT_CONF)/vhcs2_network.rc $(ROOT_CONF)/vhcs2_daemon.rc
	chmod 0755 $(ROOT_CONF)/vhcs2_network.rc $(ROOT_CONF)/vhcs2_daemon.rc
        
uninstall:

	rm -f $(ROOT_CONF)/vhcs2_daemon.rc
	rm -f $(ROOT_CONF)/vhcs2_network.rc

