#!/usr/bin/perl

# i-MSCP - internet Multi Server Control Panel
# Copyright (C) 2010-2016 by Laurent Declercq <l.declercq@nuxwin.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

=head1 NAME

imscp-reconfigure Reconfigure i-MSCP

=head1 SYNOPSIS

 imscp-reconfigure [options]...

=cut

use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/..", "$FindBin::Bin/../PerlLib", "$FindBin::Bin/../PerlVendor";
use iMSCP::Debug;
use iMSCP::Dialog;
use iMSCP::EventManager;
use iMSCP::Getopt;
use File::Basename;
use POSIX qw(locale_h);
use locale;

setlocale(LC_ALL, 'C.UTF-8');
$ENV{'LANG'} = 'C.UTF-8';

newDebug('imscp-setup.log');

# Set backend mode
$main::execmode = 'setup' unless $main::execmode;

# Init variable that holds questions
%main::questions = () unless %main::questions;

# Parse command line options
iMSCP::Getopt->parse(sprintf('Usage: perl %s [OPTION]...', basename($0)));

# Set debug and verbose mode
setDebug(iMSCP::Getopt->debug);
setVerbose(iMSCP::Getopt->noprompt && iMSCP::Getopt->verbose);

# Get reconfigure option
$main::reconfigure = iMSCP::Getopt->reconfigure;

# Handle preseed option
if(iMSCP::Getopt->preseed) {
    require iMSCP::Getopt->preseed;
    # The preseed option supersede the reconfigure option
    iMSCP::Getopt->reconfigure('none');
    $main::reconfigure = 'none';
    iMSCP::Getopt->noprompt(1);
}


# Handle the listener option
require iMSCP::Getopt->listener if iMSCP::Getopt->listener;

# handle noprompt option
if(iMSCP::Getopt->noprompt) {
    debugRegisterCallBack(sub {
        print STDOUT output('i-MSCP has been successfully installed/updated.', 'ok') unless $?;

        # We exit with status 5 from iMSCP::Dialog in noninteractive mode
        if($? == 5) {
            if(iMSCP::Getopt->preseed) {
                print STDERR output('Missing or bad entry found in your preseed file.', 'fatal');
            } else {
                print STDERR output('Missing or bad entry found in configuration file.', 'fatal');
            }
        }
    });

    print STDOUT output('Installation in progress... Please wait.', 'info');
}

sub run
{
    require "$FindBin::Bin/imscp-setup-methods.pl";

    my $rs = setupBoot();
    $rs ||= iMSCP::EventManager->getInstance()->trigger('beforeSetup');
    $rs ||= setupRegisterListeners();
    return $rs if $rs;

    unless(iMSCP::Getopt->noprompt) {
        my $distribution = ucfirst(lc(iMSCP::LsbRelease->getInstance()->getId( 'short' )));
        my $dialog = iMSCP::Dialog->getInstance();

        $dialog->set('title', 'i-MSCP Reconfiguration Dialog');

        exit 0 if $dialog->yesno(<<"EOF", 1);

Welcome to the \\Z1i-MSCP $main::imscpConfig{'Version'}\\Zn reconfiguration dialog.

This program will reconfigure i-MSCP on your system.

During the process some or all services might require to be shutdown or restarted.

Do you want to continue?
EOF

        $dialog->resetLabels();
    }

    $rs ||= setupDialog();
    $rs = setupTasks();
    $rs ||= iMSCP::EventManager->getInstance()->trigger('afterSetup');
    return $rs if $rs || iMSCP::Getopt->noprompt;

    my $port = ($main::imscpConfig{'BASE_SERVER_VHOST_PREFIX'} eq 'http://')
        ? $main::imscpConfig{'BASE_SERVER_VHOST_HTTP_PORT'}
        : $main::imscpConfig{'BASE_SERVER_VHOST_HTTPS_PORT'};

        iMSCP::Dialog->getInstance()->infobox(<<EOF);

\\Z1Congratulations\\Zn

i-MSCP has been successfully reconfigured.

Please connect to $main::imscpConfig{'BASE_SERVER_VHOST_PREFIX'}$main::imscpConfig{'BASE_SERVER_VHOST'}:$port and login with your administrator account.

Thank you for choosing i-MSCP.
EOF

    0;
}

exit run();

=head1 AUTHOR

Laurent Declercq <l.declercq@nuxwin.com>

=cut
