#!/usr/bin/perl

# i-MSCP - internet Multi Server Control Panel
# Copyright (C) 2010 - 2011 by internet Multi Server Control Panel
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# @category		i-MSCP
# @copyright	2010 - 2011 by i-MSCP | http://i-mscp.net
# @author		Daniel Andreca <sci2tech@gmail.com>
# @version		SVN: $Id$
# @link			http://i-mscp.net i-MSCP Home Site
# @license		http://www.gnu.org/licenses/gpl-2.0.html GPL v2

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/..";
use lib "$FindBin::Bin/../PerlLib";
use lib "$FindBin::Bin/../PerlVendor";

use iMSCP::Debug;
use iMSCP::Boot;
use iMSCP::Dialog;

iMSCP::Debug->newDebug('imscp-setup.log');

require "$FindBin::Bin/imscp-setup-methods.pl";

################################################################################
# Shutting down setup process
#
# @return int 0 on success, other on failure
#
sub setup_shut_down {

	debug((caller(0))[3].': Starting...');

	iMSCP::Dialog->factory()->msgbox(
					"\n
					\\Z1Congratulations!!!\\Zn

					You installed i-MSCP '$main::imscpConfig{'Version'}' successfully!\n\n

					Please type $main::imscpConfig{'BASE_SERVER_VHOST_PREFIX'}$main::imscpConfig{'BASE_SERVER_VHOST'} in your browser and log in with your Administrator Account to use i-MSCP."
	);

	debug((caller(0))[3].': Ending...');

	0;
}

################################################################################
#                                Main program                                  #
################################################################################

setup_start_up() and exit 1;
setup_engine() and exit 1;
setup_shut_down() and exit 1;

exit 0;

END{
	execute('clear');

	my @warnings	= getMessageByType('WARNING');
	my @errors		= getMessageByType('ERROR');
	my @fatals		= getMessageByType('FATAL ERROR');

	my $msg	 = "\nWARNINGS:\n"		. join("\n", @warnings)	. "\n" if @warnings > 0;
	$msg	.= "\nERRORS:\n"		. join("\n", @errors)	. "\n" if @errors > 0;
	$msg	.= "\nFATAL ERRORS:\n"	. join("\n", @fatals)	. "\n" if @fatals > 0;

	my $message = getMessage();

	iMSCP::Debug->newDebug('discard');

	if($main::imscpConfig{LOG_DIR} && -d $main::imscpConfig{LOG_DIR}){
		open(F, '>', "$main::imscpConfig{'LOG_DIR'}/imscp-setup.log") or fatal("Error: Can't open file '$main::imscpConfig{'LOG_DIR'}/imscp-setup.log' for writing: $!");
		print F $message;
		close F;
		print STDOUT "\nA log file with details can be found at: $main::imscpConfig{'LOG_DIR'}/imscp-setup.log\n";
	}
	print STDERR $msg if $msg;
}
