#!/usr/bin/perl

# ispCP ω (OMEGA) a Virtual Hosting Control Panel
# Copyright (c) 2001-2006 by moleSoftware GmbH
# http://www.molesoftware.com
# Copyright (c) 2006-2009 by isp Control Panel
# http://isp-control.net
#
#
# License:
#	This program is free software; you can redistribute it and/or
#	modify it under the terms of the MPL Mozilla Public License
#	as published by the Free Software Foundation; either version 1.1
#	of the License, or (at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	MPL Mozilla Public License for more details.
#
#	You may have received a copy of the MPL Mozilla Public License
#	along with this program.
#
#	An on-line copy of the MPL Mozilla Public License can be found
#	http://www.mozilla.org/MPL/MPL-1.1.html
#
#
# The ispCP ω Home Page is at:
#
#	http://isp-control.net
#

use FindBin;
use lib "$FindBin::Bin/..";
require 'ispcp_common_code.pl';

use strict;
use warnings;

sub welcome_note {

	my $rdata = undef;

	push_el(\@main::el, 'welcome_note()', 'Starting...');

	my $welcome_message = "\n".
	"\n".
   " Welcome in ISPCP OMEGA '$main::cfg{'Version'}' Uninstall Program.\n".
	"\n".
	"This program will uninstall ispCP OMEGA system from your server.\n".
	"\n".
	"/!\\ WARNING: All domain users and their accounts will be removed.  /!\\\n".
	"\n".
	"Please press 'Enter' to continue.\n";


	print STDOUT $welcome_message;

	$rdata = readline(\*STDIN);

	push_el(\@main::el, 'welcome_note()', 'Ending...');

	return 0;

}

sub ask_remove_user_data {

	my ($rs, $rdata) = (undef, undef);

	push_el(\@main::el, 'ask_remove_user_data()', 'Starting...');

	my $qmsg = "\n\tRemove user data? [no]: ";

	print STDOUT $qmsg;

	$rdata = readline(\*STDIN);

	chomp($rdata);

	if ($rdata eq 'yes' || $rdata eq 'y') {
		$main::rm{'rm_u_data'} = 'yes';
	}
	else {
		$main::rm{'rm_u_data'} = 'no';
	}

	push_el(\@main::el, 'ask_remove_user_data()', 'Ending...');

	return 0;

}

sub user_dialog {

	my $rs = undef;

	push_el(\@main::el, 'user_dialog()', 'Starting...');

	$rs = welcome_note();
	return $rs if($rs != 0);

	$rs = ask_remove_user_data();
	return $rs if($rs != 0);

	push_el(\@main::el, 'user_dialog()', 'Ending...');

	return 0;

}

sub uninstall_start_up {

	my $rs = undef;

	push_el(\@main::el, 'uninstall_start_up()', 'Starting...');

	# config check;

	$rs = get_conf();
	return $rs if ($rs != 0);

	if (-e "/tmp/ispcp-uninstall-services.log"){
		$rs = del_file("/tmp/ispcp-uninstall-services.log");
		return $rs if ($rs != 0);
	}

	push_el(\@main::el, 'uninstall_start_up()', 'Ending...');

	return 0;

}

sub uninstall_shut_down {

	my ($rs, $rdata) = (undef, undef);

	push_el(\@main::el, 'uninstall_shut_down()', 'Starting...');

	my $shut_down_message = "\n".
	"\n".
	"Congratulations !\n".
	"\n".
	"ISPCP OMEGA '$main::cfg{'Version'}' uninstall completed successfully !\n".
	"\n".
	"Thank you for using ISPCP OMEGA product !\n";

	print STDOUT $shut_down_message;

	push_el(\@main::el, 'uninstall_shut_down()', 'Ending...');

	return 0;

}

sub remove_sql_users{
	my ($rs, $rdata) = (undef, undef);

	push_el(\@main::el, 'remove_sql_users()', 'Starting...');

	my $sql = "select distinct(sqlu_name) from sql_user";

	($rs, $rdata) = doSQL($sql);
	if($rs != 0){
		print "Can not obtain sql user list!!!\n\n";
		send_error_mail('remove_sql_db()', "Can not obtain sql user list!!!");
	}

	my $sql_count = @$rdata;

	if ($sql_count > 0) {

		foreach (@$rdata) {

			my $row = $_;
			my $sqlu_name = @$row[0];

			$sql = "DROP USER '$sqlu_name'\@'localhost'";
			($rs, $rdata) = doSQL($sql);
			if($rs != 0){
				print "Can not remove sql user '$sqlu_name'\@localhost!!!\n\n";
				send_error_mail('remove_sql_db()', "Can not remove sql user '$sqlu_name'\@localhost!!!");
			}


			$sql = "DROP USER '$sqlu_name'\@'%'";
			($rs, $rdata) = doSQL($sql);
			if($rs != 0){
				print "Can not remove sql user '$sqlu_name'\@%!!!\n\n";
				send_error_mail('remove_sql_db()', "Can not remove sql user '$sqlu_name'\@%!!!");
			}

		}

	}

	push_el(\@main::el, 'remove_sql_users()', 'Ending...');

	return 0;
}

sub remove_sql_db{
	my ($rs, $rdata) = (undef, undef);

	push_el(\@main::el, 'remove_sql_db()', 'Starting...');

	my $sql = "select distinct(sqld_name) from sql_database";

	($rs, $rdata) = doSQL($sql);

	my $sql_count = @$rdata;

	if ($sql_count > 0) {

		foreach (@$rdata) {

			my $row = $_;
			my $sqld_name = @$row[0];

			$sql = "DROP DATABASE IF EXISTS $sqld_name;";
			($rs, $rdata) = doSQL($sql);
			if($rs != 0){
				print "Can not remove database $sqld_name!!\n\n";
				send_error_mail('remove_sql_db()', "Can not remove database $sqld_name!!!");
			}
		}

	}

	push_el(\@main::el, 'remove_sql_db()', 'Ending...');

	return 0;
}

sub uninstall_system_users {

	my ($rs, $rdata, $rows, $sql) = (undef, undef, undef, undef);

	push_el(\@main::el, 'uninstall_system_users()', 'Starting...');

	my ($fuid, $fgid) = ($main::cfg{'MTA_MAILBOX_UID_NAME'}, $main::cfg{'MTA_MAILBOX_GID_NAME'});

	my ($muid, $mgid) = ($main::cfg{'APACHE_SUEXEC_MIN_UID'}, $main::cfg{'APACHE_SUEXEC_MIN_GID'});

	my ($upref) = ($main::cfg{'APACHE_SUEXEC_USER_PREF'});

	my ($uid, $gid) = (undef, undef);


	my @udata = ();

	my @gdata = ();

	#
	# MTA Mailbox User
	#
	@udata = getpwnam($fuid);
	@gdata = getgrnam($fgid);

	if (scalar(@udata) != 0) { # we have not this one user data;

		my $cmd = "$main::cfg{'CMD_USERDEL'} $fuid";

		$rs = sys_command($cmd);
		if($rs != 0){
			print "Can not remove  user '$fuid'!!!\n\n";
			send_error_mail('uninstall_system_users()', "Can not remove  user '$fuid'!!!");
		}

	}

	if (scalar(@gdata) != 0) { # we have not this one group data;

		my $cmd = "$main::cfg{'CMD_GROUPDEL'} $fgid";

		$rs = sys_command($cmd);
		if($rs != 0){
			print "Can not remove  group '$fgid'!!!\n\n";
			send_error_mail('uninstall_system_users()', "Can not remove  group '$fgid'!!!");
		}

	}

	#
	# PHP Master
	#

	@udata = getpwnam("$upref$muid");

	if (scalar(@udata) != 0) { # we have not this one user data;

		my $cmd = "$main::cfg{'CMD_USERDEL'} $upref$muid";

		$rs = sys_command($cmd);
		if($rs != 0){
			print "Can not remove  user '$fuid'!!!\n\n";
			send_error_mail('uninstall_system_users()', "Can not remove  user '$fuid'!!!");
		}

	}

	@gdata = getgrnam("$upref$mgid");

	if (scalar(@gdata) != 0) { # we have not this one group data;

		my $cmd = "$main::cfg{'CMD_GROUPDEL'} $upref$mgid";

		$rs = sys_command($cmd);
		if($rs != 0){;
			print "Can not remove  group '$upref$mgid'!!!\n\n";
			send_error_mail('uninstall_system_users()', "Can not remove  group '$upref$mgid'!!!");
		}

	}

	#
	# Virtual User
	#

	$sql = "select domain_uid,domain_gid from domain";

	($rs, $rows) = doSQL($sql);
	if ($rs != 0){
		print "Can not obtain user list!!!\n\n";
		send_error_mail('uninstall_system_users()', "Can not obtain user list!!!");
		return 0;
	}

	if (scalar(@$rows) != 0) {

		foreach (@$rows) {

			my $query_user = $_;

			@udata = getpwnam("$upref@$query_user[0]");

			if (scalar(@udata) != 0) { # we have not this one user data;

				my $cmd = "$main::cfg{'CMD_USERDEL'} $upref@$query_user[0]";

				$rs = sys_command($cmd);
				if($rs != 0){
					print "Can not remove  user '{$upref@$query_user[0]}'!!!\n\n";
					send_error_mail('uninstall_system_users()', "Can not remove  user '{$upref@$query_user[0]}'!!!");
				}

			}

			@gdata = getgrnam("$upref@$query_user[1]");

			if (scalar(@gdata) != 0) { # we have not this one group data;

				my $cmd = "$main::cfg{'CMD_GROUPDEL'} $upref@$query_user[0]";

				$rs = sys_command($cmd);
				if($rs != 0){
					print "Can not remove  group '{upref@$query_user[0]}'!!!\nYou must remove it manually\n";
					send_error_mail('uninstall_system_users()', "Can not remove  group '{$upref@$query_user[0]}'!!!");
				}

			}

		}

	}


	push_el(\@main::el, 'uninstall_system_users()', 'Ending...');
	return 0;

}

sub uninstall_system_dirs {

	my ($rs, $rdata) = (undef, undef);

	push_el(\@main::el, 'uninstall_system_dirs()', 'Starting...');

	if ($main::rm{'rm_u_data'} eq 'yes') {
		$rs = del_dir($main::cfg{'APACHE_WWW_DIR'});
		if ($rs != 0){
			print "Can not delete folder ".$main::cfg{'APACHE_WWW_DIR'}."!!!\n\n";
			send_error_mail('uninstall_system_dirs()', "Can not delete folder ".$main::cfg{'APACHE_WWW_DIR'}."!!!");
		}
	}

	$rs = del_dir($main::cfg{'APACHE_USERS_LOG_DIR'});
	if ($rs != 0){
		print "Can not delete folder ".$main::cfg{'APACHE_USERS_LOG_DIR'}."!!!\n\n";
		send_error_mail('uninstall_system_dirs()', "Can not delete folder ".$main::cfg{'APACHE_USERS_LOG_DIR'}."!!!");
	}

	$rs = del_dir($main::cfg{'APACHE_BACKUP_LOG_DIR'});
	if ($rs != 0){
		print "Can not delete folder ".$main::cfg{'APACHE_BACKUP_LOG_DIR'}."!!!\n\n";
		send_error_mail('uninstall_system_dirs()', "Can not delete folder ".$main::cfg{'APACHE_BACKUP_LOG_DIR'}."!!!");
	}

	$rs = del_dir($main::cfg{'MTA_VIRTUAL_CONF_DIR'});
	if ($rs != 0){
		print "Can not delete folder ".$main::cfg{'MTA_VIRTUAL_CONF_DIR'}."!!!\n\n";
		send_error_mail('uninstall_system_dirs()', "Can not delete folder ".$main::cfg{'MTA_VIRTUAL_CONF_DIR'}."!!!");
	}

	if ($main::rm{'rm_u_data'} eq 'yes') {
		$rs = del_dir($main::cfg{'MTA_VIRTUAL_MAIL_DIR'});
		if ($rs != 0){
			print "Can not delete folder ".$main::cfg{'MTA_VIRTUAL_MAIL_DIR'}."!!!\n\n";
			send_error_mail('uninstall_system_dirs()', "Can not delete folder ".$main::cfg{'MTA_VIRTUAL_MAIL_DIR'}."!!!");
		}
	}

	$rs = del_dir($main::cfg{'LOG_DIR'});
	if ($rs != 0){
		print "Can not delete folder ".$main::cfg{'LOG_DIR'}."!!!\n\n";
		send_error_mail('uninstall_system_dirs()', "Can not delete folder ".$main::cfg{'LOG_DIR'}."!!!");
	}

	$rs = del_dir($main::cfg{'PHP_STARTER_DIR'});
	if ($rs != 0){
		print "Can not delete folder ".$main::cfg{'PHP_STARTER_DIR'}."!!!\n\n";
		send_error_mail('uninstall_system_dirs()', "Can not delete folder ".$main::cfg{'PHP_STARTER_DIR'}."!!!");
	}

	push_el(\@main::el, 'uninstall_system_dirs()', 'Ending...');

	return 0;
}

sub uninstall_sql {

	my ($rs, $rdata) = (undef, undef);

	push_el(\@main::el, 'uninstall_sql()', 'Starting...');

	$rs = remove_sql_users();
	$rs = remove_sql_db();

	#
	# check for existing database;
	#

	my $sql = "show tables;";

	($rs, $rdata) = doSQL($sql);

	if ($rs == 0) { # Yes, we have one ! Let's drop it;

		my $store_db_name = $main::db_name;


		# Let's reset data;


		$main::db = undef;

		$main::db_name = '';

		@main::db_connect = (
							 "DBI:mysql:$main::db_name:$main::db_host",
							 $main::db_user,
							 $main::db_pwd
							);

		$sql = "drop database $store_db_name;";

		($rs, $rdata) = doSQL($sql);
		if ($rs != 0){
			print "Can not delete database $store_db_name!!!\n\n";
			send_error_mail('uninstall_sql()', "Can not delete database $store_db_name!!!");
		}


		# Let's reset data;


		$main::db = undef;

		$main::db_name = $store_db_name;

		@main::db_connect = (
							 "DBI:mysql:$main::db_name:$main::db_host",
							 $main::db_user,
							 $main::db_pwd
							);

	}

	push_el(\@main::el, 'uninstall_sql()', 'Ending...');

	return 0;

}

sub uninstall_crontab {

	my $rs = undef;

	push_el(\@main::el, 'uninstall_crontab()', 'Starting...');

	if ( -e "/etc/cron.d/ispcp") {
		$rs = del_file("/etc/cron.d/ispcp");
		if ($rs != 0){;
			print "Can not delete file /etc/cron.d/ispcp!!!\n\n";
			send_error_mail('uninstall_crontab()', "Can not delete file /etc/cron.d/ispcp!!!");
		}
	} else {
		print "File /etc/cron.d/ispcp do not exists!";
	}

	push_el(\@main::el, 'uninstall_crontab()', 'Ending...');

	return 0;

}

sub uninstall_resolver {

	push_el(\@main::el, 'uninstall_resolver()', 'Starting...');

	my $resolv_file = "/etc/resolv.conf";

	my ($rs, $cmd) = (undef, undef);

	if ( -e "$resolv_file.bkp" ) {

		$cmd = "$main::cfg{'CMD_MV'} $resolv_file.bkp $resolv_file";

		$rs = sys_command_rs($cmd);
		if ($rs != 0){
			print "Can not move file $resolv_file.bkp into $resolv_file!!!\n\n";
			send_error_mail('uninstall_resolver()', "Can not move file $resolv_file.bkp into $resolv_file!!!");
		}
	} else {
		print "File $resolv_file.bkp do not exits. File is not restored!!!\n\n";
	}

	push_el(\@main::el, 'uninstall_resolver()', 'Ending...');

	return 0;

}

sub uninstall_logrotate {

	push_el(\@main::el, 'uninstall_logrotate()', 'Starting...');

	my ($rs, $cmd) = (undef, undef);

	my $logrotate_d = "/etc/logrotate.d";

	if ( -e "$logrotate_d/ispcp" ) {

		$rs = del_file("$logrotate_d/ispcp");
		if ($rs != 0){
			print "Can not delete $logrotate_d/ispcp!!!\n\n";
			send_error_mail('uninstall_resolver()', "Can not delete $logrotate_d/ispcp!!!");
		}
	} else {
		print "File $logrotate_d/ispcp do not exits!!!\n\n";
	}

	push_el(\@main::el, 'uninstall_logrotate()', 'Ending...');

	return 0;

}

sub uninstall_named {

	my ($rs, $rdata) = (undef, undef);

	push_el(\@main::el, 'uninstall_named()', 'Starting...');

	my $cfg_dir = "$main::cfg{'CONF_DIR'}/bind";

	my $bk_dir = "$cfg_dir/backup";

	my $wrk_dir = "$cfg_dir/working";

	my ($cfg_tpl, $cfg, $cmd) = (undef, undef, undef);

	sys_command_rs("$main::cfg{'CMD_NAMED'} stop >> /tmp/ispcp-uninstall-services.log");

	if (-e "$bk_dir/named.conf.system") {

		$cmd = "$main::cfg{'CMD_CP'} -p $bk_dir/named.conf.system $main::cfg{'BIND_CONF_FILE'}";

		$rs = sys_command($cmd);
		if ($rs != 0){
			print "File $bk_dir/named.conf.system can not be restored\n\n";
			send_error_mail('uninstall_named()', "File $bk_dir/named.conf.system can not be restored");
		}

	} else {
		print "Backup files $bk_dir/named.conf.system can not be founded\n";
		send_error_mail('uninstall_ftpd()', "Backup files $bk_dir/named.conf.system can not be founded!!!");
	}

	sys_command_rs("$main::cfg{'CMD_NAMED'} start >> /tmp/ispcp-uninstall-services.log");

	push_el(\@main::el, 'uninstall_named()', 'Ending...');

	return 0;

}

sub uninstall_httpd {

	my ($rs, $rdata) = (undef, undef);

	push_el(\@main::el, 'uninstall_httpd()', 'Starting...');

	my $cfg_dir = "$main::cfg{'CONF_DIR'}/apache";

	my $bk_dir = "$cfg_dir/backup";

	my $wrk_dir = "$cfg_dir/working";

	my ($cfg_tpl, $cfg, $cmd) = (undef, undef, undef);

	sys_command_rs("$main::cfg{'CMD_HTTPD'} stop >> /tmp/ispcp-uninstall-services.log");

	sys_command_rs("a2dissite ispcp.conf >> /tmp/ispcp-uninstall-services.log");

	$rs = del_file("$main::cfg{'APACHE_SITES_DIR'}/ispcp.conf");
	if ($rs != 0){
		print "Can not delete $main::cfg{'APACHE_SITES_DIR'}/ispcp.conf!!!\n\n";
		send_error_mail('uninstall_httpd()', "Can not delete $main::cfg{'APACHE_SITES_DIR'}/ispcp.conf!!!");
	}

	sys_command_rs("a2dissite 00_master.conf >> /tmp/ispcp-uninstall-services.log");

	$rs = del_file("$main::cfg{'APACHE_SITES_DIR'}/00_master.conf");
	if ($rs != 0){
		print "Can not delete $main::cfg{'APACHE_SITES_DIR'}/00_master.conf!!!\n\n";
		send_error_mail('uninstall_httpd()', "Can not delete $main::cfg{'APACHE_SITES_DIR'}/00_master.conf!!!");
	}

	sys_command_rs("a2dismod fastcgi_ispcp >> /tmp/ispcp-uninstall-services.log");

	$rs = del_file("$main::cfg{'APACHE_MODS_DIR'}/fastcgi_ispcp.conf");
	if ($rs != 0){
		print "Can not delete $main::cfg{'APACHE_MODS_DIR'}/fastcgi_ispcp.conf!!!\n\n";
		send_error_mail('uninstall_httpd()', "Can not delete $main::cfg{'APACHE_MODS_DIR'}/fastcgi_ispcp.conf!!!");
	}

	sys_command_rs("a2dismod fcgid_ispcp >> /tmp/ispcp-uninstall-services.log");

	$rs = del_file("$main::cfg{'APACHE_MODS_DIR'}/fcgid_ispcp.conf");
	if ($rs != 0){
		print "Can not delete $main::cfg{'APACHE_MODS_DIR'}/fcgid_ispcp.conf!!!\n\n";
		send_error_mail('uninstall_httpd()', "Can not delete $main::cfg{'APACHE_MODS_DIR'}/fcgid_ispcp.conf!!!");
	}

	if ( -e "$main::cfg{'APACHE_MODS_DIR'}/fastcgi_ispcp.load") {
		$rs = del_file("$main::cfg{'APACHE_MODS_DIR'}/fastcgi_ispcp.load");
		if ($rs != 0){
			print "Can not delete $main::cfg{'APACHE_MODS_DIR'}/fastcgi_ispcp.load!!!\n\n";
			send_error_mail('uninstall_httpd()', "Can not delete $main::cfg{'APACHE_MODS_DIR'}/fastcgi_ispcp.load!!!");
		}
	} else {
		print "File $main::cfg{'APACHE_MODS_DIR'}/fastcgi_ispcp.load do not exits!!!\n\n";
	}

	if ( -e "$main::cfg{'APACHE_MODS_DIR'}/fcgid_ispcp.load") {
		$rs = del_file("$main::cfg{'APACHE_MODS_DIR'}/fcgid_ispcp.load");
		if ($rs != 0){
			print "Can not delete $main::cfg{'APACHE_MODS_DIR'}/fcgid_ispcp.load!!!\n\n";
			send_error_mail('uninstall_httpd()', "Can not delete $main::cfg{'APACHE_MODS_DIR'}/fcgid_ispcp.load!!!");
		}
	} else {
		print "File $main::cfg{'APACHE_MODS_DIR'}/fcgid_ispcp.load do not exits!!!\n\n";
	}

	sys_command_rs("a2dissite 01_awstats.conf >> /tmp/ispcp-uninstall-services.log");

	if ( -e "$main::cfg{'APACHE_SITES_DIR'}/01_awstats.conf") {
		$rs = del_file("$main::cfg{'APACHE_SITES_DIR'}/01_awstats.conf");
		if ($rs != 0){
			print "Can not delete $main::cfg{'APACHE_SITES_DIR'}/01_awstats.conf!!!\n\n";
			send_error_mail('uninstall_httpd()', "Can not delete $main::cfg{'APACHE_MODS_DIR'}/01_awstats.conf!!!");
		}
	} elsif($main::cfg{'APACHE_SITES_DIR'} eq 'yes' && $main::cfg{'AWSTATS_MODE'} == 0) {
		print "File $main::cfg{'APACHE_SITES_DIR'}/01_awstats.conf do not exits!!!\n\n";
	}

	$rs = del_dir($main::cfg{'APACHE_CUSTOM_SITES_CONFIG_DIR'});
	if ($rs != 0){
		print "Folder $main::cfg{'APACHE_CUSTOM_SITES_CONFIG_DIR'} can not be deleted\n\n";
		send_error_mail('uninstall_httpd()', "Folder $main::cfg{'APACHE_CUSTOM_SITES_CONFIG_DIR'} can not be deleted");
	}

	sleep(5);

	sys_command_rs("$main::cfg{'CMD_HTTPD'} start >> /tmp/ispcp-uninstall-services.log");

	push_el(\@main::el, 'uninstall_httpd()', 'Ending...');

	return 0;

}

sub uninstall_mta {

	my ($rs, $rdata) = (undef, undef);

	push_el(\@main::el, 'uninstall_mta()', 'Starting...');

	my $cfg_dir = "$main::cfg{'CONF_DIR'}/postfix";

	my $bk_dir = "$cfg_dir/backup";

	my $wrk_dir = "$cfg_dir/working";

	my $vrl_dir = "$cfg_dir/ispcp";

	my ($cfg_tpl, $cfg, $cmd) = (undef, undef, undef);

	sys_command_rs("$main::cfg{'CMD_MTA'} stop >> /tmp/ispcp-uninstall-services.log");

	if (-e "$bk_dir/main.cf.system") {

		$cmd = "$main::cfg{'CMD_CP'} -p $bk_dir/main.cf.system $main::cfg{'POSTFIX_CONF_FILE'}";

		$rs = sys_command($cmd);
		if ($rs != 0){
			print "Can not move $bk_dir/main.cf.system into $main::cfg{'POSTFIX_CONF_FILE'}!!!\n\n";
			send_error_mail('uninstall_mta()', "Can not move $bk_dir/main.cf.system into $main::cfg{'POSTFIX_CONF_FILE'}!!!");
		}

		$cmd = "$main::cfg{'CMD_CP'} -p $bk_dir/master.cf.system $main::cfg{'POSTFIX_MASTER_CONF_FILE'}";

		$rs = sys_command($cmd);
		if ($rs != 0){
			print "Can not move $bk_dir/master.cf.system into $main::cfg{'POSTFIX_MASTER_CONF_FILE'}!!!\n\n";
			send_error_mail('uninstall_mta()', "Can not move $bk_dir/master.cf.system into $main::cfg{'POSTFIX_MASTER_CONF_FILE'}!!!");
		}

	} else {
		print "Backup files for MTA can not be founded\n";
		send_error_mail('uninstall_mta()', "Backup files for MTA can not be founded!!!");
	}

	if ( -e "/var/spool/postfix/private/ispcp-arpl" ) {
		$rs = del_file("/var/spool/postfix/private/ispcp-arpl");
		if ($rs != 0){
			print "Can not delete /var/spool/postfix/private/ispcp-arpl!!!\n\n";
			send_error_mail('uninstall_mta()', "Can not delete /var/spool/postfix/private/ispcp-arpl!!!");
		}
	}

	if ( -e "/usr/sbin/maillogconvert.pl" ) {
		$rs = del_file("/usr/sbin/maillogconvert.pl");
		if ($rs != 0){
			print "Can not delete /usr/sbin/maillogconvert.pl!!!\n\n";
			send_error_mail('uninstall_mta()', "Can not delete /usr/sbin/maillogconvert.pl!!!");
		}
	}

	$rs = sys_command("$main::cfg{'CMD_NEWALIASES'} >> /tmp/ispcp-uninstall-services.log");
	if ($rs != 0){
		print "Command $main::cfg{'CMD_NEWALIASES'} failed!!! Check MTA config file\n\n";
		send_error_mail('uninstall_mta()', "Command $main::cfg{'CMD_NEWALIASES'} failed!!! Check MTA config file!!!");
	}

	sys_command_rs("$main::cfg{'CMD_MTA'} start >> /tmp/ispcp-uninstall-services.log");

	push_el(\@main::el, 'uninstall_mta()', 'Ending...');

	return 0;

}

sub uninstall_po {

	my ($rs, $rdata) = (undef, undef);

	push_el(\@main::el, 'uninstall_po()', 'Starting...');

	my $cfg_dir = "$main::cfg{'CONF_DIR'}/courier";

	my $bk_dir = "$cfg_dir/backup";

	my $wrk_dir = "$cfg_dir/working";

	my ($cfg_tpl, $cfg, $cmd) = (undef, undef, undef);

	sys_command_rs("$main::cfg{'CMD_AUTHD'} stop >> /tmp/ispcp-uninstall-services.log");

	sys_command_rs("$main::cfg{'CMD_IMAP'} stop >> /tmp/ispcp-uninstall-services.log");

	sys_command_rs("$main::cfg{'CMD_POP'} stop >> /tmp/ispcp-uninstall-services.log");

	$cmd = "$main::cfg{'CMD_CP'} -p $bk_dir/authdaemonrc.system $main::cfg{'AUTHLIB_CONF_DIR'}/authdaemonrc";
	$rs = sys_command($cmd);
	if ($rs != 0){
		print "File $bk_dir/authdaemonrc.system do not exist!!! Can not be restored\n\n";
		send_error_mail('uninstall_po()', "File $bk_dir/authdaemonrc.system do not exist!!! Can not be restored");
	}

	if (-e "$bk_dir/authmodulelist.system") {
		$cmd = "$main::cfg{'CMD_CP'} -p $bk_dir/authmodulelist.system $main::cfg{'AUTHLIB_CONF_DIR'}/authmodulelist";
		$rs = sys_command($cmd);
		if ($rs != 0){
			print "File $bk_dir/authmodulelist.system do not exist!!! Can not be restored\n\n";
			send_error_mail('uninstall_po()', "File $bk_dir/authmodulelist.system do not exist!!! Can not be restored");
		}
	}

	if (-e "$bk_dir/userdb.system") {
		$cmd = "$main::cfg{'CMD_CP'} -p $bk_dir/userdb.system $main::cfg{'AUTHLIB_CONF_DIR'}/userdb";
		$rs = sys_command($cmd);
	}

	if ($rs != 0){
		print "File $bk_dir/userdb.system do not exist!!! Can not be restored\n\n";
		send_error_mail('uninstall_po()', "File $bk_dir/userdb.system do not exist!!! Can not be restored");
	}

	$rs = sys_command($main::cfg{'CMD_MAKEUSERDB'});
	if ($rs != 0){
		print "Command $main::cfg{'CMD_MAKEUSERDB'} failed!!! Check config file\n\n";
		send_error_mail('uninstall_mta()', "Command $main::cfg{'CMD_MAKEUSERDB'} failed!!! Check config file!!!");
	}

	sys_command_rs("$main::cfg{'CMD_AUTHD'} start >> /tmp/ispcp-uninstall-services.log");

	sys_command_rs("$main::cfg{'CMD_IMAP'} start >> /tmp/ispcp-uninstall-services.log");

	sys_command_rs("$main::cfg{'CMD_POP'} start >> /tmp/ispcp-uninstall-services.log");

	push_el(\@main::el, 'uninstall_po()', 'Ending...');

	return 0;

}

sub uninstall_ftpd {

	my ($rs, $rdata) = (undef, undef);

	push_el(\@main::el, 'uninstall_ftpd()', 'Starting...');

	my $cfg_dir = "$main::cfg{'CONF_DIR'}/proftpd";

	my $bk_dir = "$cfg_dir/backup";

	my ($cfg_tpl, $cfg, $cmd) = (undef, undef, undef);

	sys_command_rs("$main::cfg{'CMD_FTPD'} stop >> /tmp/ispcp-uninstall-services.log");

	if (-e "$bk_dir/proftpd.conf.system") {

		$cmd = "$main::cfg{'CMD_CP'} -p $bk_dir/proftpd.conf.system $main::cfg{'FTPD_CONF_FILE'}";
		$rs = sys_command($cmd);
		if ($rs != 0){
			print "File $bk_dir/proftpd.conf.system can not be copied\n\n";
			send_error_mail('uninstall_ftpd()', "File $bk_dir/proftpd.conf.system can not be copied");
		}

		$rs = del_dir($main::cfg{'FTPD_CONF_DIR'});
		if ($rs != 0){
			print "Folder $main::cfg{'FTPD_CONF_DIR'} can not be deleted\n\n";
			send_error_mail('uninstall_ftpd()', "Folder $main::cfg{'FTPD_CONF_DIR'} can not be deleted");
		}

	} else {
		print "Backup files $bk_dir/proftpd.conf.system can not be founded\n";
		send_error_mail('uninstall_ftpd()', "Backup files $bk_dir/proftpd.conf.system can not be founded!!!");
	}

	sys_command_rs("$main::cfg{'CMD_FTPD'} start >> /tmp/ispcp-uninstall-services.log");

	push_el(\@main::el, 'uninstall_ftpd()', 'Ending...');

	return 0;

}

sub uninstall_ispcpd {

	my ($rs, $rdata) = (undef, undef);

	push_el(\@main::el, 'uninstall_ispcpd()', 'Starting...');

	sys_command_rs("$main::cfg{'CMD_ISPCPD'} stop >> /tmp/ispcp-uninstall-services.log");

	sys_command_rs("$main::cfg{'CMD_ISPCPN'} stop >> /tmp/ispcp-uninstall-services.log");

	if ( -x "/usr/lib/lsb/install_initd" ) { #LSB 3.1 Core section 20.4 compatibility

		sys_command_rs("/usr/lib/lsb/install_initd $main::cfg{'CMD_ISPCPD'} >> /tmp/ispcp-uninstall-services.log");
		sys_command_rs("/usr/lib/lsb/install_initd $main::cfg{'CMD_ISPCPN'} >> /tmp/ispcp-uninstall-services.log");

	}

	$rs = del_file("$main::cfg{'CMD_ISPCPD'}");
	if ($rs != 0){
		print "File $main::cfg{'CMD_ISPCPD'} can not be deleted\n\n";
		send_error_mail('uninstall_ispcpd()', "File $main::cfg{'CMD_ISPCPD'} can not be deleted");
	}

	$rs = del_file("$main::cfg{'CMD_ISPCPN'}");
	if ($rs != 0){
		print "File $main::cfg{'CMD_ISPCPN'} can not be deleted\n\n";
		send_error_mail('uninstall_ispcpd()', "File $main::cfg{'CMD_ISPCPN'} can not be deleted");
	}

	if ( ! -x "/usr/lib/lsb/install_initd" && -x "/usr/sbin/update-rc.d" ) {

		sys_command_rs("/usr/sbin/update-rc.d ispcp_daemon remove >> /tmp/ispcp-uninstall-services.log");
		sys_command_rs("/usr/sbin/update-rc.d ispcp_network remove >> /tmp/ispcp-uninstall-services.log");

	}

	push_el(\@main::el, 'uninstall_ispcpd()', 'Ending...');

	return 0;

}

sub uninstall_ispcp {

	my ($rs, $rdata) = (undef, undef);

	push_el(\@main::el, 'uninstall_ispcp()', 'Starting...');

	$rs = del_dir($main::cfg{'CONF_DIR'});
	if ($rs != 0){
		print "Folder $main::cfg{'CONF_DIR'} can not be deleted\n\n";
		send_error_mail('uninstall_ispcp()', "Folder $main::cfg{'CONF_DIR'} can not be deleted");
	}

	$rs = del_dir($main::cfg{'SCOREBOARDS_DIR'});
	if ($rs != 0){
		print "Folder $main::cfg{'SCOREBOARDS_DIR'} can not be deleted\n\n";
		send_error_mail('uninstall_ispcp()', "Folder $main::cfg{'SCOREBOARDS_DIR'} can not be deleted");
	}

	$rs = del_dir($main::cfg{'ROOT_DIR'});
	if ($rs != 0){
		print "Folder $main::cfg{'ROOT_DIR'} can not be deleted\n\n";
		send_error_mail('uninstall_ispcp()', "Folder $main::cfg{'ROOT_DIR'} can not be deleted");
	}


	push_el(\@main::el, 'uninstall_ispcp()', 'Ending...');

	return 0;

}

sub uninstall_host_system {

	my ($rs, $rdata) = (undef, undef);

	push_el(\@main::el, 'uninstall_host_system()', 'Starting...');

	$rs = uninstall_system_users();
	return $rs if ($rs != 0);

	$rs = uninstall_system_dirs();
	return $rs if ($rs != 0);

	$rs = uninstall_sql();
	return $rs if ($rs != 0);

	$rs = uninstall_crontab();
	return $rs if ($rs != 0);

	$rs = uninstall_logrotate();
	return $rs if ($rs != 0);

	$rs = uninstall_httpd();
	return $rs if ($rs != 0);

	$rs = uninstall_mta();
	return $rs if ($rs != 0);

	$rs = uninstall_po();
	return $rs if ($rs != 0);

	$rs = uninstall_ftpd();
	return $rs if ($rs != 0);

	$rs = uninstall_named();
	return $rs if ($rs != 0);

	$rs = uninstall_ispcpd();
	return $rs if ($rs != 0);

	$rs = uninstall_ispcp();
	return $rs if ($rs != 0);

	push_el(\@main::el, 'uninstall_host_system()', 'Ending...');

	return 0;

}

################################################################################
##									MAIN									##
################################################################################

# Clear screen
system('clear');

my $rs = undef;

$rs = uninstall_start_up();
if ($rs != 0) {

	my $el_data = pop_el(\@main::el);

	my ($sub_name, $msg) = split(/$main::el_sep/, $el_data);

	print STDERR "$msg\n";

	exit 1;

}

$rs = user_dialog();
if ($rs != 0) {

	my $el_data = pop_el(\@main::el);

	my ($sub_name, $msg) = split(/$main::el_sep/, $el_data);

	print STDERR "$msg\n";

	exit 1;

}

$rs = uninstall_host_system();
if ($rs != 0) {

	my $el_data = pop_el(\@main::el);

	my ($sub_name, $msg) = split(/$main::el_sep/, $el_data);

	print STDERR "$msg\n";

	exit 1;

}

$rs = uninstall_shut_down();
if ($rs != 0) {

	my $el_data = pop_el(\@main::el);

	my ($sub_name, $msg) = split(/$main::el_sep/, $el_data);

	print STDERR "$msg\n";

	exit 1;

}
