#!/bin/sh

if [ ! -d language-files ]; then
        if [ ! -d ../language-files ]; then
            echo 'Neither language-files nor ../language-files are valid directories!'
            exit 1
        else
            cd ../language-files
        fi
else
    cd language-files 
fi



for i in *.po; do
	echo $i
	msgmerge -U $i ispCP.pot
done
