ALTER TABLE `vhcs2`.`login` ADD `ipaddr` varchar(15) NULL AFTER `session_id`;
ALTER TABLE `vhcs2`.`login` ADD `user_name` varchar(255) NULL AFTER `ipaddr`;
ALTER TABLE `vhcs2`.`login` ADD `login_count` tinyint(1) NULL AFTER `lastaccess`;
CREATE TABLE `vhcs2`.`config` (`name` varchar(255) NOT NULL default '',`value` varchar(255) NOT NULL default '',PRIMARY KEY  (`name`));
ALTER TABLE `vhcs2`.`admin` ADD `uniqkey_time` TIMESTAMP NULL AFTER `uniqkey`;
ALTER TABLE `vhcs2`.`admin` ADD UNIQUE ( `admin_name` );
ALTER TABLE `vhcs2`.`domain` ADD INDEX i_domain_domain_admin_id ( `domain_admin_id` );
ALTER TABLE `vhcs2`.`domain` ADD UNIQUE ( `domain_name` );
ALTER TABLE `vhcs2`.`domain_traffic` ADD INDEX i_domain_traffic_domain_id ( `domain_id` );
ALTER TABLE `vhcs2`.`htaccess_users` ADD `status` varchar(255) default NULL;
ALTER TABLE `vhcs2`.`htaccess_groups` ADD `status` varchar(255) default NULL;
ALTER TABLE `vhcs2`.`htaccess` CHANGE `status` `status` VARCHAR( 255 ) default NULL;
UPDATE `vhcs2`.`subdomain` SET `subdomain_status` = 'change' WHERE `subdomain_status` = 'ok';
UPDATE `vhcs2`.`domain` SET `domain_status` = 'change' WHERE `domain_status` = 'ok';
UPDATE `vhcs2`.`domain_aliasses` SET `alias_status` = 'change' WHERE `alias_status` = 'ok';
DROP TABLE IF EXISTS `vhcs2`.`lang_Deutsch`;
DROP TABLE IF EXISTS `vhcs2`.`lang_Portugues_Brasil`;
UPDATE `vhcs2`.`user_gui_props` SET `lang` = 'lang_German' WHERE `lang` = 'lang_Deutsch';
UPDATE `vhcs2`.`user_gui_props` SET `lang` = 'lang_PortuguesBrazil' WHERE `lang` = 'lang_Portugues_Brasil';
DELETE FROM `vhcs2`.`login`;
