# i-MSCP Listener::Dovecot::Service::Login listener file
# Copyright (C) 2017 Laurent Declercq <l.declercq@nuxwin.com>
# Copyright (C) 2016-2017 Sven Jantzen <info@svenjantzen.de>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA

#
## Allows to modify default service-login configuration options.
## This listener file requires dovecot version 2.1.0 or newer.
#

package Listener::Dovecot::Service::Login;

use strict;
use warnings;
use iMSCP::File;
use iMSCP::EventManager;
use Servers::po;

#
## Configuration parameters
#

# Service ports
# Note: Setting a port to 0 will close it
my $POP3_PORT = 110;
my $POP3_SSL_PORT = 995;
my $IMAP_PORT = 143;
my $IMAP_SSL_PORT = 993;

# Space separated list of IP addresses/hostnames to listen on.
# For instance:
#	- with 'localhost' as value the service-login will listen on localhost only
#	- with '*' as value, the service-login will listen on all IPv4 addresses
#	- with '::' as value, the service-login will listen on all IPv6 addresses
#	- with '*, ::' as value, the service-login will listen on all IPv4/IPv6 addresses
my $IMAP_LISTEN_ADDR = '* ::';
my $IMAP_SSL_LISTEN_ADDR = '* ::';
my $POP3_LISTEN_ADDR = '* ::';
my $POP3_SSL_LISTEN_ADDR = '* ::';

# Number of connections to handle before starting a new process. Typically
# the only useful values are 0 (unlimited) or 1. 1 is more secure, but 0
# is faster.
my $IMAP_SERVICE_COUNT = 0;
my $POP3_SERVICE_COUNT = 0;

#
## Please, don't edit anything below this line
#

iMSCP::EventManager->getInstance()->register(
    'beforePoBuildConf',
    sub {
        my (undef, $tplName) = @_;

        return 0 unless $tplName eq 'dovecot.conf';

        my $po = Servers::po->factory();

        my $file = iMSCP::File->new(
            $po->{'config'}->{'DOVECOT_CONF_DIR'}
                . '/imscp.d/60-dovecot-service-login.conf'
        );

        $file->set( <<"EOF" );
# DOVECOT(1) configuration file - auto-generated by i-MSCP
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

service imap-login {
    inet_listener imap {
        port = $IMAP_PORT
        address = $IMAP_LISTEN_ADDR
    }

    inet_listener imaps {
        port = $IMAP_SSL_PORT
        address = $IMAP_SSL_LISTEN_ADDR
        ssl = yes
    }

    service_count = $IMAP_SERVICE_COUNT
}

service pop3-login {
    inet_listener pop3 {
        port = $POP3_PORT
        address = $POP3_LISTEN_ADDR
    }

    inet_listener pop3s {
        port = $POP3_SSL_PORT
        address = $POP3_SSL_LISTEN_ADDR
        ssl = yes
    }

    service_count = $POP3_SERVICE_COUNT
}
EOF
        $file->save();
    }
);

1;
__END__
