.include <../../../../Makefile.fbsd>

install:

	$(SYSTEM_MAKE_DIRS) $(ROOT_CONF)/rc.d

	cp ispcp_daemon $(ROOT_CONF)/rc.d/ispcp_daemon.sh
	cp ispcp_network $(ROOT_CONF)/rc.d/ispcp_network.sh

	chown root:wheel $(ROOT_CONF)/rc.d/ispcp_network.sh $(ROOT_CONF)/rc.d/ispcp_daemon.sh
	chmod 0755 $(ROOT_CONF)/rc.d/ispcp_network.sh $(ROOT_CONF)/rc.d/ispcp_daemon.sh

uninstall:

	rm -f $(ROOT_CONF)/rc.d/ispcp_daemon.sh
	rm -f $(ROOT_CONF)/rc.d/ispcp_network.sh
