#! /bin/sh
#
# skeleton	example file to build /etc/init.d/ scripts.
#		This file should be used to construct scripts for /etc/init.d.
#
#		Written by Miquel van Smoorenburg <miquels@cistron.nl>.
#		Modified for Debian GNU/Linux
#		by Ian Murdock <imurdock@gnu.ai.mit.edu>.
#		Modified for Debian 
#		by Erik Lehmann <erik.lehmann@ispcp.net>
#		Modified for OpenBSD
#		by Carsten Schoene <ispcp@j0ke.net>
#
# Version:	@(#)skeleton  1.8  03-Mar-1998  miquels@cistron.nl
#
# This file was automatically customized by dh-make on Mon, 22 Apr 2002 16:15:28 +0300

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/var/www/ispcp/daemon/ispcp_daemon
PID=/var/run/ispcp-daemon.pid
NAME=ispcp_daemon
DESC=ispcp_daemon


test -f $DAEMON || exit 0

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "
	$DAEMON -p $PID
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	kill -9 `cat $PID`
        rm -f $PID
	echo "$NAME."
	;;
  restart|force-reload)
	$0 stop
	$0 start
	echo "$NAME."
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
