<?php $this->jQuery()->addOnload('$("#username").focus()');?>

<h2 class="user"><span>Add new user</span></h2>

<form name="add" method="post" action="<?php echo $this->url();?>">
    <fieldset>
        <legend>User information:</legend>
        <table>
			<tr>
				<td><label for="role">User role</label></td>
				<td>
					<select name="role" id="role">
					<?php foreach($this->roles as $role):?>
						<option value="<?php echo $role->id;?>" <?php echo ($this->role == $role->id) ? 'selected="selected"' : '';?>><?php echo ucFirst($role->role);?></option>
					<?php endforeach;?>
					</select>
				</td>
			</tr>
            <tr>
                <td><label for="username">Username</label></td>
                <td><input type="text" name="username" id="username" maxlength="8" value="<?php echo $this->escape($this->username);?>"/></td>
            </tr>
            <tr>
                <td><label for="password">Password</label></td>
                <td><input type="password" name="password" id="password" maxlength="8" value="<?php echo $this->escape($this->password);?>"/></td>
            </tr>
            <tr>
                <td><label for="password_confirm">Confirm password</label></td>
                <td><input type="password" name="password_confirm" id="password_confirm" maxlength="8" value="<?php echo $this->escape($this->passwordConfirm);?>"/></td>
            </tr>
            <tr>
                <td><label for="email">Email address</label></td>
                <td><input type="text" name="email" id="email" maxlength="255" value="<?php echo $this->escape($this->email);?>"/></td>
            </tr>
			<tr>
				<td><label for="is_active_yes">Activate user ?</label></td>
				<td>
					<input type="radio" name="is_active" id="is_active_yes" value="1" style="vertical-align:middle" <?php echo ($this->is_active) ? 'checked="checked"' : '';?>/>
					<span style="vertical-align:middle">Yes</span>
					<input type="radio" name="is_active" id="is_active_no" value="0" style="vertical-align:middle" <?php echo (!$this->is_active) ? 'checked="checked"' : '';?>/>
					<span style="vertical-align:middle">No</span>
                </td>
            </tr>
        </table>
    </fieldset>
	<div class="buttons">
	    <input name="submit" type="submit" class="button" value="Add user" />
	</div>
</form>	
