<?php $this->jQuery()->addOnload('
	$("#username").focus();
	$("#password").keyup(function(){$("#password_text").val($(this).val());$("#password_confirm").val("");});
	$("#password_text").keyup(function(){$("#password").val($(this).val());$("#password_confirm").val("");});
	$("#show_password").click(function(){$("#password,#password_text").toggle();});
	$("#show_password").toggle(function(){$(this).val("Hide password");},function(){$(this).val("Show password");});
');?>

<h2 class="user"><span>Add new user</span></h2>

<form name="addUserForm" method="post" action="<?php echo $this->url();?>">
    <fieldset>
        <legend>User information:</legend>
        <table>
			<tr>
				<td width="200"><label for="role">User role</label></td>
				<td>
					<select name="role" id="role">
					<?php foreach($this->roles as $role):?>
						<option value="<?php echo $role->id;?>" <?php echo ($this->role == $role->id) ? 'selected="selected"' : '';?>><?php echo ucFirst($role->role);?></option>
					<?php endforeach;?>
					</select>
				</td>
			</tr>
            <tr>
                <td width="200"><label for="username">Username</label></td>
                <td><input type="text" name="username" id="username" maxlength="8" value="<?php echo $this->escape($this->username);?>"/></td>
            </tr>
            <tr>
                <td width="200"><label for="password">Password</label></td>
                <td>
	                <input type="password" name="password" id="password" maxlength="8" style="vertical-align:middle" value="<?php echo $this->escape($this->password);?>"/>
	                <input type="text" name="password_text" id="password_text" maxlength="8" style="display:none;vertical-align:middle" value="<?php echo $this->escape($this->password);?>"/>
	                <input type="button" name="show_password" id="show_password" style="vertical-align:middle" value="Show password"/>
                </td>
            </tr>
            <tr>
                <td width="200"><label for="password_confirm">Confirm password</label></td>
                <td><input type="password" name="password_confirm" id="password_confirm" maxlength="8" value="<?php echo $this->escape($this->password_confirm);?>"/></td>
            </tr>
            <tr>
                <td width="200"><label for="email">Email address</label></td>
                <td><input type="text" name="email" id="email" maxlength="255" value="<?php echo $this->escape($this->email);?>"/></td>
            </tr>
			<tr>
				<td width="200"><label for="is_active_yes">Activate user ?</label></td>
				<td>
					<input type="radio" name="is_active" id="is_active_yes" class="buttons" value="1" style="vertical-align:middle" <?php echo ($this->is_active) ? 'checked="checked"' : '';?>/>
					<span style="vertical-align:middle">Yes</span>
					<input type="radio" name="is_active" id="is_active_no" class="buttons" value="0" style="vertical-align:middle" <?php echo (!$this->is_active) ? 'checked="checked"' : '';?>/>
					<span style="vertical-align:middle">No</span>
                </td>
            </tr>
        </table>
    </fieldset>
	<div class="buttons">
	    <input name="submit" type="submit" class="buttons" value="Add user" />
		<input type="reset" class="buttons" value="Reset" />
	</div>
</form>	
