<?php $this->jQuery()->addOnload('
	$("#password").focus();
	$("#password").keyup(function(){$("#password_text").val($(this).val());$("#password_confirm").val("");});
	$("#password_text").keyup(function(){$("#password").val($(this).val());$("#password_confirm").val("");});
	$("#show_password").click(function(){$("#password,#password_text").toggle();});
	$("#show_password").toggle(function(){$(this).val("Hide password");},function(){$(this).val("Show password");});
');?>

<h2 class="user"><span>Change password</span></h2>

<form name="changePasswordForm" method="post" action="<?php echo $this->url();?>">
    <fieldset>
        <legend>New password:</legend>
		<table>
            <tr>
                <td width="200"><label for="password">Password</label></td>
                <td>
	                <input type="password" name="password" id="password" maxlength="8" style="vertical-align:middle" value="<?php echo $this->escape($this->password);?>"/>
	                <input type="text" name="password_text" id="password_text" maxlength="8" style="display:none;vertical-align:middle" value="<?php echo $this->escape($this->password);?>"/>
	                <input type="button" name="show_password" id="show_password" style="vertical-align:middle" value="Show password"/>
                </td>
            </tr>
            <tr>
                <td width="200"><label for="password_confirm">Confirm password</label></td>
                <td><input type="password" name="password_confirm" id="password_confirm" maxlength="8" value="<?php echo $this->escape($this->password_confirm);?>"/></td>
            </tr>
		</table>
	</fieldset>
	<div class="buttons">
	    <input name="submit" type="submit" class="buttons" value="Change password" />
		<input type="reset" class="buttons" value="Reset" />
	</div>
</form>