<?php $this->headTitle($this->translate('Change password'));?>
<?php $this->jQuery()->addOnload('$("#password").focus();');?>

<h2 class="user"><span><?php echo $this->translate('Update password');?></span></h2>

<form name="changePasswordForm" method="post" action="<?php echo $this->url();?>">
    <fieldset>
        <legend><?php echo $this->translate('New password');?>:</legend>
		<table>
            <tr>
                <td width="200"><label for="password"><?php echo $this->translate('Password');?></label></td>
                <td>
	                <input type="password" name="password" id="password" maxlength="8" style="vertical-align:middle" value="<?php echo $this->escape($this->password);?>"/>
	                <input type="text" name="password_text" id="password_text" maxlength="8" style="display:none;vertical-align:middle" value="<?php echo $this->escape($this->password);?>"/>
                </td>
            </tr>
            <tr>
                <td width="200"><label for="password_confirm"><?php echo $this->translate('Confirm password');?></label></td>
                <td><input type="password" name="password_confirm" id="password_confirm" maxlength="8" value="<?php echo $this->escape($this->password_confirm);?>"/></td>
            </tr>
		</table>
	</fieldset>
	<div class="buttons">
	    <input name="submit" type="submit" class="buttons" value="<?php echo $this->translate('Update');?>" />
		<input type="reset" class="buttons" value="<?php echo $this->translate('Reset');?>" />
	</div>
</form>