<br /><br /><center>View script for controller <b>User</b> and script/action name <b>list</b></center>

<h2 class="users"><span>Administrators</span></h2>

<?php if(!empty($this->users->admin)): ?>
<table>
    <tr>
        <th>Username</th>
        <th>Creation date</th>
        <th>Created by</th>
        <th>Options</th>
    </tr>
	<?php foreach($this->users->admin as $admin): ?>
    <tr>
        <td><?php echo $admin->username;?></td>
        <td><?php echo (is_null($admin->created_on)) ? 'n/a' : $admin->created_on;?></td>
        <td><?php echo (is_null($admin->parent_id)) ? 'system' : $admin->parent_id;?></td>
        <td>
            <a href="/admin/user/edit/<?php echo $admin->id?>" class="icon i_user">Edit</a>
        </td>
    </tr>
	<?php endforeach;?>
</table>
<?php else:?>
<div class="info">You have not admin yet</div>
<?php endif;?>

<h2 class="users"><span>Resellers</span></h2>

<?php if(!empty($this->users->reseller)): ?>
<table>
    <tr>
        <th>Username</th>
        <th>Creation date</th>
        <th>Created by</th>
        <th>Options</th>
    </tr>
	<?php foreach($this->users->resellers as $reseller): ?>
    <tr>
        <td><?php echo $reseller->username;?></td>
        <td><?php echo $reseller->created_on;?></td>
        <td><?php echo $reseller->parent_id;?></td>
        <td>
            <a href="/admin/user/edit/<?php echo $reseller->id?>" class="icon i_user">Edit</a>
        </td>
    </tr>
	<?php endforeach;?>
</table>
<?php else:?>
<div class="info">You have not reseller yet</div>
<?php endif;?>

<h2 class="users"><span>Customers</span></h2>

<?php if(!empty($this->users->resellers)): ?>
<table>
    <tr>
        <th>Username</th>
        <th>Creation date</th>
        <th>Created by</th>
        <th>Options</th>
    </tr>
	<?php foreach($this->users->customers as $customer): ?>
    <tr>
        <td><?php echo $customer->username;?></td>
        <td><?php echo $customer->created_on;?></td>
        <td><?php echo $customer->parent_id;?></td>
        <td>
            <a href="/admin/user/edit/<?php echo $customer->id?>" class="icon i_user">Edit</a>
        </td>
    </tr>
	<?php endforeach;?>
</table>
<?php else:?>
<div class="info">You have not customer yet</div>
<?php endif;?>