<?php $this->headTitle($this->translate('List users'));?>
<h2 class="users"><span><?php echo $this->translate('Administrators');?></span></h2>

<?php if(!empty($this->users->admin)): ?>
<table>
    <tr>
        <th><?php echo $this->translate('Username');?></th>
        <th><?php echo $this->translate('Creation date');?></th>
        <th><?php echo $this->translate('Created by');?>y</th>
        <th><?php echo $this->translate('Options');?></th>
    </tr>
	<?php foreach($this->users->admin as $admin): ?>
    <tr>
        <td><?php echo $admin->username;?></td>
        <td><?php echo (is_null($admin->created_on)) ? $this->translate('n/a') : $admin->created_on;?></td>
        <td><?php echo (is_null($admin->parent_id)) ? $this->translate('system') : $admin->parent_id;?></td>
        <td>
            <a href="/admin/user/edit/<?php echo $admin->id?>" class="icon i_user"><?php echo $this->translate('Edit');?></a>
        </td>
    </tr>
	<?php endforeach;?>
</table>
<?php else:?>
<div class="info"><?php echo $this->translate('You have not admin yet');?></div>
<?php endif;?>

<h2 class="users"><span><?php echo $this->translate('Resellers');?></span></h2>

<?php if(!empty($this->users->reseller)): ?>
<table>
    <tr>
        <th><?php echo $this->translate('Username');?></th>
        <th><?php echo $this->translate('Creation date');?></th>
        <th><?php echo $this->translate('Created by');?></th>
        <th><?php echo $this->translate('Options');?></th>
    </tr>
	<?php foreach($this->users->resellers as $reseller): ?>
    <tr>
        <td><?php echo $reseller->username;?></td>
        <td><?php echo $reseller->created_on;?></td>
        <td><?php echo $reseller->parent_id;?></td>
        <td>
            <a href="/admin/user/edit/<?php echo $reseller->id?>" class="icon i_user"><?php echo $this->translate('Edit');?></a>
        </td>
    </tr>
	<?php endforeach;?>
</table>
<?php else:?>
<div class="info"><?php echo $this->translate('You have not reseller yet');?></div>
<?php endif;?>

<h2 class="users"><span><?php echo $this->translate('Customers');?></span></h2>

<?php if(!empty($this->users->resellers)): ?>
<table>
    <tr>
        <th><?php echo $this->translate('Username');?></th>
        <th><?php echo $this->translate('Creation date');?></th>
        <th><?php echo $this->translate('Created by');?></th>
        <th><?php echo $this->translate('Options');?></th>
    </tr>
	<?php foreach($this->users->customers as $customer): ?>
    <tr>
        <td><?php echo $customer->username;?></td>
        <td><?php echo $customer->created_on;?></td>
        <td><?php echo $customer->parent_id;?></td>
        <td>
            <a href="/admin/user/edit/<?php echo $customer->id?>" class="icon i_user"><?php echo $this->translate('Edit');?></a>
        </td>
    </tr>
	<?php endforeach;?>
</table>
<?php else:?>
<div class="info"><?php echo $this->translate('You have not customer yet');?></div>
<?php endif;?>
