		<!-- BDP: page_message -->
		<div class="{MESSAGE_CLS} message">{MESSAGE}</div>
		<!-- EDP: page_message -->
		<div id="outer">
			<div id="middle">
				<div id="inner">
					<form name="login_frm" action="index.php" method="post">
						<fieldset>
							<label>Username:<input type="text" name="uname" id="uname" value="" maxlength="255" tabindex="1" /></label>
							<label>Password:<input type="password" name="upass" id="upass" value="" maxlength="255" tabindex="2" /></label>
							<div class="buttons">
							<!-- BDP: lostpwd_button -->
								<input style="text-align:left;padding-left:15px;" type="button" name="lostpwd" value="Lost Password" tabindex="7" onclick="location.href='/lostpassword';return false"/>&nbsp;&nbsp;&nbsp;
							<!-- EDP: lostpwd_button -->
								<input type="submit" name="" value="Login" tabindex="3" />
							</div>
							<!-- /* Uncomment this to show the ssl switch */
							<div style="margin-top:15px;">
								<a class="icon i_lock" href="{TR_SSL_LINK}" title="{TR_SSL_DESCRIPTION}">{TR_SSL_DESCRIPTION}</a>
							</div> -->
						</fieldset>
					</form>
					<div class="toolsbox">
    					<ul class="icons">
       						<li><a class="pma" href="{TR_PMA_LINK}" tabindex="4">PhpMyAdmin</a></li>
       						<li><a class="filemanager" href="{TR_FTP_LINK}" tabindex="5">FileManager</a></li>
       						<li><a class="webmail" href="{TR_WEBMAIL_LINK}" tabindex="6">Webmail</a></li>
   						</ul>
					</div>
				</div>
			</div>
		</div>
