#!/bin/sh

# description:
#
# updates/merges all language specific .po files with strings of the
# main file ispcp.pot
#

set -e

if [ ! -d language-files ]; then
	if [ ! -d ../../language-files ]; then
		echo 'Neither language-files nor ../../language-files are valid directories!'
		exit 1
	else
		cd ../../language-files/po
	fi
else
	cd language-files/po
fi


for i in *.po; do
	echo $i
	msgmerge -U $i ispCP.pot
done
